import type { QuizRow } from "../quiz-types";

export const bugReportingFundamentalsQuizzes: QuizRow[] = [
  {
    lesson_title: "Bug Reporting Fundamentals",
    question: "What is the difference between bug severity and priority?",
    option_a: "They mean the same thing",
    option_b: "Severity is the technical impact; priority is the urgency to fix",
    option_c: "Priority is the technical impact; severity is the urgency",
    option_d: "Severity is set by developers; priority by QA",
    answer: "B",
    explanation: "Severity = how bad the impact is technically. Priority = how urgently it needs fixing (business decision). A typo on the homepage might be low severity but high priority.",
  },
  {
    lesson_title: "Bug Reporting Fundamentals",
    question: "Which is the best bug title?",
    option_a: "Login broken",
    option_b: "Page error",
    option_c: "Login button unresponsive when email contains + character",
    option_d: "Bug in authentication",
    answer: "C",
    explanation: "Good bug titles are specific: what is broken + under what conditions. This lets developers understand the scope without reading the full report.",
  },
  {
    lesson_title: "Bug Reporting Fundamentals",
    question: "Why is 'Steps to Reproduce' the most critical section of a bug report?",
    option_a: "It shows the severity of the bug",
    option_b: "Without it, developers cannot reliably reproduce and fix the bug",
    option_c: "It determines who fixes the bug",
    option_d: "It calculates the priority of the bug",
    answer: "B",
    explanation: "Developers need to reproduce the bug to understand and fix it. Vague or incomplete reproduction steps are the #1 cause of bugs being marked 'Cannot Reproduce'.",
  },
  {
    lesson_title: "Bug Reporting Fundamentals",
    question: "A critical bug that crashes the payment system but only happens once is best described as:",
    option_a: "High Severity, High Priority",
    option_b: "Low Severity, Low Priority",
    option_c: "High Severity, Low Priority",
    option_d: "Low Severity, High Priority",
    answer: "A",
    explanation: "Payment system crashes are critical business impact (high severity) AND need immediate attention regardless of frequency (high priority).",
  },
  {
    lesson_title: "Bug Reporting Fundamentals",
    question: "What should you include in the 'Environment' field of a bug report?",
    option_a: "Your personal opinion about the feature",
    option_b: "OS, browser version, app version, and URL where the bug occurred",
    option_c: "The developer's name",
    option_d: "Your test case ID only",
    answer: "B",
    explanation: "Environment details (OS, browser, version, URL) help developers reproduce the bug in the same conditions. The same bug may not appear on different OS/browser combinations.",
  },
  {
    lesson_title: "Bug Reporting Fundamentals",
    question: "What does 'intermittent' reproducibility mean?",
    option_a: "The bug happens every time",
    option_b: "The bug only happens in production",
    option_c: "The bug happens some of the time but not consistently",
    option_d: "The bug cannot be reproduced",
    answer: "C",
    explanation: "Intermittent bugs don't reproduce every time — they might occur 30-70% of attempts. These are especially difficult to diagnose and fix.",
  },
  {
    lesson_title: "Bug Reporting Fundamentals",
    question: "When should you attach a screenshot or video to a bug report?",
    option_a: "Never — they take up too much space",
    option_b: "Only for UI bugs",
    option_c: "Always when possible — visual evidence speeds up developer understanding",
    option_d: "Only when the bug is Critical severity",
    answer: "C",
    explanation: "Visual evidence (screenshots, videos, logs) dramatically speeds up bug resolution by giving developers immediate context without needing to reproduce it first.",
  },
  {
    lesson_title: "Bug Reporting Fundamentals",
    question: "A bug report where 'Expected Result' and 'Actual Result' are identical indicates:",
    option_a: "A valid bug",
    option_b: "A critical bug",
    option_c: "The test passed — no defect",
    option_d: "The environment is broken",
    answer: "C",
    explanation: "A bug exists when actual results differ from expected results. If they match, the feature works as specified — it's not a bug.",
  },
  {
    lesson_title: "Bug Reporting Fundamentals",
    question: "Who assigns priority to a bug?",
    option_a: "Always the QA engineer who found it",
    option_b: "Always the developer who fixes it",
    option_c: "Business/product owner or team consensus",
    option_d: "The test management tool automatically",
    answer: "C",
    explanation: "Priority is a business decision — it depends on business impact, customer impact, and release timelines. Product owners or the team make this decision, not QA alone.",
  },
  {
    lesson_title: "Bug Reporting Fundamentals",
    question: "What is an 'orphan bug'?",
    option_a: "A bug not linked to any test case or requirement",
    option_b: "A bug only reproducible in production",
    option_c: "A bug that cannot be reproduced",
    option_d: "A bug reported by an external user",
    answer: "A",
    explanation: "An orphan bug has no traceability to requirements or test cases — making it hard to understand its scope and impact on the release.",
  },
];
