import type { QuizRow } from "../quiz-types";

export const fullJavascriptForQaAutomationQuizzes: QuizRow[] = [
  {
    lesson_title: "Full JavaScript for QA Automation",
    question: "Why is JavaScript especially useful for QA automation?",
    option_a: "It is only used for database migrations",
    option_b: "Many modern QA tools such as Playwright, Cypress, Postman scripts, and k6 use JavaScript concepts",
    option_c: "It removes the need for test planning",
    option_d: "It can guarantee an application has no bugs",
    answer: "B",
    explanation: "JavaScript is widely used in modern QA tooling, especially browser automation, API testing, data setup, and performance scripts.",
  },
  {
    lesson_title: "Full JavaScript for QA Automation",
    question: "Which keyword should you usually use when a value should not be reassigned?",
    option_a: "var",
    option_b: "let",
    option_c: "const",
    option_d: "static",
    answer: "C",
    explanation: "Use const by default for values that should not be reassigned. Use let only when the variable needs to change.",
  },
  {
    lesson_title: "Full JavaScript for QA Automation",
    question: "In QA automation, what is a common use for JavaScript objects?",
    option_a: "Representing API payloads, responses, fixtures, and test data",
    option_b: "Replacing all assertions",
    option_c: "Pausing tests for a fixed number of seconds",
    option_d: "Avoiding test data setup",
    answer: "A",
    explanation: "Objects are key-value structures, which makes them perfect for request bodies, API responses, fixtures, and generated test data.",
  },
  {
    lesson_title: "Full JavaScript for QA Automation",
    question: "What does async/await help with in test automation?",
    option_a: "Writing CSS selectors",
    option_b: "Handling operations that take time, such as browser actions and API calls",
    option_c: "Deleting test reports",
    option_d: "Turning manual tests into requirements",
    answer: "B",
    explanation: "Browser interactions, network requests, and setup steps are asynchronous. async/await lets tests wait for those operations cleanly.",
  },
  {
    lesson_title: "Full JavaScript for QA Automation",
    question: "What is a likely problem if a tester forgets to await an async browser action?",
    option_a: "The test may assert before the action finishes, causing flaky results",
    option_b: "The browser will automatically close",
    option_c: "The test will always pass",
    option_d: "The API response will become XML",
    answer: "A",
    explanation: "Forgetting await can make assertions run too early. This is a common source of unreliable automation.",
  },
  {
    lesson_title: "Full JavaScript for QA Automation",
    question: "Why are helper functions useful in automated tests?",
    option_a: "They hide all failures from reports",
    option_b: "They prevent any need for assertions",
    option_c: "They reduce duplication and make repeated setup easier to maintain",
    option_d: "They make tests run only in production",
    answer: "C",
    explanation: "Helpers are useful for repeated tasks like creating users, logging in, generating data, or calling APIs. They keep tests shorter and easier to update.",
  },
  {
    lesson_title: "Full JavaScript for QA Automation",
    question: "Which equality operator is recommended for precise JavaScript test checks?",
    option_a: "===",
    option_b: "==",
    option_c: "=",
    option_d: "!=",
    answer: "A",
    explanation: "Strict equality (===) avoids JavaScript type coercion, which makes test checks more predictable.",
  },
  {
    lesson_title: "Full JavaScript for QA Automation",
    question: "What is data-driven testing in JavaScript?",
    option_a: "Deleting data after every manual test",
    option_b: "Running the same test logic with multiple input objects or array items",
    option_c: "Testing only database tables",
    option_d: "Writing one test with no inputs",
    answer: "B",
    explanation: "Data-driven tests use arrays or objects to run the same behavior checks with multiple inputs and expected results.",
  },
  {
    lesson_title: "Full JavaScript for QA Automation",
    question: "What should a good QA helper error message do?",
    option_a: "Be empty so logs stay short",
    option_b: "Clearly explain what setup or assertion failed",
    option_c: "Always blame the browser",
    option_d: "Hide the failing status code",
    answer: "B",
    explanation: "Clear helper errors reduce debugging time, especially when tests fail in CI.",
  },
  {
    lesson_title: "Full JavaScript for QA Automation",
    question: "Which example is the best reason to create a test data factory?",
    option_a: "To create unique users for each test run and avoid collisions",
    option_b: "To remove all negative test cases",
    option_c: "To make tests depend on each other",
    option_d: "To skip API validation",
    answer: "A",
    explanation: "Factories create predictable, unique data for tests. This helps avoid collisions between test runs and parallel jobs.",
  },
];
