import type { QuizRow } from "../quiz-types";

export const softwareTestingLifeCycleStlcQuizzes: QuizRow[] = [
  {
    lesson_title: "Software Testing Life Cycle (STLC)",
    question: "How many phases are there in the STLC?",
    option_a: "4",
    option_b: "5",
    option_c: "6",
    option_d: "7",
    answer: "C",
    explanation: "The STLC has 6 phases: Requirement Analysis, Test Planning, Test Case Development, Test Environment Setup, Test Execution, and Test Closure.",
  },
  {
    lesson_title: "Software Testing Life Cycle (STLC)",
    question: "What is the first phase of STLC?",
    option_a: "Test Planning",
    option_b: "Test Execution",
    option_c: "Requirement Analysis",
    option_d: "Test Case Development",
    answer: "C",
    explanation: "Requirement Analysis is the first phase — QA studies the requirements to understand what must be tested before any planning begins.",
  },
  {
    lesson_title: "Software Testing Life Cycle (STLC)",
    question: "What document is produced during the Test Planning phase?",
    option_a: "Requirements Traceability Matrix",
    option_b: "Test Plan",
    option_c: "Defect Report",
    option_d: "Test Summary Report",
    answer: "B",
    explanation: "The Test Planning phase produces the Test Plan — covering scope, approach, resources, schedule, and risks.",
  },
  {
    lesson_title: "Software Testing Life Cycle (STLC)",
    question: "What is the entry criterion for the Test Execution phase?",
    option_a: "All bugs are fixed",
    option_b: "Test cases are written and the test environment is set up",
    option_c: "The product is deployed to production",
    option_d: "Management approval is received",
    answer: "B",
    explanation: "Test Execution can begin when test cases are ready and the test environment is configured and verified to work.",
  },
  {
    lesson_title: "Software Testing Life Cycle (STLC)",
    question: "What happens during the Test Closure phase?",
    option_a: "New test cases are written",
    option_b: "Bugs are filed for the first time",
    option_c: "Metrics are analyzed and a test summary report is created",
    option_d: "The test environment is set up",
    answer: "C",
    explanation: "Test Closure is the wrap-up phase: analyze metrics, document lessons learned, create the test summary report, and archive test artifacts.",
  },
  {
    lesson_title: "Software Testing Life Cycle (STLC)",
    question: "During which STLC phase are test cases peer-reviewed?",
    option_a: "Test Planning",
    option_b: "Test Case Development",
    option_c: "Test Execution",
    option_d: "Test Closure",
    answer: "B",
    explanation: "Test Case Development includes writing test cases AND having them peer-reviewed to ensure quality before execution.",
  },
  {
    lesson_title: "Software Testing Life Cycle (STLC)",
    question: "What is a smoke test in the context of environment setup?",
    option_a: "A test to find performance issues",
    option_b: "A quick check that the test environment is working",
    option_c: "A test that fills the database with data",
    option_d: "A security vulnerability scan",
    answer: "B",
    explanation: "In environment setup, a smoke test verifies that the environment is configured correctly and basic functionality works before full testing begins.",
  },
  {
    lesson_title: "Software Testing Life Cycle (STLC)",
    question: "What is an exit criterion?",
    option_a: "Conditions that must be met to start a testing phase",
    option_b: "Conditions that must be met to end a testing phase",
    option_c: "Conditions under which testing is skipped",
    option_d: "The final test case in a suite",
    answer: "B",
    explanation: "Exit criteria define when a testing phase is considered complete. Example: 100% test cases executed, no open Critical bugs, test coverage > 80%.",
  },
  {
    lesson_title: "Software Testing Life Cycle (STLC)",
    question: "What is produced at the end of the STLC?",
    option_a: "A new Test Plan",
    option_b: "Updated requirements",
    option_c: "Test Closure Report",
    option_d: "Source code",
    answer: "C",
    explanation: "The Test Closure Report summarizes all testing activities, metrics, lessons learned, and formally closes the testing effort.",
  },
  {
    lesson_title: "Software Testing Life Cycle (STLC)",
    question: "During Requirement Analysis, what is the output?",
    option_a: "Test cases",
    option_b: "Requirements Understanding Document (RUD) or similar",
    option_c: "Bug reports",
    option_d: "Test scripts",
    answer: "B",
    explanation: "The output of Requirement Analysis is a Requirements Understanding Document (or RTM baseline) capturing what QA understands about what needs to be tested.",
  },
];
