import type { QuizRow } from "../quiz-types";

export const typesOfTestingQuizzes: QuizRow[] = [
  {
    lesson_title: "Types of Testing",
    question: "What does black-box testing mean?",
    option_a: "Testing in a dark room",
    option_b: "Testing without knowledge of internal code structure",
    option_c: "Testing only the backend",
    option_d: "Testing with full access to source code",
    answer: "B",
    explanation: "Black-box testing treats the system as a black box — the tester focuses on inputs and outputs without knowing the internal implementation.",
  },
  {
    lesson_title: "Types of Testing",
    question: "Which testing type verifies that new changes haven't broken existing functionality?",
    option_a: "Smoke Testing",
    option_b: "Acceptance Testing",
    option_c: "Regression Testing",
    option_d: "Unit Testing",
    answer: "C",
    explanation: "Regression testing ensures existing functionality still works after code changes. It's the most common candidate for automation.",
  },
  {
    lesson_title: "Types of Testing",
    question: "What is the primary goal of load testing?",
    option_a: "Find security vulnerabilities",
    option_b: "Verify the system handles expected normal traffic",
    option_c: "Push the system beyond its limits",
    option_d: "Test the UI layout",
    answer: "B",
    explanation: "Load testing simulates expected normal usage to verify the system meets performance SLAs under typical conditions.",
  },
  {
    lesson_title: "Types of Testing",
    question: "Who typically performs User Acceptance Testing (UAT)?",
    option_a: "QA engineers",
    option_b: "Developers",
    option_c: "End users or business stakeholders",
    option_d: "Project managers",
    answer: "C",
    explanation: "UAT is performed by actual end users or business stakeholders to validate that the system meets their business needs before go-live.",
  },
  {
    lesson_title: "Types of Testing",
    question: "What distinguishes integration testing from unit testing?",
    option_a: "Unit testing is faster",
    option_b: "Integration testing tests how multiple components work together",
    option_c: "Integration testing uses real databases, unit testing doesn't",
    option_d: "Unit testing covers more code",
    answer: "B",
    explanation: "Unit testing isolates individual functions/components. Integration testing verifies that multiple components interact correctly at their interfaces.",
  },
  {
    lesson_title: "Types of Testing",
    question: "What is the goal of stress testing?",
    option_a: "Verify normal operation under expected load",
    option_b: "Find the breaking point and observe failure behavior",
    option_c: "Test UI responsiveness",
    option_d: "Detect memory leaks over time",
    answer: "B",
    explanation: "Stress testing pushes the system beyond expected capacity to find the breaking point and observe how it fails (gracefully or catastrophically).",
  },
  {
    lesson_title: "Types of Testing",
    question: "Which type of testing evaluates how easy the software is to use?",
    option_a: "Security Testing",
    option_b: "Performance Testing",
    option_c: "Usability Testing",
    option_d: "Regression Testing",
    answer: "C",
    explanation: "Usability testing evaluates user experience — how easy and intuitive the software is to use for its intended audience.",
  },
  {
    lesson_title: "Types of Testing",
    question: "Soak testing is designed to find what type of issue?",
    option_a: "SQL injection vulnerabilities",
    option_b: "Memory leaks and performance degradation over extended time",
    option_c: "Broken UI layouts",
    option_d: "Missing features",
    answer: "B",
    explanation: "Soak testing (endurance testing) runs the system at normal load for an extended period to find issues like memory leaks that only appear over time.",
  },
  {
    lesson_title: "Types of Testing",
    question: "What is grey-box testing?",
    option_a: "Testing in staging environment only",
    option_b: "Testing with partial knowledge of the internal system",
    option_c: "Testing only non-functional requirements",
    option_d: "Testing using only automated tools",
    answer: "B",
    explanation: "Grey-box testing combines black-box (user perspective) and white-box (internal knowledge) — the tester has partial insight into the system's internals.",
  },
  {
    lesson_title: "Types of Testing",
    question: "Which testing type is BEST suited for automation?",
    option_a: "Exploratory Testing",
    option_b: "Usability Testing",
    option_c: "Ad-hoc Testing",
    option_d: "Regression Testing",
    answer: "D",
    explanation: "Regression testing is the best automation candidate — it's repetitive, stable, runs frequently, and has clear pass/fail criteria.",
  },
];
