import type { QuizRow } from "../../quiz-types";

export const testAutomationStrategyQuizzes: QuizRow[] = [
  {
    lesson_title: "Test Automation Strategy",
    question: "According to the test automation pyramid, what should have the MOST tests?",
    option_a: "E2E tests",
    option_b: "Integration tests",
    option_c: "Unit tests",
    option_d: "UI tests",
    answer: "C",
    explanation: "Unit tests form the pyramid's base — they're the fastest, cheapest, and most numerous. The typical ratio is 70% unit, 20% integration, 10% E2E.",
  },
  {
    lesson_title: "Test Automation Strategy",
    question: "What does ROI mean in the context of test automation?",
    option_a: "Rules Of Implementation",
    option_b: "Return On Investment — the value gained vs. the cost of automating",
    option_c: "Rate Of Increase in test execution",
    option_d: "Risk Of Implementation",
    answer: "B",
    explanation: "ROI in automation = time saved by automation vs. time spent writing/maintaining it. Automate when the savings exceed the investment over the expected lifetime.",
  },
  {
    lesson_title: "Test Automation Strategy",
    question: "Which type of testing should NOT typically be automated?",
    option_a: "Regression testing",
    option_b: "Smoke testing",
    option_c: "Exploratory testing",
    option_d: "API testing",
    answer: "C",
    explanation: "Exploratory testing requires human creativity, intuition, and real-time decision making — it cannot be effectively automated. Automation excels at repetitive, predictable tests.",
  },
  {
    lesson_title: "Test Automation Strategy",
    question: "What is the Page Object Model (POM)?",
    option_a: "A design pattern separating page element locators from test logic",
    option_b: "A tool for recording browser interactions",
    option_c: "A type of API testing framework",
    option_d: "A reporting tool for test results",
    answer: "A",
    explanation: "POM separates page interactions (locators, actions) from test logic. When the UI changes, only the page object is updated — not every test that uses it.",
  },
  {
    lesson_title: "Test Automation Strategy",
    question: "Your team has 0% automation coverage. Where do you start automating and why?",
    option_a: "Start with the most complex E2E flows to prove ROI quickly",
    option_b: "Start with the highest-risk, most frequently run tests — smoke tests and critical regression paths — to get immediate CI feedback value",
    option_c: "Automate everything at once for full coverage",
    option_d: "Start with unit tests written by developers — QA shouldn't automate yet",
    answer: "B",
    explanation: "Start where automation delivers immediate value: smoke tests (run on every deployment) and critical regression paths (frequently executed manually). These maximize ROI from day 1 and build team confidence in automation.",
  },
  {
    lesson_title: "Test Automation Strategy",
    question: "What is 'test flakiness' and why is it dangerous for CI reliability?",
    option_a: "A flaky test is one that takes too long to run",
    option_b: "A flaky test passes and fails intermittently without code changes — it erodes trust in CI, causes teams to ignore failures, and hides real regressions",
    option_c: "A flaky test is one written by a junior engineer",
    option_d: "Flakiness is normal and acceptable in E2E tests",
    answer: "B",
    explanation: "When tests are flaky, teams start ignoring CI failures ('it's probably flaky again'). This makes CI unreliable as a quality gate — real regressions get ignored alongside false ones. Flaky tests must be fixed or quarantined.",
  },
  {
    lesson_title: "Test Automation Strategy",
    question: "You have 500 UI E2E tests that take 4 hours to run. How do you reduce pipeline time?",
    option_a: "Delete tests until it runs in 1 hour",
    option_b: "Parallelize across multiple CI agents, move stable tests to nightly runs, and replace slow E2E tests with faster API tests where possible",
    option_c: "Only run tests on release branches",
    option_d: "Increase the server size to run faster",
    answer: "B",
    explanation: "Parallelization is the most impactful: 500 tests on 10 agents = ~24 min. Additionally: push slow stable tests to nightly, replace UI tests with equivalent API tests (10x faster). Both reduce wall time without losing coverage.",
  },
  {
    lesson_title: "Test Automation Strategy",
    question: "What is the 'inverted test pyramid' anti-pattern?",
    option_a: "Having more unit tests than E2E tests",
    option_b: "Having more E2E tests than unit tests — the most expensive, slowest, and most fragile layer dominates",
    option_c: "Testing only the UI and skipping APIs",
    option_d: "Running all tests manually",
    answer: "B",
    explanation: "The inverted pyramid has many slow, brittle E2E tests at the base and few unit tests. This results in slow CI pipelines, high maintenance costs, and unreliable feedback. Invert it: build a solid unit test foundation.",
  },
  {
    lesson_title: "Test Automation Strategy",
    question: "A developer says 'let's automate everything, including exploratory testing.' How do you respond?",
    option_a: "Agree — automation is always better than manual testing",
    option_b: "Explain that automation excels at verifying known scenarios repeatedly, but exploratory testing requires human judgment, creativity, and real-time investigation that cannot be scripted",
    option_c: "Agree to automate exploratory testing but warn it will take time",
    option_d: "Tell the developer to automate it themselves",
    answer: "B",
    explanation: "Automation verifies 'does the known behavior still work?' Exploratory testing asks 'what unexpected behaviors exist that we haven't thought of yet?' The latter requires human cognition. Both are necessary and complementary.",
  },
  {
    lesson_title: "Test Automation Strategy",
    question: "What are the key components of a test automation framework?",
    option_a: "A single test file and a browser",
    option_b: "Test runner, assertions library, reporting, page/API objects, test data management, CI integration, and configuration management",
    option_c: "Just Selenium or Playwright",
    option_d: "Only a requirements document",
    answer: "B",
    explanation: "A robust framework includes: test runner (Jest, Mocha), assertions (Chai, built-in), reporting (HTML/JUnit), page objects (maintainability), test data helpers, environment configs, and CI integration — each layer serves a purpose.",
  },
  {
    lesson_title: "Test Automation Strategy",
    question: "Your automation suite passes locally but fails in CI. What are the 3 most likely causes to check first?",
    option_a: "Network speed, monitor resolution, and team size",
    option_b: "Environment differences (headless vs. headed browser, different OS), timing/race conditions that work locally but fail under CI timing, and missing environment variables/secrets",
    option_c: "The CI server is broken — restart it",
    option_d: "The tests are flaky — accept the failures",
    answer: "B",
    explanation: "Classic causes of local-pass/CI-fail: (1) CI runs headless browser with different rendering, (2) CI is faster/slower causing timing assumptions to break, (3) environment variables or test data that exist locally but not in CI.",
  },
  {
    lesson_title: "Test Automation Strategy",
    question: "What is parallel test execution and what are its main challenges?",
    option_a: "Running tests one at a time in quick succession",
    option_b: "Running multiple tests simultaneously across threads/agents to reduce total execution time — challenges include test data conflicts, shared state, and flakiness amplification",
    option_c: "Running the same test twice to check for flakiness",
    option_d: "Running tests on multiple operating systems",
    answer: "B",
    explanation: "Parallel execution dramatically reduces runtime but requires tests to be truly independent — no shared test data, no shared database state, no shared environment configuration. Fixing these dependencies is the main parallelization challenge.",
  },
  {
    lesson_title: "Test Automation Strategy",
    question: "After 6 months, 40% of your automation tests are broken and unmaintained. What systemic changes do you make?",
    option_a: "Delete all broken tests and start over",
    option_b: "Implement a 'boy scout rule' (fix tests you touch), add automation health to the DoD, allocate sprint capacity for maintenance, and establish code review for test changes",
    option_c: "Hire a dedicated person to fix only broken tests",
    option_d: "Pause new feature testing until all tests are fixed",
    answer: "B",
    explanation: "Automation debt compounds. Systemic fixes: make test maintenance a first-class concern (in DoD, sprint allocation), enforce code review for test code, and treat broken tests as bugs — not backlog items that wait indefinitely.",
  },
  {
    lesson_title: "Test Automation Strategy",
    question: "What is the difference between record-and-playback automation and code-based automation?",
    option_a: "They produce the same quality of tests",
    option_b: "Record-and-playback generates brittle test scripts with hardcoded locators that break on UI changes; code-based automation uses page objects and explicit logic that is maintainable and robust",
    option_c: "Record-and-playback is more reliable",
    option_d: "Code-based automation is only for developers",
    answer: "B",
    explanation: "Record-and-playback is fast to create but produces unmaintainable scripts tied to exact UI state. Code-based automation requires more upfront investment but produces maintainable, reusable, and reliable test suites.",
  },
  {
    lesson_title: "Test Automation Strategy",
    question: "You've had automation for 1 year but bugs still reach production regularly. How do you explain this gap?",
    option_a: "Automation doesn't work — abandon it",
    option_b: "Automation only verifies scenarios it was written for — production bugs are in untested flows, edge cases, integrations, or newly introduced behaviors that automation doesn't cover yet",
    option_c: "The automation framework is wrong",
    option_d: "Automation should catch everything if implemented correctly",
    answer: "B",
    explanation: "Automation is a net, not a shield — it only catches what it covers. Gaps in coverage (missing test cases, new features not automated, untested edge cases) allow bugs through. The fix: continuously expand automation to cover discovered gaps.",
  },
];
