import type { QuizRow } from "../../quiz-types";

export const seleniumWebdriverQuizzes: QuizRow[] = [
  {
    lesson_title: "Selenium WebDriver",
    question: "What is the WebDriver protocol?",
    option_a: "A browser plugin that records user actions",
    option_b: "A W3C standard HTTP-based protocol that allows test code to send commands to a browser driver (ChromeDriver, GeckoDriver) which controls the real browser",
    option_c: "A proprietary Selenium API for browser communication",
    option_d: "A JavaScript injection framework",
    answer: "B",
    explanation: "WebDriver is a W3C standard: test code → WebDriver API → HTTP commands → browser driver → browser. This architecture allows language-agnostic browser automation without browser plugins.",
  },
  {
    lesson_title: "Selenium WebDriver",
    question: "What is the difference between findElement() and findElements()?",
    option_a: "findElement() is faster",
    option_b: "findElement() returns one WebElement and throws NoSuchElementException if not found; findElements() returns a list (empty if not found, never throws)",
    option_c: "findElements() only works with CSS selectors",
    option_d: "They return the same result",
    answer: "B",
    explanation: "findElement(): returns one element or throws. findElements(): returns List<WebElement> — empty if none found. Use findElements() when the element's presence is optional, or to count occurrences.",
  },
  {
    lesson_title: "Selenium WebDriver",
    question: "What is a StaleElementReferenceException and when does it occur?",
    option_a: "It occurs when the browser is too slow to find an element",
    option_b: "It occurs when a WebElement reference becomes invalid after the DOM was refreshed, navigated away, or the element was removed and re-rendered",
    option_c: "It occurs when two tests share the same WebDriver instance",
    option_d: "It means the element is hidden on the page",
    answer: "B",
    explanation: "StaleElementReferenceException: you found an element, then the DOM changed (page refresh, AJAX re-render). The old reference no longer points to a valid DOM node. Fix: re-find the element just before interacting with it.",
  },
  {
    lesson_title: "Selenium WebDriver",
    question: "Your Selenium test clicks a button but nothing happens and no exception is thrown. What are the most likely causes to investigate?",
    option_a: "The Selenium version is outdated",
    option_b: "The click hit a wrong element overlapping the target, the element is present but not interactable (covered by another element), or a JavaScript event handler is not yet attached at click time",
    option_c: "The browser has a popup blocking the click",
    option_d: "The test environment has no internet connection",
    answer: "B",
    explanation: "Silent click failures: (1) another element intercepts the click (use JavaScript click as workaround), (2) element exists but is not visible/enabled yet (add explicit wait for clickability), (3) JS event listener attached after the click — add a wait for the condition to be true.",
  },
  {
    lesson_title: "Selenium WebDriver",
    question: "What is Implicit Wait and why is it discouraged in favor of Explicit Wait?",
    option_a: "Implicit Wait is faster than Explicit Wait",
    option_b: "Implicit Wait applies a global timeout to every findElement call; Explicit Wait waits for a specific condition — combining both causes unpredictable timing and Implicit Wait cannot handle dynamic conditions",
    option_c: "Implicit Wait can only be used with Chrome",
    option_d: "They work the same way but have different syntax",
    answer: "B",
    explanation: "Implicit Wait: pollutes every findElement globally and interacts poorly with Explicit Wait. Explicit Wait: targets a specific condition (element clickable, text present) and is more readable and reliable. Best practice: use only Explicit Waits.",
  },
  {
    lesson_title: "Selenium WebDriver",
    question: "A test passes reliably when run alone but fails intermittently when run in a parallel suite. What is the most likely cause?",
    option_a: "The browser version is wrong",
    option_b: "Tests are sharing state — a common WebDriver instance, the same test data (same user account, same database record), or a shared file/resource — causing race conditions",
    option_c: "Parallel execution is not supported in Selenium",
    option_d: "The test itself has a bug that only appears sometimes",
    answer: "B",
    explanation: "Parallel failures almost always trace to shared state: same user logging in simultaneously, tests reading/modifying the same DB record, or tests writing to the same file. Fix: each parallel thread needs isolated test data and its own WebDriver instance.",
  },
  {
    lesson_title: "Selenium WebDriver",
    question: "Your test uses the locator `By.xpath('//div[3]/span[2]/button')`. Why is this problematic?",
    option_a: "XPath is not supported in Selenium",
    option_b: "This is a positional XPath tied to DOM structure — if any parent element is added/removed, the locator breaks even if the button still exists on the page",
    option_c: "The locator is too long",
    option_d: "Button elements cannot be found with XPath",
    answer: "B",
    explanation: "Positional XPath (//div[3]/span[2]) is extremely brittle — any UI restructuring breaks it. Better alternatives: `By.id`, `By.cssSelector('[data-testid='submit']')`, or semantic XPath like `//button[text()='Submit']`. Always prefer stable attributes.",
  },
  {
    lesson_title: "Selenium WebDriver",
    question: "What is the Page Object Model (POM) and what problem does it solve?",
    option_a: "POM is a tool that records test scripts automatically",
    option_b: "POM is a design pattern where each page has a class containing its locators and actions — when the UI changes, only the page object is updated, not every test that uses it",
    option_c: "POM is a type of test runner for Selenium",
    option_d: "POM generates test reports in HTML format",
    answer: "B",
    explanation: "Without POM, locators are scattered across hundreds of test files — one UI change breaks all of them. POM centralizes page interactions: `LoginPage.enterEmail()`, `LoginPage.clickSubmit()`. When the email field ID changes, fix it once in LoginPage.",
  },
  {
    lesson_title: "Selenium WebDriver",
    question: "What is Selenium Grid and when would you use it?",
    option_a: "A visual test reporting dashboard",
    option_b: "A hub-and-node architecture that allows distributing test execution across multiple machines and browsers simultaneously — used for cross-browser testing and parallel execution",
    option_c: "A tool for recording Selenium scripts",
    option_d: "A code coverage tool for Selenium tests",
    answer: "B",
    explanation: "Selenium Grid: one Hub coordinates test distribution to multiple Nodes (machines running different OS/browser combinations). Use it to run 500 tests across 10 machines in parallel, or to test against Chrome/Firefox/Safari simultaneously.",
  },
  {
    lesson_title: "Selenium WebDriver",
    question: "You're automating a multi-step file upload form. What are the key challenges and how do you handle them?",
    option_a: "File uploads cannot be automated with Selenium",
    option_b: "The OS file dialog cannot be controlled by WebDriver — use sendKeys() on the file input element to set the file path directly, bypassing the dialog entirely",
    option_c: "Use JavaScript to submit the form and skip the file input",
    option_d: "File uploads require a separate testing tool",
    answer: "B",
    explanation: "`driver.findElement(By.css('input[type=file]')).sendKeys('/path/to/file.pdf')` sets the file path directly without opening the OS dialog. This is the standard approach. The OS native dialog is outside WebDriver's control.",
  },
  {
    lesson_title: "Selenium WebDriver",
    question: "What is the difference between driver.quit() and driver.close()?",
    option_a: "They do the same thing",
    option_b: "driver.close() closes the current browser window; driver.quit() closes all windows and ends the WebDriver session — not calling quit() causes browser processes to accumulate and leak memory",
    option_c: "driver.quit() only works in Chrome",
    option_d: "driver.close() also terminates the WebDriver session",
    answer: "B",
    explanation: "Always call driver.quit() in teardown — it closes all windows AND kills the browser driver process. driver.close() only closes the focused window. Leaving WebDriver sessions open causes ChromeDriver/GeckoDriver processes to accumulate on the CI server.",
  },
  {
    lesson_title: "Selenium WebDriver",
    question: "Your Selenium suite takes 2 hours to run in CI. Propose 3 strategies to reduce this.",
    option_a: "Buy a faster server and run tests sequentially",
    option_b: "Parallelize across multiple threads/Selenium Grid nodes, move stable smoke tests to a fast suite run first, and replace low-value UI tests with equivalent API tests (10x faster)",
    option_c: "Delete tests until the suite fits in 1 hour",
    option_d: "Run only the tests that changed in the last commit",
    answer: "B",
    explanation: "Three pillars: (1) Parallelization — 200 tests on 10 nodes = 12 min instead of 2 hours. (2) Prioritization — smoke tests first for fast feedback, full suite nightly. (3) Test pyramid shift — replace UI tests with API tests where business logic validation doesn't require the UI.",
  },
  {
    lesson_title: "Selenium WebDriver",
    question: "What causes an ElementNotInteractableException?",
    option_a: "The element does not exist in the DOM",
    option_b: "The element exists in the DOM but cannot be interacted with — it is hidden, has zero dimensions, is disabled, or is covered by another element",
    option_c: "The locator strategy is wrong",
    option_d: "The browser does not support the element type",
    answer: "B",
    explanation: "ElementNotInteractableException: element is in DOM but not interactable. Common causes: display:none, visibility:hidden, covered by a modal/overlay, or not yet rendered. Fix: wait for element to be visible and enabled with WebDriverWait.",
  },
  {
    lesson_title: "Selenium WebDriver",
    question: "A form has dynamic input fields that appear based on previous selections. What Selenium strategy should you apply?",
    option_a: "Use Thread.sleep() to wait for the fields to appear",
    option_b: "Use WebDriverWait with ExpectedConditions.visibilityOfElementLocated() to wait for each dynamic field before interacting — never use fixed sleeps",
    option_c: "Reload the page after each selection",
    option_d: "Use JavaScript to force-show hidden fields before interacting",
    answer: "B",
    explanation: "Dynamic fields: always use explicit waits. `new WebDriverWait(driver, Duration.ofSeconds(10)).until(ExpectedConditions.visibilityOfElementLocated(By.id('dynamic-field')))`. Fixed sleeps are flaky — they either waste time or fail on slow machines.",
  },
  {
    lesson_title: "Selenium WebDriver",
    question: "You need to test that a success notification appears briefly and then disappears. How do you assert this with Selenium?",
    option_a: "Use Thread.sleep(5000) and hope the notification is still visible",
    option_b: "Wait for the element to be visible (assert it appears), then wait for the element to become invisible (assert it disappears) — both using explicit waits with appropriate timeouts",
    option_c: "Only assert the final state after the notification disappears",
    option_d: "Use a screenshot comparison tool to capture the notification",
    answer: "B",
    explanation: "Transient UI elements: (1) `WebDriverWait.until(ExpectedConditions.visibilityOf(notification))` — assert it appears. (2) `WebDriverWait.until(ExpectedConditions.invisibilityOf(notification))` — assert it disappears. Both states are testable with explicit waits.",
  },
];
