import type { QuizRow } from "../../quiz-types";

export const cypressIoModernTestingQuizzes: QuizRow[] = [
  {
    lesson_title: "Cypress.io Modern Testing",
    question: "What makes Cypress fundamentally different from Selenium in its architecture?",
    option_a: "Cypress only works with Chrome",
    option_b: "Cypress runs inside the browser alongside the application — not over a remote WebDriver protocol — giving it direct DOM access, native event firing, and automatic waiting",
    option_c: "Cypress uses a different programming language",
    option_d: "Cypress requires a browser plugin to work",
    answer: "B",
    explanation: "Selenium: test code → HTTP → WebDriver → browser. Cypress: test code runs in the same browser loop as the app, giving it direct access to the DOM, network layer, and JS context. This enables automatic retry, network stubbing, and debugging features not possible with Selenium.",
  },
  {
    lesson_title: "Cypress.io Modern Testing",
    question: "What is Cypress's automatic retry mechanism and what does it apply to?",
    option_a: "Cypress retries the entire test if it fails",
    option_b: "Cypress automatically retries assertions and queries against the DOM until they pass or time out — it retries cy.get(), .should(), .contains() but NOT actions like .click()",
    option_c: "Cypress retries network requests that return errors",
    option_d: "Cypress only retries tests marked with .retry()",
    answer: "B",
    explanation: "Cypress's command queue is asynchronous and retries automatically: `cy.get('.button').should('be.visible')` will keep checking until the button appears or the timeout (default 4s) is exceeded. This eliminates most explicit waits. Actions (.click(), .type()) are NOT retried.",
  },
  {
    lesson_title: "Cypress.io Modern Testing",
    question: "A junior tester writes `cy.wait(3000)` in every test to 'make sure the page loads.' Why is this wrong?",
    option_a: "cy.wait() syntax is incorrect — use cy.pause() instead",
    option_b: "Fixed waits make tests slow and still flaky — on a fast machine the app might load in 500ms (wasting 2.5s), on a slow CI server 3s might not be enough. Use cy.wait('@alias') or assertions instead",
    option_c: "cy.wait() only works for API calls",
    option_d: "Fixed waits are acceptable for page loads but not for API calls",
    answer: "B",
    explanation: "Replace `cy.wait(3000)` with: (1) `cy.wait('@apiAlias')` to wait for a specific intercepted request, (2) assertions like `.should('be.visible')` which retry automatically. Fixed sleeps are the #1 source of flaky Cypress tests.",
  },
  {
    lesson_title: "Cypress.io Modern Testing",
    question: "What is cy.intercept() and when would you use it?",
    option_a: "A command to intercept user keyboard input",
    option_b: "A command to intercept, inspect, modify, or stub HTTP network requests — used to test loading states, error responses, or make tests independent of backend availability",
    option_c: "A command to intercept browser navigation",
    option_d: "A tool to block third-party scripts from loading",
    answer: "B",
    explanation: "cy.intercept() is Cypress's network control layer: stub a 500 error response to test error handling, stub slow responses to test loading spinners, or spy on API calls to assert they were made with correct parameters. This makes E2E tests independent of backend state.",
  },
  {
    lesson_title: "Cypress.io Modern Testing",
    question: "What is the purpose of beforeEach() in Cypress and what should typically go inside it?",
    option_a: "It runs after each test to clean up state",
    option_b: "It runs before each test in the describe block — typically used for login, navigation to a known URL, seeding test data, or resetting state to ensure test isolation",
    option_c: "It is called once before all tests in the file",
    option_d: "It is only used for setting environment variables",
    answer: "B",
    explanation: "`beforeEach(() => { cy.login(); cy.visit('/dashboard'); })` ensures each test starts from a consistent state. Without it, a previous test's side effects can bleed into the next. Keep beforeEach focused on setup, not assertions.",
  },
  {
    lesson_title: "Cypress.io Modern Testing",
    question: "What are Cypress fixtures and how are they used?",
    option_a: "Fixtures are assertions that fix test failures",
    option_b: "Fixtures are static JSON/data files stored in the cypress/fixtures folder — loaded with cy.fixture() to provide consistent test data or stub API responses without hardcoding in test files",
    option_c: "Fixtures are reusable UI component snapshots",
    option_d: "Fixtures are browser configurations stored per test",
    answer: "B",
    explanation: "`cy.fixture('user.json').then(user => { cy.intercept('GET', '/api/user', user); })` loads static data from fixtures/user.json to stub the API. This keeps test data organized and reusable across multiple tests.",
  },
  {
    lesson_title: "Cypress.io Modern Testing",
    question: "Your Cypress tests pass in headed mode locally but fail in headless CI. What are the most common causes?",
    option_a: "Headless mode is a different product — use a different testing framework",
    option_b: "Viewport size differs (headless defaults smaller), animations complete differently, timing-sensitive assertions differ between headed/headless, or a third-party resource fails to load in CI's network environment",
    option_c: "Cypress does not support headless mode officially",
    option_d: "The test commands must be rewritten for headless execution",
    answer: "B",
    explanation: "Common headed/headless differences: (1) default viewport (set explicitly with `cy.viewport(1280, 720)`), (2) CI blocks external resources (stub them with cy.intercept()), (3) CSS animations — disable with `* { animation: none !important }` in CI. Always test headless locally before pushing.",
  },
  {
    lesson_title: "Cypress.io Modern Testing",
    question: "How do you handle authentication in Cypress tests to avoid logging in through the UI in every test?",
    option_a: "Skip authentication tests entirely to save time",
    option_b: "Use cy.request() to call the login API directly and set the auth token/cookie programmatically — this bypasses the UI login flow and is 10x faster than going through the login page",
    option_c: "Store credentials in a global variable and reuse across tests",
    option_d: "Use cy.session() only if cy.request() is unavailable",
    answer: "B",
    explanation: "Logging in via UI on every test wastes time and adds flakiness. `cy.request('POST', '/api/login', {email, password})` then setting `cy.setCookie()` or `localStorage.setItem()` logs in programmatically in milliseconds. Alternatively, cy.session() caches and restores session state.",
  },
  {
    lesson_title: "Cypress.io Modern Testing",
    question: "What does the .should() command do and why is it preferred over .then() for assertions?",
    option_a: "They are interchangeable and produce the same behavior",
    option_b: ".should() automatically retries the assertion until it passes or times out; .then() executes once immediately and will fail if the condition isn't met at that exact moment",
    option_c: ".should() is used for network assertions; .then() is for DOM assertions",
    option_d: ".should() only works with built-in Chai assertions",
    answer: "B",
    explanation: "`.should('have.text', 'Success')` retries until the element has the expected text (within timeout). `.then(el => expect(el.text()).to.equal('Success'))` runs once — if the text hasn't updated yet, it fails. Always prefer .should() for assertions on dynamic content.",
  },
  {
    lesson_title: "Cypress.io Modern Testing",
    question: "You have 200 Cypress E2E tests taking 40 minutes. The team wants feedback within 10 minutes. How do you achieve this?",
    option_a: "Delete tests until 10 minutes is achieved",
    option_b: "Split tests across parallel CI machines using Cypress Cloud or run specs in parallel with --parallel flag, and prioritize a smoke suite (10-15 critical tests) that runs first for immediate feedback",
    option_c: "Run only the tests related to the last changed file",
    option_d: "Convert all E2E tests to unit tests",
    answer: "B",
    explanation: "Parallelization: 200 tests on 4 machines = ~10 min. Cypress Cloud orchestrates parallel runs automatically. Additionally: tag critical tests as @smoke and run that suite first (5 tests, 2 min feedback). Full suite runs in parallel for comprehensive coverage.",
  },
  {
    lesson_title: "Cypress.io Modern Testing",
    question: "What is the Cypress command log used for during debugging?",
    option_a: "The command log only records test failures",
    option_b: "The command log shows every Cypress command executed with its before/after DOM snapshots — you can hover over any command to time-travel and see the app state at that exact moment during the test run",
    option_c: "The command log generates a JUnit XML report for CI",
    option_d: "The command log is only visible in headed mode",
    answer: "B",
    explanation: "Cypress time-travel debugging: the command log records each step. Click on a cy.click() entry in the log and the app state at that moment is shown in the browser snapshot. This makes debugging failures dramatically faster than reading stack traces.",
  },
  {
    lesson_title: "Cypress.io Modern Testing",
    question: "What are Cypress custom commands and when should you create one?",
    option_a: "Custom commands replace all built-in Cypress commands",
    option_b: "Custom commands are reusable sequences defined in commands.js — create one when you repeat 3+ lines of Cypress code across multiple tests (e.g., cy.login(), cy.fillAddressForm())",
    option_c: "Custom commands are only for assertions",
    option_d: "Custom commands must be defined in each test file",
    answer: "B",
    explanation: "`Cypress.Commands.add('login', (email, password) => { cy.request(...) })` then `cy.login('user@test.com', 'pass')` in tests. Extract repeated setup into custom commands to keep tests readable and reduce duplication. Stored in cypress/support/commands.js.",
  },
  {
    lesson_title: "Cypress.io Modern Testing",
    question: "A Cypress test is asserting that a table has 5 rows. The test passes locally but fails with 3 rows in CI. What do you investigate?",
    option_a: "The assertion is wrong — use a different matcher",
    option_b: "The table data is loaded via API — in CI the API call may return different data, or a previous test may have deleted records. Investigate test data isolation and consider stubbing the API response",
    option_c: "The table component renders differently in Chrome vs Firefox",
    option_d: "Cypress cannot count table rows — use a different assertion method",
    answer: "B",
    explanation: "Inconsistent row counts = data problem. Either: (1) tests run in different order in CI and a previous test deleted records, (2) the API returns different paginated data in CI's environment. Fix: stub the response with cy.intercept() for deterministic data, or seed test data before the test.",
  },
  {
    lesson_title: "Cypress.io Modern Testing",
    question: "What is the cypress.config.js file used for?",
    option_a: "It is used to define test assertions",
    option_b: "It configures Cypress globally — baseUrl, viewportWidth, defaultCommandTimeout, environment variables, and test file patterns — so tests don't hardcode these values",
    option_c: "It stores test data for fixtures",
    option_d: "It defines the order tests run in",
    answer: "B",
    explanation: "`baseUrl: 'http://localhost:3000'` lets tests use `cy.visit('/')` instead of full URLs. `defaultCommandTimeout: 10000` extends timeouts for slow environments. `env: { apiUrl: '...' }` injects environment-specific config. Centralizes all Cypress settings.",
  },
  {
    lesson_title: "Cypress.io Modern Testing",
    question: "The product team asks why Cypress E2E tests still miss some bugs that reach production. How do you explain this?",
    option_a: "Cypress is not suitable for production-quality testing",
    option_b: "E2E tests only cover the happy paths and major flows they were written for — production bugs often occur in edge cases, unusual user flows, specific data conditions, or integrations not covered by existing test scenarios",
    option_c: "Cypress tests should be written to cover 100% of the application",
    option_d: "The Cypress version is outdated — upgrade to fix this",
    answer: "B",
    explanation: "No test suite provides complete coverage. E2E tests cover defined flows — bugs in untested flows (unusual data, rare user paths, third-party integrations) escape. Complement E2E with unit tests (logic), API tests (contract), and exploratory testing (discovery). Each layer catches different bugs.",
  },
];
