import type { QuizRow } from "../../quiz-types";

export const playwrightForE2eTestingQuizzes: QuizRow[] = [
  {
    lesson_title: "Playwright for E2E Testing",
    question: "What is Playwright's auto-waiting mechanism and what does it wait for?",
    option_a: "Playwright waits 3 seconds before every action by default",
    option_b: "Playwright automatically waits for elements to be visible, enabled, and stable before performing actions — no explicit waits needed for most interactions",
    option_c: "Playwright only waits for network requests to complete",
    option_d: "Auto-waiting must be configured in playwright.config.ts",
    answer: "B",
    explanation: "Before click(), fill(), etc., Playwright checks: element is attached to DOM, visible, not animating, enabled, and not covered. This eliminates most flakiness without manual waits. If these conditions aren't met within the timeout, the action fails with a clear error.",
  },
  {
    lesson_title: "Playwright for E2E Testing",
    question: "How does Playwright support cross-browser testing?",
    option_a: "Playwright only supports Chrome",
    option_b: "Playwright ships with bundled browser engines (Chromium, Firefox, WebKit) and tests can run across all three by configuring projects in playwright.config.ts — no separate drivers needed",
    option_c: "Cross-browser testing requires Selenium Grid alongside Playwright",
    option_d: "Playwright uses the browser installed on the OS — it cannot bundle browsers",
    answer: "B",
    explanation: "Playwright bundles Chromium, Firefox, and WebKit. In playwright.config.ts: `projects: [{ name: 'chromium', use: devices['Desktop Chrome'] }, { name: 'firefox', ... }]`. Each test runs across all configured browsers. No downloading of separate WebDrivers.",
  },
  {
    lesson_title: "Playwright for E2E Testing",
    question: "What are Playwright fixtures and how do they improve test isolation?",
    option_a: "Fixtures are screenshot comparison files used for visual testing",
    option_b: "Fixtures are functions that provide test setup (pages, authenticated contexts, database state) and automatic teardown — each test gets a fresh, isolated instance without shared state",
    option_c: "Fixtures are JSON data files stored in the tests folder",
    option_d: "Fixtures are only for providing test data, not for browser setup",
    answer: "B",
    explanation: "Playwright fixtures: `test.extend({ loggedInPage: async ({ page }, use) => { await loginViaAPI(page); await use(page); await cleanup(); } })`. Each test calling `loggedInPage` gets a fresh, authenticated page. Teardown runs automatically. This is Playwright's dependency injection for tests.",
  },
  {
    lesson_title: "Playwright for E2E Testing",
    question: "Your Playwright test fails with 'Target page, context, or browser has been closed.' What does this mean?",
    option_a: "The test timed out because Playwright took too long",
    option_b: "The browser context or page was closed while the test was still running — often caused by a fixture that tears down too early, a context.close() call in the wrong place, or the browser crashing",
    option_c: "Playwright does not support the tested page's technology stack",
    option_d: "The test tried to open a URL that redirected to a closed tab",
    answer: "B",
    explanation: "'Target closed' means the object you're interacting with no longer exists. Common causes: (1) context/page closed in a beforeEach or fixture before assertions complete, (2) test framework re-using a context across tests that should be isolated, (3) the application code closed the window. Check fixture lifecycle order.",
  },
  {
    lesson_title: "Playwright for E2E Testing",
    question: "What is page.waitForResponse() and when should you use it?",
    option_a: "It pauses the test for a set number of milliseconds",
    option_b: "It waits for a matching network response before continuing — use it after triggering an action that makes an API call to ensure the response was received before asserting the resulting UI change",
    option_c: "It verifies that a response has a specific HTTP status code",
    option_d: "It is used to mock API responses",
    answer: "B",
    explanation: "`await page.waitForResponse(resp => resp.url().includes('/api/orders') && resp.status() === 200)` waits for the orders API call to complete. Use this when: clicking 'Submit' triggers an API call and you need the UI to update before asserting — more reliable than arbitrary timeouts.",
  },
  {
    lesson_title: "Playwright for E2E Testing",
    question: "How do you test multiple user roles (admin and regular user) in Playwright without repeating login flows?",
    option_a: "Create separate test files for each role",
    option_b: "Use storageState to save authenticated browser states per role — set them up once and reuse them across tests with `use: { storageState: 'admin-state.json' }` in playwright.config.ts",
    option_c: "Pass the role as a test parameter and log in via UI each time",
    option_d: "Use parallel execution with different user accounts in each worker",
    answer: "B",
    explanation: "storageState captures cookies and localStorage after login. `await page.context().storageState({ path: 'admin-state.json' })` saves admin session. Tests then start authenticated without any login steps: `test.use({ storageState: 'admin-state.json' })`. Reduces setup time dramatically.",
  },
  {
    lesson_title: "Playwright for E2E Testing",
    question: "What does expect(page).toHaveURL() do and why is it preferred over checking URL manually?",
    option_a: "It navigates the page to the specified URL",
    option_b: "It is a web-first assertion that waits and retries until the page URL matches — it handles navigation that happens asynchronously after a click, unlike a synchronous manual check",
    option_c: "It verifies the URL is reachable via HTTP GET",
    option_d: "It is identical to page.url() === expectedUrl",
    answer: "B",
    explanation: "Web-first assertions in Playwright (toHaveURL, toHaveText, toBeVisible) retry automatically: `await expect(page).toHaveURL('/dashboard')` waits up to the configured timeout for the URL to match. A manual check `page.url() === '/dashboard'` would fail if navigation hasn't completed yet.",
  },
  {
    lesson_title: "Playwright for E2E Testing",
    question: "You need to test a payment flow that calls a real payment gateway. How do you handle this in automated tests?",
    option_a: "Always use the real payment gateway — tests must reflect production",
    option_b: "Use page.route() to intercept and stub the payment gateway request — return a mocked success or failure response so tests are fast, reliable, and don't charge real money",
    option_c: "Skip payment flow testing entirely",
    option_d: "Create a real test account and use a test credit card from the provider",
    answer: "B",
    explanation: "page.route('/api/payment*', route => route.fulfill({ status: 200, body: JSON.stringify({ success: true }) })) stubs the payment API. This tests your app's handling of payment outcomes without real money, network latency, or third-party rate limits. Test real integration in a dedicated integration test with sandbox credentials.",
  },
  {
    lesson_title: "Playwright for E2E Testing",
    question: "What is Playwright's test.describe() and how does it help organize tests?",
    option_a: "test.describe() is used to mark tests as skipped",
    option_b: "test.describe() groups related tests together and allows shared beforeEach/afterEach setup specific to that group — improving readability and allowing focused runs with --grep",
    option_c: "test.describe() is required for every test file",
    option_d: "test.describe() runs tests in parallel automatically",
    answer: "B",
    explanation: "`test.describe('Checkout flow', () => { test.beforeEach(...); test('add to cart', ...); test('apply coupon', ...) })` groups related tests. The beforeEach runs only for tests in this describe. Run just this group with `npx playwright test --grep 'Checkout flow'`.",
  },
  {
    lesson_title: "Playwright for E2E Testing",
    question: "A Playwright test passes on Chromium but fails on WebKit (Safari). What should you investigate?",
    option_a: "WebKit support is experimental — ignore WebKit failures",
    option_b: "Cross-browser differences: CSS rendering, JavaScript API availability, animation timing, or form validation behavior that differs between engines — investigate the specific assertion that fails and check for known WebKit quirks",
    option_c: "The test locator is wrong and needs to be rewritten for Safari",
    option_d: "WebKit tests always need different locator strategies",
    answer: "B",
    explanation: "WebKit-specific failures are real bugs — Safari users will encounter them. Investigate: (1) CSS that renders differently, (2) JS APIs not supported in WebKit (`requestAnimationFrame` timing), (3) form input behavior differences. These are legitimate cross-browser bugs worth fixing.",
  },
  {
    lesson_title: "Playwright for E2E Testing",
    question: "What is Playwright's reporter and what options are available for CI integration?",
    option_a: "Playwright only outputs results to the terminal",
    option_b: "Playwright supports multiple reporters: list (terminal), HTML (interactive report), JUnit (CI integration), GitHub (PR annotations) — configured in playwright.config.ts and combined for different audiences",
    option_c: "Reporters must be written from scratch for each project",
    option_d: "Playwright uses the same reporter as Jest",
    answer: "B",
    explanation: "`reporter: [['html'], ['junit', { outputFile: 'results.xml' }]]` generates an interactive HTML report for developers AND a JUnit XML for CI systems. GitHub reporter adds ❌/✅ annotations directly on PR diffs. HTML reporter includes video/screenshot of failures.",
  },
  {
    lesson_title: "Playwright for E2E Testing",
    question: "Your team wants to add visual regression testing. How does Playwright support this?",
    option_a: "Playwright cannot do visual testing — use a dedicated tool",
    option_b: "Use expect(page).toHaveScreenshot() to capture and compare pixel-by-pixel screenshots — Playwright stores baseline images and flags diffs above a configurable threshold",
    option_c: "Visual testing only works in Chromium, not Firefox or WebKit",
    option_d: "Visual regression requires the Playwright Visual plugin installed separately",
    answer: "B",
    explanation: "`await expect(page.locator('.chart')).toHaveScreenshot('chart.png')` compares against stored baseline. First run creates the baseline; subsequent runs compare. `maxDiffPixels: 50` tolerates minor rendering differences. Update baselines with `--update-snapshots`. Great for catching unintended UI regressions.",
  },
  {
    lesson_title: "Playwright for E2E Testing",
    question: "How do you configure Playwright to run tests in parallel and what are the key settings?",
    option_a: "Playwright does not support parallel test execution",
    option_b: "Set workers in playwright.config.ts — each worker runs in an isolated browser context. fullyParallel: true runs each test in its own worker; by default, test files run in parallel but tests within a file are sequential",
    option_c: "Parallel execution requires Playwright Grid, a separate product",
    option_d: "Tests must be manually split into separate processes to run in parallel",
    answer: "B",
    explanation: "`workers: process.env.CI ? 4 : 2` and `fullyParallel: true` in config. Each worker gets an isolated context — no shared browser state. Important: tests must be truly independent (no shared data, no sequential dependencies). Use `test.serial` for tests that must run in order.",
  },
  {
    lesson_title: "Playwright for E2E Testing",
    question: "After 3 months, the team notices Playwright tests are catching fewer bugs than when they started. What's likely happening?",
    option_a: "Playwright became less effective over time",
    option_b: "Tests are covering the same happy paths repeatedly but new features were not automated — the test suite hasn't grown with the application, creating coverage gaps for new functionality",
    option_c: "The application quality improved, so fewer bugs exist",
    option_d: "The team should switch to a different E2E framework",
    answer: "B",
    explanation: "Coverage drift: the test suite was written for an older version of the app. New features were added without corresponding tests. Fix: make automation a DoD requirement for new features, track coverage per feature, and regularly audit what new functionality has no E2E tests.",
  },
  {
    lesson_title: "Playwright for E2E Testing",
    question: "What is the Playwright codegen tool and what is its appropriate use?",
    option_a: "Codegen generates production-ready tests that should be committed directly",
    option_b: "Codegen records browser interactions and generates Playwright code as a starting point — use it to get initial locators and action sequences quickly, then refactor with page objects and proper assertions",
    option_c: "Codegen is a visual editor for designing test flows without coding",
    option_d: "Codegen only works with the Playwright VS Code extension",
    answer: "B",
    explanation: "`npx playwright codegen https://example.com` opens a browser and generates code as you interact. It's a productivity tool for getting initial code — not a final result. Generated code needs: page objects, meaningful assertions, data-testid locators instead of positional ones, and proper test structure.",
  },
];
