import type { QuizRow } from "../../quiz-types";

export const apiAutomationAndContractTestingQuizzes: QuizRow[] = [
  {
    lesson_title: "API Automation & Contract Testing",
    question: "What is contract testing and what problem does it solve?",
    option_a: "A legal process for signing off on API specifications",
    option_b: "Contract testing verifies that a consumer's expected API format matches what the provider actually delivers — catching integration breakages before services are deployed together",
    option_c: "Testing API authentication and authorization",
    option_d: "Performance testing of API contracts under load",
    answer: "B",
    explanation: "Without contract tests: Team A's API changes break Team B's consumer, discovered only in integration/E2E. With Pact/contract tests: provider verifies its responses match all consumers' expectations independently. Integration breakages are caught in CI before deployment.",
  },
  {
    lesson_title: "API Automation & Contract Testing",
    question: "What is the difference between schema validation and contract testing?",
    option_a: "They are the same — both verify API response format",
    option_b: "Schema validation verifies a single response matches a structure (e.g., JSON Schema); contract testing verifies both consumer expectations and provider output match across a deployment — it's bidirectional",
    option_c: "Contract testing is only for REST APIs; schema validation works for all formats",
    option_d: "Schema validation is more thorough than contract testing",
    answer: "B",
    explanation: "Schema validation: does this response have the right fields? Contract testing (Pact): does the provider's response match exactly what each consumer expects to receive? Contract testing includes the consumer perspective, making it more powerful for microservices where many consumers exist.",
  },
  {
    lesson_title: "API Automation & Contract Testing",
    question: "What test cases should you write for a DELETE /users/{id} endpoint?",
    option_a: "Only verify it returns 200",
    option_b: "Test: 200/204 on valid deletion, 404 for non-existent ID, verify the resource is truly gone (follow-up GET returns 404), 401/403 for unauthorized callers, and behavior when deleting already-deleted resource",
    option_c: "Test only that the HTTP method is accepted",
    option_d: "Only test that the database record count decreases",
    answer: "B",
    explanation: "DELETE coverage: (1) happy path — correct status and resource gone, (2) not found — 404, (3) verify deletion — follow-up GET returns 404, (4) unauthorized — 401/403, (5) double-delete — idempotent (404) or error. A DELETE that returns 200 but doesn't delete anything is a common bug.",
  },
  {
    lesson_title: "API Automation & Contract Testing",
    question: "What is API idempotency and why is it important to test?",
    option_a: "Idempotency means an API responds within a fixed time limit",
    option_b: "An idempotent operation produces the same result when called multiple times — GET, PUT, DELETE should be idempotent; testing this prevents duplicate charges, double-inserts, and inconsistent state from network retries",
    option_c: "Idempotency only applies to GET requests",
    option_d: "Idempotency means the API never changes data",
    answer: "B",
    explanation: "Network failures cause clients to retry. A non-idempotent POST /checkout that creates an order on each call would create duplicate orders if retried. Test: call PUT /orders/1 twice with the same data — the second call should return the same result, not error or create duplicates.",
  },
  {
    lesson_title: "API Automation & Contract Testing",
    question: "An API returns HTTP 200 but the response body contains `{ 'error': 'User not found' }`. Why is this a problem and how do you test for it?",
    option_a: "This is acceptable — the HTTP status code is the only thing that matters",
    option_b: "A 200 with an error body is misleading — clients relying only on the status code will mishandle the error. Test for this by asserting both the HTTP status AND the response body structure/content",
    option_c: "This only occurs in poorly designed APIs and should not be tested",
    option_d: "HTTP status codes and response bodies are independent — test them separately",
    answer: "B",
    explanation: "APIs that return 200 on error break HTTP semantics and cause consumer bugs (automated clients treat 200 as success). Always assert both: `expect(response.status).toBe(200)` AND `expect(response.body.error).toBeUndefined()`. This catches the common anti-pattern of 'HTTP 200 but business failure.'",
  },
  {
    lesson_title: "API Automation & Contract Testing",
    question: "What is Pact in the context of contract testing?",
    option_a: "A test runner for API integration tests",
    option_b: "A consumer-driven contract testing tool — the consumer defines its expectations (the 'pact'), the provider verifies it can fulfill them — enabling independent deployment of microservices",
    option_c: "A tool for performance testing REST APIs",
    option_d: "A security scanning tool for API endpoints",
    answer: "B",
    explanation: "Pact workflow: Consumer writes a test that defines what it expects from the API → Pact saves this as a contract file → Provider verifies it can fulfill the contract in its own test suite. Both sides verify independently. No need to deploy both services together to catch contract breaks.",
  },
  {
    lesson_title: "API Automation & Contract Testing",
    question: "How do you test API rate limiting behavior?",
    option_a: "Rate limiting is a network configuration — it cannot be tested at the API level",
    option_b: "Send requests exceeding the rate limit and verify: the API returns 429 Too Many Requests, the Retry-After header is present, and that requests are accepted again after the window resets",
    option_c: "Only verify that the API returns 429 — do not test the reset behavior",
    option_d: "Rate limiting tests should only be run in production with real traffic",
    answer: "B",
    explanation: "Rate limiting test: (1) Send N+1 requests (where N is the limit), assert the last returns 429. (2) Check for Retry-After or X-RateLimit-Reset headers. (3) Wait for window reset and confirm the API accepts requests again. Missing rate limits enable abuse; missing 429 responses break client retry logic.",
  },
  {
    lesson_title: "API Automation & Contract Testing",
    question: "What is the difference between mocking and stubbing in API test automation?",
    option_a: "They are identical concepts",
    option_b: "A stub returns predefined responses to specific requests (behavior replacement); a mock additionally verifies that it was called with expected parameters — mocks have built-in assertions, stubs do not",
    option_c: "Mocking is for unit tests; stubbing is only for integration tests",
    option_d: "Stubs are faster than mocks at runtime",
    answer: "B",
    explanation: "Stub: 'when called with these args, return this response' — no verification. Mock: 'I expect to be called exactly twice with these args' — fails if not called correctly. In API testing: stub the payment gateway to return a response; mock it to also verify the correct amount was sent.",
  },
  {
    lesson_title: "API Automation & Contract Testing",
    question: "You're automating tests for a POST /orders endpoint. What validations should your automated tests cover beyond the happy path?",
    option_a: "Only the successful order creation case",
    option_b: "Missing required fields (400), invalid field types (400), duplicate order prevention, authentication (401), authorization (403), oversold inventory edge case, and verifying the response body contains the created order ID",
    option_c: "Only test error cases — the happy path is tested manually",
    option_d: "Test only the HTTP status code, not the response body",
    answer: "B",
    explanation: "POST endpoint test coverage: (1) happy path — 201 with correct body, (2) validation — missing/invalid fields return 400 with clear error messages, (3) auth — unauthenticated returns 401, (4) business rules — oversold inventory, duplicate orders, (5) response body includes ID for follow-up operations.",
  },
  {
    lesson_title: "API Automation & Contract Testing",
    question: "Your automated API suite runs fine individually but fails when run together. What is the most likely cause?",
    option_a: "API automation does not support parallel execution",
    option_b: "Tests are sharing state — one test creates data that another test depends on, or a test deletes data another test expects — making execution order matter",
    option_c: "The test framework has a memory leak",
    option_d: "Running multiple tests simultaneously overloads the server",
    answer: "B",
    explanation: "Order-dependent tests are a design flaw. Each test should: (1) create its own test data, (2) clean up after itself. If test B relies on data created by test A, test B will fail when run alone or in a different order. Fix: self-contained tests with setup/teardown per test.",
  },
  {
    lesson_title: "API Automation & Contract Testing",
    question: "How do you handle authentication in API automation tests without hardcoding credentials?",
    option_a: "Hardcode test credentials — they're not production credentials",
    option_b: "Use environment variables for credentials, programmatically obtain a token in the test setup via a login API call, and pass it in the Authorization header — never commit secrets to source control",
    option_c: "Use the same credentials for all test environments",
    option_d: "Skip authentication testing — it is the developer's responsibility",
    answer: "B",
    explanation: "Pattern: `const token = await getAuthToken(process.env.TEST_USER, process.env.TEST_PASS)` in beforeAll. Pass `Authorization: Bearer ${token}` on requests. Credentials come from environment variables or a secrets manager — never hardcoded in test files. Rotate tokens between test suites.",
  },
  {
    lesson_title: "API Automation & Contract Testing",
    question: "What is an API regression test suite and how should it be structured?",
    option_a: "A test that runs every endpoint once to check they respond",
    option_b: "A versioned collection of tests covering all known API behaviors — organized by endpoint and scenario, run on every deployment to detect any change that breaks expected behavior",
    option_c: "A performance test that checks API response times haven't regressed",
    option_d: "Only tests for previously reported bugs",
    answer: "B",
    explanation: "API regression suite: organized by resource (users, orders, products), each resource has tests for all CRUD operations and edge cases, run in CI on every PR. When a new bug is found, a test is added immediately so it never regresses. The suite grows continuously.",
  },
  {
    lesson_title: "API Automation & Contract Testing",
    question: "A developer says the API is backward compatible — they only added a new optional field. Why might this still break consumers?",
    option_a: "Adding optional fields never breaks anything",
    option_b: "Consumers using strict schema validation or exact-match assertions will fail if they don't expect the new field — 'backward compatible' at the HTTP level is not the same as backward compatible for all consumers",
    option_c: "The developer must version the API even for optional fields",
    option_d: "Optional fields are ignored by all clients automatically",
    answer: "B",
    explanation: "Adding a field is 'non-breaking' in HTTP terms but can break: (1) consumers with strict schema validation that rejects unknown fields, (2) consumers that deserialize to fixed structs. Contract tests (Pact) catch this — the consumer's contract doesn't include the new field, but if the provider adds it, the contract still passes.",
  },
  {
    lesson_title: "API Automation & Contract Testing",
    question: "What should be included in an automated API test assertion beyond checking the HTTP status code?",
    option_a: "The status code is sufficient for most API tests",
    option_b: "Assert: correct status code, response body structure (required fields present, correct types), response body values (correct data returned), response headers (Content-Type, Cache-Control), and response time (within SLA)",
    option_c: "Only assert fields that are likely to change",
    option_d: "Only assert the entire response body as an exact match",
    answer: "B",
    explanation: "A 200 status doesn't mean the response is correct. Assert: `expect(response.body.id).toBeDefined()`, `expect(response.body.email).toBe(testUser.email)`, `expect(response.headers['content-type']).toContain('application/json')`. Complete assertions catch bugs that status-code-only checks miss.",
  },
  {
    lesson_title: "API Automation & Contract Testing",
    question: "How do you test an API that has external dependencies (email service, payment gateway) in automation?",
    option_a: "Always use real external services in automated tests",
    option_b: "Use test doubles (stubs/mocks) for external dependencies — either by injecting a fake service, using a sandbox mode provided by the vendor, or intercepting HTTP calls at the HTTP client level",
    option_c: "Skip tests that require external dependencies",
    option_d: "Use a VPN to connect to production external services from the test environment",
    answer: "B",
    explanation: "External services make tests slow, flaky, and costly (real charges, rate limits). Strategy: (1) Use vendor sandbox accounts when available, (2) Stub at the HTTP level using WireMock or nock, (3) Dependency injection — pass in a fake email service implementation. Keep one end-to-end integration test using real services, but most cases use doubles.",
  },
];
