import type { QuizRow } from "../../quiz-types";

export const apiAutomationAndContractTestingQuizzes: QuizRow[] = [
  {
    lesson_title: "API Automation & Contract Testing",
    question: "Why are API tests more cost-effective than UI tests?",
    option_a: "API tests are always free",
    option_b: "API tests run faster, don't break when UI changes, and cover more scenarios in less time",
    option_c: "UI tests are more accurate",
    option_d: "There is no difference",
    answer: "B",
    explanation: "API tests run in milliseconds to seconds while UI tests take 15-60 seconds. API tests are stable, directly verify business logic, and don't break from UI changes.",
  },
  {
    lesson_title: "API Automation & Contract Testing",
    question: "What is contract testing in API automation?",
    option_a: "A legal agreement for API usage",
    option_b: "Testing that the API request/response structure matches the agreed contract between services",
    option_c: "Testing the user interface",
    option_d: "A type of security test",
    answer: "B",
    explanation: "Contract testing ensures that APIs meet their documented contract (request/response schema, status codes). It prevents services from silently breaking when they evolve independently.",
  },
  {
    lesson_title: "API Automation & Contract Testing",
    question: "What is the test pyramid and why does it place API tests in the middle?",
    option_a: "It is an organizational chart",
    option_b: "It shows testing layers: many unit tests at base, fewer API tests in middle, few UI tests at top",
    option_c: "It replaces testing strategy",
    option_d: "It is only for backend developers",
    answer: "B",
    explanation: "The pyramid shows the cost/benefit balance: unit tests are fast and cheap, API tests provide good coverage efficiently, UI tests are slow but necessary for end-to-end validation.",
  },
  {
    lesson_title: "API Automation & Contract Testing",
    question: "What should you test in an API response?",
    option_a: "Only the HTTP status code",
    option_b: "Status code, response schema, key values, error messages, and headers",
    option_c: "Only the response body text",
    option_d: "Nothing, APIs are always correct",
    answer: "B",
    explanation: "Comprehensive API testing validates status codes (200, 404, 500), response structure (JSON schema), specific data values, error messages, and headers.",
  },
  {
    lesson_title: "API Automation & Contract Testing",
    question: "What is the advantage of storing API tests in a centralized repository?",
    option_a: "Tests run faster",
    option_b: "Tests can be shared across teams and integrated into CI/CD pipelines for continuous validation",
    option_c: "Tests are easier to read",
    option_d: "Tests require less maintenance",
    answer: "B",
    explanation: "Centralized API test repositories enable code reuse, team collaboration, integration with CI/CD for continuous validation, and version control of test changes.",
  },
];
