import type { QuizRow } from "../../quiz-types";

export const ciCdPipelineIntegrationQuizzes: QuizRow[] = [
  {
    lesson_title: "CI/CD Pipeline Integration",
    question: "What is the difference between Continuous Integration (CI) and Continuous Delivery (CD)?",
    option_a: "CI and CD are the same concept",
    option_b: "CI automatically builds and tests code on every commit; CD extends this to automatically prepare or deploy releases — CI ensures the code is always releasable, CD ensures it is actually released",
    option_c: "CI is for testing; CD is only for database migrations",
    option_d: "CD requires manual approval before any code runs; CI does not",
    answer: "B",
    explanation: "CI: every commit triggers build + automated tests — catching integration issues immediately. CD (Delivery): CI pipeline extends to staging/production deployment. CD (Deployment): fully automated releases with no manual approval. QA's job in CI/CD: design tests that run at the right stage.",
  },
  {
    lesson_title: "CI/CD Pipeline Integration",
    question: "What is a quality gate in a CI/CD pipeline?",
    option_a: "A manual review step where a senior QA approves each build",
    option_b: "An automated threshold that must pass before a pipeline stage proceeds — examples: test pass rate >95%, code coverage >80%, zero critical security vulnerabilities — failing the gate blocks deployment",
    option_c: "A UI checkpoint that captures screenshots for visual review",
    option_d: "A performance benchmark that runs once per week",
    answer: "B",
    explanation: "Quality gates enforce non-negotiable quality standards automatically. SonarQube gate: 0 critical bugs, >80% coverage. Test gate: 95% pass rate. Security gate: no OWASP critical findings. A failing gate stops the pipeline and notifies the team — no manual oversight needed.",
  },
  {
    lesson_title: "CI/CD Pipeline Integration",
    question: "The CI pipeline runs 400 tests and takes 45 minutes. The team wants feedback in under 10 minutes. What is your strategy?",
    option_a: "Delete tests until the pipeline runs in 10 minutes",
    option_b: "Stage the pipeline: fast smoke tests first (2 min), then parallelize the full suite across multiple agents. Run smoke on every commit, full suite on PR merge — developers get early feedback from smoke and thorough coverage from parallel full runs",
    option_c: "Run only tests related to changed files",
    option_d: "Run the full suite but on a faster server",
    answer: "B",
    explanation: "Tiered pipeline: Stage 1 (every commit): 10-15 critical smoke tests, ~2 min. Stage 2 (PR): full suite on 5 parallel agents, ~10 min. Stage 3 (pre-deploy): performance + security scans. Developers get 2-min feedback on their commit and full confidence before merge.",
  },
  {
    lesson_title: "CI/CD Pipeline Integration",
    question: "What are build artifacts and why are they important for QA in a CI/CD pipeline?",
    option_a: "Build artifacts are error logs generated when a build fails",
    option_b: "Build artifacts are the outputs of a build step (compiled app, Docker image, test reports) that are passed to later stages — QA tests the exact same artifact that will be deployed, not a re-built version",
    option_c: "Build artifacts are source code backups stored in the CI server",
    option_d: "Build artifacts are only relevant to the deployment stage, not QA",
    answer: "B",
    explanation: "Artifact promotion: Build once, test the same artifact at every stage. CI builds a Docker image → QA tests it → same image promoted to staging → same image deployed to production. If QA tests a re-built image, the tested code is not the deployed code — a critical traceability gap.",
  },
  {
    lesson_title: "CI/CD Pipeline Integration",
    question: "A critical bug reached production despite all CI tests passing. What pipeline gap does this reveal?",
    option_a: "The CI pipeline is not needed — manual testing would have caught it",
    option_b: "The test suite has a coverage gap — the bug is in a scenario not covered by any automated test. CI only catches what it covers; production reveals what was missed",
    option_c: "The CI server had a configuration error that allowed bad code through",
    option_d: "CD deployed too fast — a manual approval step would have caught it",
    answer: "B",
    explanation: "CI is only as good as its tests. When a bug escapes: (1) Write a test for this exact scenario now, (2) Analyze what class of test was missing (edge case? integration? regression?), (3) Update testing checklists to prevent similar gaps. Use production bugs as a retrospective signal for coverage improvement.",
  },
  {
    lesson_title: "CI/CD Pipeline Integration",
    question: "What is a canary deployment and how does it reduce risk in CD?",
    option_a: "A canary deployment runs tests in a special test environment called 'canary'",
    option_b: "A canary deployment sends a small percentage of real traffic (e.g., 5%) to the new version while 95% stays on the old version — monitors error rates and metrics before rolling out to 100%",
    option_c: "A canary is an automated regression test suite run post-deployment",
    option_d: "A canary deployment deploys to one geographic region only",
    answer: "B",
    explanation: "Canary: deploy new version to 5% of servers → monitor error rates, latency, business metrics → if metrics are healthy, gradually increase to 25%, 50%, 100%. If metrics degrade, roll back the 5% instantly. Real-world traffic catches bugs that tests miss, with limited blast radius.",
  },
  {
    lesson_title: "CI/CD Pipeline Integration",
    question: "What is 'shift-right testing' and how does it differ from shift-left?",
    option_a: "Shift-right means moving all testing to after deployment to save development time",
    option_b: "Shift-right tests in production using techniques like canary deployments, feature flags, A/B testing, and monitoring — complementing shift-left (early testing) to catch issues that only appear under real user conditions",
    option_c: "Shift-right is a rejected testing philosophy — all testing should happen pre-deployment",
    option_d: "Shift-right means running tests on the right side of the Selenium Grid",
    answer: "B",
    explanation: "Shift-left (catch early): requirements review, unit tests, CI. Shift-right (real-world validation): production monitoring, synthetic transactions, chaos engineering, feature flags. Both are necessary — staging never fully replicates production traffic and data patterns.",
  },
  {
    lesson_title: "CI/CD Pipeline Integration",
    question: "What are feature flags and how do they improve QA's ability to safely release new features?",
    option_a: "Feature flags are special test-only environment variables",
    option_b: "Feature flags are toggles that enable/disable features at runtime without redeployment — QA can test the flagged feature in production with internal users before releasing to all customers",
    option_c: "Feature flags replace A/B testing and are only used for UI experiments",
    option_d: "Feature flags allow bypassing CI pipelines for emergency releases",
    answer: "B",
    explanation: "Feature flags decouple deployment from release. Deploy code with flag OFF (dark launch) → QA tests in production with flag ON for internal users → gradually enable for 5%, 25%, 100%. If issues arise, turn the flag OFF instantly — no rollback deployment needed. Enables true continuous deployment.",
  },
  {
    lesson_title: "CI/CD Pipeline Integration",
    question: "Your team deploys 10 times per day. How do you structure QA without becoming the bottleneck?",
    option_a: "Have QA manually verify each deployment — 10 reviews per day is manageable",
    option_b: "Automate the regression suite to run in CI on every deployment, reserve manual QA for new feature exploration and edge cases, and use monitoring/alerting to detect issues in production that tests miss",
    option_c: "Slow down deployments to once per day to give QA time to test",
    option_d: "Remove QA from the deployment pipeline — move faster by relying on developers to test",
    answer: "B",
    explanation: "10 deploys/day = automation mandatory. Automated regression catches regressions without manual effort. QA's value shifts from 'gatekeeper' to 'quality engineer': writing automation, improving coverage, exploratory testing of new features, and analyzing production metrics. QA enables speed, not blocks it.",
  },
  {
    lesson_title: "CI/CD Pipeline Integration",
    question: "What is a rollback strategy and when should it be triggered?",
    option_a: "A rollback deploys the previous Docker image if a developer requests it",
    option_b: "A rollback automatically reverts to the previous stable release when post-deployment metrics breach thresholds — error rate spike, latency increase, business metric drop — triggered by monitoring, not manual observation",
    option_c: "Rollbacks are only used for database migrations",
    option_d: "A rollback is a full re-deployment from source code that takes several hours",
    answer: "B",
    explanation: "Automated rollback: define health thresholds (error rate > 1%, p99 latency > 500ms, zero purchases in 5 min). If breached post-deploy: auto-rollback in seconds. QA's role: define and validate these thresholds. Without automated rollback, a bad deploy can impact users for hours while oncall responds.",
  },
  {
    lesson_title: "CI/CD Pipeline Integration",
    question: "How do you handle database migrations in a CI/CD pipeline safely?",
    option_a: "Run all migrations before any testing — migrations are safe by definition",
    option_b: "Migrations must be backward compatible (additive only) — new columns added with defaults, old columns not dropped until all code stops using them — enabling rollback without data loss",
    option_c: "Database migrations should only be run manually by a DBA",
    option_d: "Run migrations in production after deployment to verify they work",
    answer: "B",
    explanation: "Safe migration pattern: (1) Add new nullable column, (2) Deploy code that writes to both old and new, (3) Backfill data, (4) Deploy code using only new column, (5) Drop old column later. This allows rollback at any step. Dropping a column in the same deployment as the code change that stops using it will break a rollback.",
  },
  {
    lesson_title: "CI/CD Pipeline Integration",
    question: "What is the difference between a smoke test and a regression test suite in CI?",
    option_a: "They are the same — both verify the application works",
    option_b: "Smoke tests are a small set of critical path tests run in minutes to verify the deployment didn't break core functionality; regression tests are comprehensive and verify all known behaviors — run on different CI triggers",
    option_c: "Regression tests run in CI; smoke tests are only run manually",
    option_d: "Smoke tests test the database; regression tests test the UI",
    answer: "B",
    explanation: "Smoke: 5-15 tests, < 5 minutes, run on every commit and deployment — verify app starts, login works, core API responds. Regression: 200+ tests, 10-30 minutes, run on PRs and pre-production — verify all existing features still work. Different triggers, different purposes.",
  },
  {
    lesson_title: "CI/CD Pipeline Integration",
    question: "A developer asks to skip CI tests for a 'trivial one-line fix.' How do you respond?",
    option_a: "Allow it — a one-line fix cannot cause a regression",
    option_b: "Decline: one-line fixes cause regressions regularly. If CI must be bypassed for emergencies, use a hotfix process with post-deployment monitoring and a follow-up test. Never normalize bypassing CI",
    option_c: "Allow it if a senior developer approves",
    option_d: "Skip only the slow tests, not the smoke tests",
    answer: "B",
    explanation: "'Trivial' changes cause critical bugs: changing `>=` to `>` in a condition, a missing null check, a renamed variable used elsewhere. CI exists precisely because humans misjudge impact. Bypassing CI destroys team trust in the pipeline. If CI takes too long, fix the pipeline — don't bypass it.",
  },
  {
    lesson_title: "CI/CD Pipeline Integration",
    question: "What is environment parity and why does it matter for QA?",
    option_a: "Environment parity means all environments have the same number of test cases",
    option_b: "Environment parity means dev, staging, and production use the same OS, runtime versions, configs, and infrastructure — differences between environments are the #1 cause of 'works in staging, fails in production'",
    option_c: "Environment parity means QA and developers share the same workstation",
    option_d: "Environment parity only applies to database configurations",
    answer: "B",
    explanation: "Environment drift: staging runs Node 16, production runs Node 20. Staging has 1GB RAM, production has 16GB. Staging has no CDN. These differences cause tests to pass in staging but fail in production. Use Docker and infrastructure-as-code (Terraform) to enforce parity. If environments differ, tests in staging are not reliable production proxies.",
  },
  {
    lesson_title: "CI/CD Pipeline Integration",
    question: "How should failed CI tests be handled by the team to maintain pipeline reliability?",
    option_a: "Failing tests can be ignored if the feature is urgent",
    option_b: "Failed tests are a stop signal — investigate and fix immediately, or explicitly quarantine with a tracking ticket if the fix is complex. Never merge code that breaks the pipeline, and never ignore failures",
    option_c: "Failed tests should be deleted to keep the pipeline green",
    option_d: "Failed tests indicate the pipeline needs to be restarted, not fixed",
    answer: "B",
    explanation: "A broken pipeline is a fire. Options: (1) Fix now if quick, (2) Revert the commit that broke it, (3) Quarantine the flaky/broken test with an explicit ticket and @skip annotation. Normalized failure-ignoring destroys CI reliability — teams stop trusting the pipeline and real regressions hide in the noise.",
  },
];
