import type { QuizRow } from "../../quiz-types";

export const performanceTestingWithK6Quizzes: QuizRow[] = [
  {
    lesson_title: "Performance Testing with k6",
    question: "What is k6 and how does it differ from JMeter?",
    option_a: "k6 is a GUI-based performance tool; JMeter is code-based",
    option_b: "k6 uses JavaScript for test scripts, runs as a CLI tool with a developer-friendly workflow, and integrates naturally into CI pipelines; JMeter uses XML/GUI config and was built in the Java era",
    option_c: "k6 is only for API testing; JMeter tests databases",
    option_d: "k6 requires browser installation; JMeter does not",
    answer: "B",
    explanation: "k6: write tests in JavaScript, run with `k6 run script.js`, integrates with CI via exit codes, outputs metrics in real time. JMeter: GUI-based, XML test plans, heavier setup. k6 is preferred for developer-centric teams and CI integration.",
  },
  {
    lesson_title: "Performance Testing with k6",
    question: "What is the structure of a basic k6 test script?",
    option_a: "A k6 script must have a setup() and teardown() function",
    option_b: "A k6 script requires a default exported function that is called repeatedly by virtual users — optionally with an options object defining VUs, duration, stages, and thresholds",
    option_c: "k6 scripts are written in YAML, not JavaScript",
    option_d: "A k6 script must import from the 'k6/browser' library to work",
    answer: "B",
    explanation: "`export const options = { vus: 10, duration: '30s' }; export default function() { http.get('http://test.k6.io'); }` — the default function is the virtual user scenario. k6 runs it repeatedly across all VUs for the duration. `options` configures the load profile.",
  },
  {
    lesson_title: "Performance Testing with k6",
    question: "What is the difference between k6 check() and a threshold?",
    option_a: "They are identical — both fail the test when conditions are not met",
    option_b: "check() validates individual request-level conditions (status 200, response time < 500ms) but does NOT fail the test; thresholds define pass/fail criteria for the entire test run — failing a threshold exits k6 with a non-zero code",
    option_c: "check() fails the test immediately; thresholds are informational only",
    option_d: "Thresholds are only for response time; check() handles other validations",
    answer: "B",
    explanation: "check() is a metric tracker — it counts pass/fail but the test continues regardless. `thresholds: { 'http_req_duration': ['p95 < 500'] }` — if p95 exceeds 500ms, k6 exits with code 1, failing the CI pipeline. Combine both: check() for visibility, thresholds for pipeline pass/fail.",
  },
  {
    lesson_title: "Performance Testing with k6",
    question: "What is the purpose of sleep() in a k6 script?",
    option_a: "sleep() pauses the entire test for all virtual users",
    option_b: "sleep() simulates think time between user actions — without it, virtual users send requests as fast as possible, creating an unrealistically high request rate that doesn't match real user behavior",
    option_c: "sleep() is used to wait for asynchronous responses",
    option_d: "sleep() is required between all HTTP requests in k6",
    answer: "B",
    explanation: "`sleep(1)` pauses the virtual user for 1 second — simulating time spent reading a page. A test without think time at 100 VUs generates 100 requests/second continuously — unrealistic. Real users spend 2-5 seconds between actions. Think time calibrates the load to match actual usage patterns.",
  },
  {
    lesson_title: "Performance Testing with k6",
    question: "What is the stages option in k6 and why is it important?",
    option_a: "stages defines which test environments to run in sequence",
    option_b: "stages ramps VUs up and down over time — simulating realistic traffic growth, peak load, and cool-down rather than immediately hammering the server with full load",
    option_c: "stages defines the sequence of test scenarios to execute",
    option_d: "stages is used to split the test across multiple k6 agents",
    answer: "B",
    explanation: "`stages: [{ duration: '2m', target: 100 }, { duration: '5m', target: 100 }, { duration: '2m', target: 0 }]` ramps to 100 VUs over 2 min, sustains for 5 min, then ramps down. This avoids a 'thundering herd' start and matches real traffic patterns — gradual growth, sustained peak, decline.",
  },
  {
    lesson_title: "Performance Testing with k6",
    question: "Your k6 test shows p95 response time of 800ms, but the SLA requires p95 < 300ms. What do you report and what does this mean for release?",
    option_a: "p95 is a guideline — the release can proceed with a note",
    option_b: "Report: p95 SLA breach (800ms vs. 300ms target). This means 5% of users experience > 800ms response times — a release blocker. Recommend: profiling the endpoint, identifying the bottleneck (DB query? slow algorithm?), and re-testing after optimization",
    option_c: "Adjust the SLA threshold to 1000ms to make the test pass",
    option_d: "Re-run the test with fewer VUs to achieve the target",
    answer: "B",
    explanation: "p95=800ms means 1 in 20 users waits > 800ms. At 10,000 daily users, 500 get a degraded experience. This is a quantified, release-blocking finding. Report with numbers, document the current baseline, and track improvement after each optimization iteration.",
  },
  {
    lesson_title: "Performance Testing with k6",
    question: "What are the default metrics k6 collects automatically?",
    option_a: "k6 only collects metrics you explicitly define with Trend()",
    option_b: "k6 automatically collects: http_req_duration (response time), http_req_failed (error rate), http_reqs (total requests), iterations (VU iterations), vus (active VUs), and data_sent/received",
    option_c: "k6 only collects pass/fail status per test",
    option_d: "k6 collects metrics only when using the Grafana integration",
    answer: "B",
    explanation: "Built-in k6 metrics give immediate insight: `http_req_duration` (p50, p90, p95, p99, max), `http_req_failed` rate, `http_reqs` (throughput). Percentiles show distribution — a max of 5000ms is less actionable than p99=800ms. These metrics are always available without configuration.",
  },
  {
    lesson_title: "Performance Testing with k6",
    question: "How do you configure a smoke test vs. a load test in k6?",
    option_a: "Smoke and load tests use different k6 commands",
    option_b: "Smoke test: 1-5 VUs, 1-2 minute duration — verifies the script works and the system responds normally. Load test: realistic VU count (e.g., 100-500), 15-30 minute duration with ramp-up stages — tests under expected production load",
    option_c: "Load tests require the k6 Pro license",
    option_d: "Smoke tests are run without thresholds; load tests require strict thresholds",
    answer: "B",
    explanation: "Always run smoke before load: `options = { vus: 1, duration: '1m' }` catches script errors and system failures at minimal load. Load test: `stages: [{duration: '5m', target: 200}, {duration: '10m', target: 200}]` with thresholds. Running a broken script at 500 VUs wastes time and can destabilize the test environment.",
  },
  {
    lesson_title: "Performance Testing with k6",
    question: "You run a k6 test and the error rate increases from 0% to 15% as VUs climb above 200. What does this tell you?",
    option_a: "The test script has a bug causing errors at high VU counts",
    option_b: "The system's capacity limit is around 200 concurrent users — above this, it starts rejecting requests or returning errors. This is the breaking point, and 200 VUs is likely the effective ceiling before SLA breach",
    option_c: "The k6 agent itself is overloaded and cannot send requests faster",
    option_d: "A network firewall is blocking requests above a certain rate",
    answer: "B",
    explanation: "Error rate inflection at 200 VUs = capacity threshold. The system is overwhelmed: connection pool exhausted, timeouts, 500 errors. Report: system capacity is ~200 concurrent users before degradation. Recommendation: scale horizontally (add servers) or optimize the bottleneck before handling higher load.",
  },
  {
    lesson_title: "Performance Testing with k6",
    question: "How do you parameterize test data in k6 to avoid all VUs using the same user account?",
    option_a: "Use the same test account for all VUs — performance tests don't need unique users",
    option_b: "Use SharedArray to load a CSV/JSON list of users and assign each VU iteration a unique user: `const user = users[exec.scenario.iterationInTest % users.length]`",
    option_c: "Generate random usernames inside the default function using Math.random()",
    option_d: "Create 500 test accounts manually in the database before each test run",
    answer: "B",
    explanation: "`const users = new SharedArray('users', () => JSON.parse(open('./users.json')))` loads once, shared across VUs. Each iteration picks a different user. Without this, 100 VUs login with the same credentials simultaneously — triggering rate limiting, session conflicts, and unrealistic server behavior.",
  },
  {
    lesson_title: "Performance Testing with k6",
    question: "What is a soak test (endurance test) and what specific problems does it detect?",
    option_a: "A soak test runs at maximum load for 30 minutes",
    option_b: "A soak test runs at moderate load (60-70% of capacity) for extended time (hours) — it specifically detects memory leaks, database connection pool exhaustion, and gradual performance degradation that only appears over time",
    option_c: "A soak test verifies the system can handle a sudden 10x traffic spike",
    option_d: "A soak test is equivalent to a load test with a longer duration",
    answer: "B",
    explanation: "Memory leaks, thread leaks, and connection pool issues don't appear immediately — they accumulate over hours. Soak test: 70% load, 4-8 hours. Watch: memory steadily increasing (leak), response time degrading after 2 hours (resource exhaustion), error rate appearing gradually (connection pool full).",
  },
  {
    lesson_title: "Performance Testing with k6",
    question: "The team says performance testing is 'the infrastructure team's responsibility.' How do you respond?",
    option_a: "Agree — infrastructure owns all performance concerns",
    option_b: "Disagree: application code performance (inefficient queries, N+1 problems, blocking operations) is a development concern. QA's role is to write the performance tests that surface these issues. Infrastructure scales the platform; developers write efficient code — both are responsible",
    option_c: "Agree partially — QA should only test UI performance, not backend",
    option_d: "Performance testing requires specialized tools that only infrastructure teams have access to",
    answer: "B",
    explanation: "Performance is a shared responsibility. An O(n²) algorithm in code cannot be fixed by adding more servers (just costs more). A missing database index causing 800ms queries is a code/DBA issue. Infrastructure handles scaling; QA and developers own code efficiency. Performance tests belong in the development CI pipeline.",
  },
  {
    lesson_title: "Performance Testing with k6",
    question: "How do you integrate k6 performance tests into a CI/CD pipeline?",
    option_a: "Performance tests cannot run in CI — they need dedicated hardware",
    option_b: "Run k6 in CI with `k6 run --vus 10 --duration 1m script.js` after deployment to staging, set thresholds that fail the pipeline if breached, and use output formats (JSON, InfluxDB) to trend metrics over time",
    option_c: "Only run performance tests before major releases, not in CI",
    option_d: "k6 requires a GUI to interpret results — it cannot run in headless CI",
    answer: "B",
    explanation: "k6 in CI: `k6 run script.js` exits 0 if thresholds pass, 1 if they fail — just like test suites. Keep CI performance tests lightweight (10 VUs, 1 min smoke). Full load tests run nightly or pre-release. Output to InfluxDB+Grafana to track performance trends across every deployment.",
  },
  {
    lesson_title: "Performance Testing with k6",
    question: "What is the VU (virtual user) model in k6 and how does it relate to real-world concurrency?",
    option_a: "Each VU represents exactly one thread on the server",
    option_b: "Each VU simulates one user's journey — executing the default function sequentially with think times. 100 VUs = 100 users actively using the app simultaneously. VU count translates to concurrent session count in production",
    option_c: "VUs only send GET requests — POST requests require a different model",
    option_d: "VU count directly equals requests per second",
    answer: "B",
    explanation: "100 VUs = 100 concurrent sessions. If each user makes 1 request per 5 seconds (with sleep(4)), throughput = 100/5 = 20 RPS. Match VU count to expected concurrent users in production — not raw RPS — for a realistic test. Monitor your analytics for peak concurrent user counts to set VU targets.",
  },
  {
    lesson_title: "Performance Testing with k6",
    question: "After a performance test, you see p50=200ms but p99=4000ms. What does this mean and what should you investigate?",
    option_a: "p50 is the important metric — p99 outliers are acceptable",
    option_b: "A wide gap between p50 and p99 means most requests are fast but some are extremely slow — indicating an intermittent bottleneck: occasional slow DB queries, garbage collection pauses, lock contention, or a specific code path that triggers slowly",
    option_c: "The test was not run long enough — run it again for more data",
    option_d: "p99 is only relevant for SLA discussions, not for optimization",
    answer: "B",
    explanation: "p50=200ms, p99=4000ms: median is fine but 1% of requests are 20x slower. Root causes: (1) DB queries without indexes that occasionally hit a slow path, (2) GC pauses in JVM applications, (3) lock contention under high concurrency. Investigate with APM tools (Datadog, New Relic) to capture the slow request traces.",
  },
];
