import type { QuizRow } from "../../quiz-types";

export const securityTestingAndOwaspTop10Quizzes: QuizRow[] = [
  {
    lesson_title: "Security Testing & OWASP Top 10",
    question: "What is the OWASP Top 10 and why is it important for QA?",
    option_a: "A list of the 10 most popular web frameworks",
    option_b: "A regularly updated list of the most critical web application security risks — QA should test for these vulnerabilities because they represent the most common and impactful security failures in production applications",
    option_c: "A performance testing standard published by OWASP",
    option_d: "A list of the top 10 testing tools recommended for security",
    answer: "B",
    explanation: "OWASP Top 10 (2021): Broken Access Control, Cryptographic Failures, Injection, Insecure Design, Security Misconfiguration, Vulnerable Components, Authentication Failures, Software Integrity Failures, Logging Failures, SSRF. These represent real-world breaches — QA testing for them prevents the most common attack vectors.",
  },
  {
    lesson_title: "Security Testing & OWASP Top 10",
    question: "What is SQL injection and how do you test for it?",
    option_a: "Injecting test SQL queries to verify the database works correctly",
    option_b: "Malicious SQL input that manipulates database queries — test by entering payloads like `' OR '1'='1` in input fields and verifying the application returns an error or unchanged response, not extra data",
    option_c: "A performance test that sends many SQL queries simultaneously",
    option_d: "A test to verify SQL syntax in stored procedures",
    answer: "B",
    explanation: "SQL injection: `username = ' OR '1'='1' --` attempts to bypass login. A vulnerable app returns data for all users. Test: enter payloads in all input fields and verify (1) the app rejects or sanitizes the input, (2) an error page doesn't expose stack traces, (3) parameterized queries are used in code review.",
  },
  {
    lesson_title: "Security Testing & OWASP Top 10",
    question: "What is Broken Access Control and provide an example of how to test for it?",
    option_a: "Broken Access Control means the login page has no password requirement",
    option_b: "Broken Access Control is when users can access resources they shouldn't — test by logging in as User A and attempting to access User B's data by modifying the user_id parameter in the URL or request body",
    option_c: "Broken Access Control only applies to admin panels",
    option_d: "Broken Access Control means the app doesn't use HTTPS",
    answer: "B",
    explanation: "IDOR (Insecure Direct Object Reference): `/api/orders/123` returns Order 123 while logged in as User A. Change to `/api/orders/124` (User B's order) — should return 403, not the order data. Test all ID parameters for horizontal privilege escalation. This is the #1 OWASP vulnerability.",
  },
  {
    lesson_title: "Security Testing & OWASP Top 10",
    question: "An application returns a full stack trace in the error response when an exception occurs. Why is this a security risk?",
    option_a: "Stack traces slow down the API response — it's a performance issue",
    option_b: "Stack traces expose internal technology details (framework versions, file paths, class names) that attackers use to target known vulnerabilities in those specific versions",
    option_c: "Stack traces are only a concern in development environments",
    option_d: "Stack traces cause browser compatibility issues",
    answer: "B",
    explanation: "A stack trace showing `org.springframework 5.3.2` tells an attacker exactly which CVEs to exploit. File paths reveal directory structure. Class names expose business logic. Test: trigger errors (invalid data, missing fields) and verify the response contains only a generic error message, not technical details.",
  },
  {
    lesson_title: "Security Testing & OWASP Top 10",
    question: "What is Cross-Site Scripting (XSS) and how do you test for it?",
    option_a: "XSS is when a website loads content from another website",
    option_b: "XSS is injecting malicious scripts into pages viewed by other users — test by entering `<script>alert('XSS')</script>` in input fields that display user content and verify it is sanitized/escaped, not executed",
    option_c: "XSS only affects forms with file upload functionality",
    option_d: "XSS is a type of server-side attack that exploits database queries",
    answer: "B",
    explanation: "Stored XSS: attacker submits `<img src=x onerror='stealCookies()'>` as a comment. Victim loads the page, the script executes, cookies stolen. Test: enter HTML/script tags in all user-editable fields (name, bio, comment). Verify the output is HTML-encoded (`&lt;script&gt;`) not executed (`<script>`).",
  },
  {
    lesson_title: "Security Testing & OWASP Top 10",
    question: "What is CSRF (Cross-Site Request Forgery) and how is it prevented?",
    option_a: "CSRF is a type of SQL injection targeting CSRF tokens",
    option_b: "CSRF tricks a logged-in user's browser into making an unintended request to the application — prevented by including a unique CSRF token in forms that the server validates before processing the request",
    option_c: "CSRF only affects GET requests",
    option_d: "CSRF is prevented by HTTPS alone",
    answer: "B",
    explanation: "CSRF: malicious site has `<img src='https://bank.com/transfer?to=attacker&amount=1000'>` — if user is logged into bank.com, their browser sends the request with valid cookies. Prevention: CSRF token (random value in form, verified server-side). Test: submit requests without CSRF tokens — server should reject them.",
  },
  {
    lesson_title: "Security Testing & OWASP Top 10",
    question: "You're testing a file upload feature. What security test cases should you include?",
    option_a: "Only test that the file uploads successfully",
    option_b: "Test: uploading executable files (.php, .exe, .js), files with double extensions (file.jpg.php), oversized files, files with malicious content in metadata, path traversal in filename (../../etc/passwd), and verify files are stored outside the web root",
    option_c: "Only test the file size limit",
    option_d: "Security testing of file uploads requires specialized tools only",
    answer: "B",
    explanation: "File upload attacks: (1) Upload shell.php — if executed, attacker has server control. (2) File.jpg with PHP code — server executes if content-type not validated. (3) `../../../etc/passwd` as filename — path traversal. Mitigations: whitelist extensions, validate content-type, rename files, store outside web root.",
  },
  {
    lesson_title: "Security Testing & OWASP Top 10",
    question: "What is the principle of least privilege and how should you test for it?",
    option_a: "Least privilege means giving all users the same permissions to simplify management",
    option_b: "Least privilege means users and services have only the minimum access needed for their role — test by verifying regular users cannot perform admin actions, and API keys/service accounts cannot access resources outside their defined scope",
    option_c: "Least privilege only applies to database access",
    option_d: "Least privilege is enforced by HTTPS and does not need to be tested",
    answer: "B",
    explanation: "Test permission boundaries: (1) Regular user tries admin API endpoints — should get 403, (2) User A tries to delete User B's data — 403, (3) Service account tries to access another service's data — 403, (4) Revoked user still has a valid token — verify token expiry is enforced. Map all roles and test all cross-role access.",
  },
  {
    lesson_title: "Security Testing & OWASP Top 10",
    question: "An API endpoint does not limit the number of login attempts. Why is this a security risk and how do you test it?",
    option_a: "Unlimited login attempts are acceptable — they don't affect performance",
    option_b: "No rate limiting enables brute force attacks — test by sending 100+ login requests with wrong passwords and verifying the API returns 429 or temporarily locks the account after a threshold is reached",
    option_c: "Login attempt limiting is the client's responsibility, not the server's",
    option_d: "Brute force attacks are only possible with specialized tools and cannot be tested by QA",
    answer: "B",
    explanation: "Brute force: automated tool tries all password combinations. Without rate limiting, a 6-character password falls in minutes. Test: script 50 failed login attempts — server should return 429, add delays, or lock the account. Check that lockout notification is sent and lockout duration is reasonable.",
  },
  {
    lesson_title: "Security Testing & OWASP Top 10",
    question: "What is security testing vs. penetration testing and what is QA's role in each?",
    option_a: "They are the same — QA engineers perform both",
    option_b: "Security testing (QA's role): systematic testing of known vulnerability patterns (OWASP Top 10, input validation, auth). Penetration testing: certified specialists simulate real attacks with advanced techniques — QA provides coverage, pentesters find deeper vulnerabilities",
    option_c: "QA should not be involved in security testing — it's only for security teams",
    option_d: "Penetration testing is automated; security testing is manual",
    answer: "B",
    explanation: "QA can and should test for well-known security vulnerabilities: input validation, access control, error handling, sensitive data exposure. Penetration testing requires specialized skills (reverse engineering, exploit development) and tools. Both are necessary: QA catches common issues early, pentesters find complex vulnerabilities.",
  },
  {
    lesson_title: "Security Testing & OWASP Top 10",
    question: "What does 'sensitive data exposure' mean in OWASP and how do you test for it?",
    option_a: "Exposing test data to developers during testing",
    option_b: "Transmitting or storing sensitive data (passwords, credit cards, PII) without adequate protection — test by verifying HTTPS is enforced, passwords are hashed (not stored plaintext), and sensitive fields are masked in logs and API responses",
    option_c: "Exposing API documentation to the public",
    option_d: "Showing error messages to end users",
    answer: "B",
    explanation: "Test: (1) Check API responses — credit card numbers should be masked (`****1234`), (2) Check network traffic is HTTPS only (no HTTP), (3) Check application logs don't contain passwords or tokens, (4) Verify password storage uses bcrypt/argon2 (not MD5 or plaintext), (5) Check for autocomplete=off on password fields.",
  },
  {
    lesson_title: "Security Testing & OWASP Top 10",
    question: "What is the difference between authentication testing and authorization testing?",
    option_a: "They test the same thing — both verify user identity",
    option_b: "Authentication testing verifies identity validation (login works correctly, invalid credentials rejected); authorization testing verifies access control (authenticated users can only access what they're permitted to — not other users' data or elevated privileges)",
    option_c: "Authentication is tested by security teams; authorization by QA",
    option_d: "Authorization testing only applies to admin roles",
    answer: "B",
    explanation: "Authentication: Can user prove who they are? Tests: valid login succeeds, invalid login fails, brute force protected. Authorization: Does the verified identity have permission? Tests: user can only see their own data, regular users can't access admin endpoints, tokens can't be forged. Both must be tested systematically.",
  },
  {
    lesson_title: "Security Testing & OWASP Top 10",
    question: "A developer says 'security testing slows us down — let the security team handle it at the end.' How do you respond?",
    option_a: "Agree — security testing is specialized and should be done separately",
    option_b: "Explain that fixing security vulnerabilities at the end is 10-100x more expensive than preventing them early. QA should test basic security patterns throughout development; a final security audit complements, not replaces, ongoing security testing",
    option_c: "Agree to only test security for high-risk features",
    option_d: "Suggest running all security tests overnight to avoid slowing the team",
    answer: "B",
    explanation: "A SQL injection bug found in code review: 30 minutes to fix. Found in staging: 2 days (regression + retest). Found in production post-breach: incident response, data breach notification, legal costs, reputation damage. Shift-left applies to security too. Basic security tests (input validation, auth, access control) belong in CI.",
  },
  {
    lesson_title: "Security Testing & OWASP Top 10",
    question: "What is security misconfiguration and what are common examples to test for?",
    option_a: "Security misconfiguration is when developers write insecure code",
    option_b: "Security misconfiguration is insecure default settings left in place — test for: debug mode enabled in production, default admin credentials unchanged, unnecessary ports/services exposed, directory listing enabled, missing security headers (X-Frame-Options, CSP, HSTS)",
    option_c: "Security misconfiguration only applies to database servers",
    option_d: "Security misconfiguration is the same as insecure authentication",
    answer: "B",
    explanation: "Common misconfiguration tests: (1) `/actuator` or `/admin` endpoints publicly accessible, (2) Default credentials (admin/admin), (3) `X-Frame-Options: DENY` header missing (enables clickjacking), (4) `Content-Security-Policy` missing (enables XSS), (5) HTTP (not HTTPS) accepted, (6) Verbose error messages in production.",
  },
  {
    lesson_title: "Security Testing & OWASP Top 10",
    question: "How do you test that JWT tokens are validated correctly?",
    option_a: "JWT tokens are validated automatically by frameworks — no testing needed",
    option_b: "Test: use an expired token (should get 401), modify the token payload and re-sign with a different key (should get 401), use a token with 'alg: none' (should be rejected), and verify the token is validated on every protected endpoint",
    option_c: "JWT validation only needs to be tested on the login endpoint",
    option_d: "Test JWT by decoding it and verifying the payload matches the user",
    answer: "B",
    explanation: "JWT attack vectors: (1) Algorithm confusion — `alg: none` bypasses signature verification in vulnerable implementations. (2) Modified payload — change `role: user` to `role: admin` and resign. (3) Expired token reuse. (4) Token used after logout. Test each scenario — JWT misimplementation is a common authentication vulnerability.",
  },
];
