import type { QuizRow } from "../../quiz-types";

export const bddWithCucumberAndGherkinQuizzes: QuizRow[] = [
  {
    lesson_title: "BDD with Cucumber & Gherkin",
    question: "Why does BDD solve a real team communication problem that TDD does not?",
    option_a: "BDD is faster to write than TDD",
    option_b: "TDD tests are written in code that non-technical stakeholders cannot read or validate — BDD uses plain-English Gherkin scenarios that business, QA, and developers all write and review together, preventing requirement misunderstandings before code is written",
    option_c: "BDD replaces unit tests, making TDD obsolete",
    option_d: "BDD only applies to UI testing, while TDD covers unit testing",
    answer: "B",
    explanation: "The real BDD value: a BA writes Given/When/Then, a QA refines edge cases, a developer reads it as a spec — all from the same artifact. With TDD alone, the spec lives in code only developers can read. BDD surfaces misunderstandings in a meeting, not in production.",
  },
  {
    lesson_title: "BDD with Cucumber & Gherkin",
    question: "What is the Given/When/Then structure in Gherkin and what does each part represent?",
    option_a: "Given = the test name, When = the action, Then = the cleanup step",
    option_b: "Given = precondition/context (system state before action), When = the user action or event, Then = the expected observable outcome — each part is specific and testable",
    option_c: "Given/When/Then is optional — Gherkin only requires Feature and Scenario",
    option_d: "Then must always contain a database verification",
    answer: "B",
    explanation: "Given: `Given the user is logged in and has an empty cart` (precondition). When: `When they add a product to the cart` (action). Then: `Then the cart badge shows 1 item` (observable outcome). Each step must be independently verifiable and unambiguous.",
  },
  {
    lesson_title: "BDD with Cucumber & Gherkin",
    question: "What is a Scenario Outline in Gherkin and when should you use it?",
    option_a: "A Scenario Outline is a required template for every feature file",
    option_b: "A Scenario Outline runs the same scenario with multiple data combinations using an Examples table — use it when the same test logic applies to multiple input/output cases to avoid duplicating scenarios",
    option_c: "Scenario Outline is only for performance testing scenarios",
    option_d: "Scenario Outline replaces all regular Scenarios in BDD",
    answer: "B",
    explanation: "`Scenario Outline: Login with <role>` + `Examples: | role | dashboard | admin | /admin | user | /home |` runs the login scenario twice with different data. Without Outline, you'd write identical scenarios with different values. Use for data-driven tests; don't overuse — it can reduce readability.",
  },
  {
    lesson_title: "BDD with Cucumber & Gherkin",
    question: "What is the Background keyword in Gherkin and how does it differ from Given in a Scenario?",
    option_a: "Background is a comment block above the Feature",
    option_b: "Background contains Given steps that run before every Scenario in a Feature file — it avoids repeating common setup steps in every Scenario. Unlike a Scenario's Given, Background applies to all Scenarios in the file",
    option_c: "Background is equivalent to beforeAll in code — it runs once per feature",
    option_d: "Background can contain When and Then steps too",
    answer: "B",
    explanation: "`Background: Given the user is logged in as admin` runs before every Scenario in the file — equivalent to a beforeEach. It reduces duplication when all scenarios in a feature share the same precondition. Keep it short: if the background has 5+ steps, the feature is likely doing too much.",
  },
  {
    lesson_title: "BDD with Cucumber & Gherkin",
    question: "A QA engineer writes: `When the user does the checkout process`. What is wrong with this step?",
    option_a: "It uses 'When' incorrectly — 'When' is only for API calls",
    option_b: "The step is vague and non-testable — 'the checkout process' could mean 10 different things. It should be broken into specific steps: 'When the user clicks Proceed to Checkout', 'And enters valid payment details', 'And clicks Place Order'",
    option_c: "There is nothing wrong — scenarios should be high-level",
    option_d: "The step should start with 'Given' not 'When'",
    answer: "B",
    explanation: "BDD anti-pattern: imperative vs. declarative. 'User does checkout process' is underdefined — what exactly happens? Break into atomic steps that can be individually automated. Each step should describe one specific action or assertion. Ambiguous steps produce ambiguous automation.",
  },
  {
    lesson_title: "BDD with Cucumber & Gherkin",
    question: "What are Cucumber tags and how are they used?",
    option_a: "Tags are required metadata for every scenario",
    option_b: "Tags (e.g., @smoke, @regression, @slow) label scenarios so they can be selectively run — run only smoke tests with `--tags @smoke`, skip slow tests in CI with `--tags 'not @slow'`",
    option_c: "Tags automatically categorize tests into pass/fail groups",
    option_d: "Tags are only used for generating test reports",
    answer: "B",
    explanation: "Tags enable selective execution: `@smoke` for critical path tests, `@regression` for full suite, `@wip` for in-progress scenarios, `@ignore` for known-broken tests. In CI: run `@smoke` on every commit (fast), `@regression` on PR merge (thorough). Tags are the BDD equivalent of test suites.",
  },
  {
    lesson_title: "BDD with Cucumber & Gherkin",
    question: "What is 'living documentation' in the context of BDD?",
    option_a: "A wiki page that is updated manually after each sprint",
    option_b: "Feature files that serve as both the automated test suite and human-readable specifications — because they run as tests, they are always accurate (if they pass, the feature works as described) unlike static documentation",
    option_c: "Auto-generated API documentation from code comments",
    option_d: "A Jira board that tracks feature completion status",
    answer: "B",
    explanation: "Living documentation: feature files that pass CI = the system behaves exactly as described. Static docs go stale — no one updates them. With BDD, the spec IS the test — if the test passes, the documentation is accurate. This is one of BDD's core values beyond just test automation.",
  },
  {
    lesson_title: "BDD with Cucumber & Gherkin",
    question: "Your team has 200 Cucumber scenarios and they take 2 hours to run. The business wants new features daily. How do you address this?",
    option_a: "Remove Cucumber and use a faster testing framework",
    option_b: "Parallelize Cucumber execution with multiple threads, tag scenarios by run frequency (@smoke for CI, @regression for nightly), and replace slow UI Cucumber scenarios with faster API-level step definitions where possible",
    option_c: "Ask the business to slow down feature delivery",
    option_d: "Run only the scenarios that changed in the last commit",
    answer: "B",
    explanation: "Cucumber performance: (1) Parallel: Cucumber-JVM supports parallel execution — split across 8 threads for 8x speedup. (2) Tiering: @smoke (30 scenarios, 10 min) runs on every commit; @regression runs nightly. (3) API vs UI: step definitions can call API directly (50ms) instead of driving browser (5s) for logic tests.",
  },
  {
    lesson_title: "BDD with Cucumber & Gherkin",
    question: "A developer says 'BDD is just overhead — tests would be faster to write directly in code.' How do you respond?",
    option_a: "Agree — BDD is only useful for large enterprises",
    option_b: "Explain: BDD's value is collaboration, not test speed. The Given/When/Then format surfaces requirement gaps before coding, enables non-technical review, and creates shared understanding. If the team doesn't use feature files for collaboration, they are indeed overhead — BDD requires buy-in from business and QA, not just developers",
    option_c: "Disagree — Gherkin is faster to write than code-based tests",
    option_d: "Agree and replace BDD with pure Playwright tests",
    answer: "B",
    explanation: "BDD is a collaboration practice, not just a test format. It adds value when: BA writes draft scenarios, QA refines them, dev implements step definitions based on agreed behavior. Without this collaboration, writing Gherkin on top of existing tests IS overhead. The ceremony is the point — not the syntax.",
  },
  {
    lesson_title: "BDD with Cucumber & Gherkin",
    question: "What is the step definition in Cucumber and what does it contain?",
    option_a: "A step definition is the Gherkin text in the feature file",
    option_b: "A step definition is the code implementation that maps to a Gherkin step — it contains the automation logic (page interactions, API calls, assertions) and is linked to the Gherkin text via regex or string matching",
    option_c: "Step definitions are generated automatically by Cucumber",
    option_d: "A step definition is a comment that explains what the step does",
    answer: "B",
    explanation: "Feature file: `When the user clicks the Login button`. Step definition: `@When('the user clicks the Login button') public void clickLogin() { loginPage.clickLoginButton(); }`. The feature file is human-readable; the step definition is the executable automation behind it. They're linked by pattern matching.",
  },
  {
    lesson_title: "BDD with Cucumber & Gherkin",
    question: "What is the difference between a Feature and a Scenario in Gherkin?",
    option_a: "They are the same — Feature and Scenario can be used interchangeably",
    option_b: "A Feature describes one functional capability of the system (Login, Checkout) and contains multiple Scenarios. A Scenario is one specific test case within that feature — one concrete behavior to verify",
    option_c: "A Feature contains the step definitions; a Scenario contains the Gherkin steps",
    option_d: "A Feature is a test suite; a Scenario is an individual assertion",
    answer: "B",
    explanation: "Feature: `Feature: User Authentication` — describes the overall functionality. Scenario: `Scenario: Successful login with valid credentials` — one specific testable behavior. One Feature file contains multiple Scenarios covering the feature's happy paths, error cases, and edge cases.",
  },
  {
    lesson_title: "BDD with Cucumber & Gherkin",
    question: "After 6 months, your Cucumber feature files are hundreds of lines long and nobody reads them. What went wrong?",
    option_a: "Cucumber is not suitable for projects lasting more than 3 months",
    option_b: "Feature files grew without discipline — scenarios became too detailed, steps are too technical and reusable only by developers, and the business stopped reviewing them. BDD became test automation overhead instead of collaboration",
    option_c: "The scenarios need to be split into more files",
    option_d: "The step definitions need to be refactored",
    answer: "B",
    explanation: "BDD decay signs: (1) Steps like `When I click the button with id 'submit-btn'` — technical, not business language. (2) Scenarios with 20+ steps — too detailed. (3) Business never reads them. Fix: rewrite with business language, limit scenarios to 5-7 steps, and schedule regular business review of feature files. BDD dies without the collaboration process.",
  },
  {
    lesson_title: "BDD with Cucumber & Gherkin",
    question: "What is the 'And' keyword in Gherkin and when should you use it?",
    option_a: "And is used to chain multiple Features together",
    option_b: "And continues the previous step type — it avoids repeating Given/When/Then for multiple consecutive steps of the same type, improving readability: 'Given X, And Y' instead of 'Given X, Given Y'",
    option_c: "And is only valid after Then steps",
    option_d: "And creates a conditional step that only runs if the previous step passed",
    answer: "B",
    explanation: "`Given the user is on the login page / And the user has a valid account / When they enter their email / And they enter their password / And they click Login / Then they see the dashboard / And their name is displayed` — And keeps the flow readable without repeating Given/When/Then for each consecutive step.",
  },
  {
    lesson_title: "BDD with Cucumber & Gherkin",
    question: "How should error and negative scenarios be written in Gherkin?",
    option_a: "Negative scenarios should not be in BDD — only happy paths",
    option_b: "Negative scenarios use the same Given/When/Then format with a Then that asserts an error state: 'Then an error message Your password is incorrect is displayed' — they are first-class scenarios, not edge cases to skip",
    option_c: "Negative scenarios should be written in code, not Gherkin",
    option_d: "Use 'But' keyword for all negative scenarios",
    answer: "B",
    explanation: "Negative scenarios are equally important: `Scenario: Login fails with wrong password / Given the user is on the login page / When they enter a valid email and incorrect password / Then the error message 'Invalid credentials' is displayed / And they remain on the login page`. These define error behavior as clearly as happy paths.",
  },
  {
    lesson_title: "BDD with Cucumber & Gherkin",
    question: "What is the ideal relationship between the Three Amigos (BA, Developer, QA) and Gherkin scenarios?",
    option_a: "QA should write all Gherkin scenarios independently after requirements are finalized",
    option_b: "BA drafts initial scenarios from business requirements, QA adds edge cases and negative scenarios, Developer reviews for technical feasibility and implementation clarity — scenarios are agreed before coding starts",
    option_c: "Developers write scenarios based on their code implementation",
    option_d: "Gherkin scenarios should only be written by certified BDD practitioners",
    answer: "B",
    explanation: "Three Amigos and BDD: (1) BA drafts Given/When/Then from user stories — defines 'what success looks like'. (2) QA adds: 'what if the email is invalid?' 'what if the network fails?' (3) Developer reviews: 'this step implies a specific API call — is that correct?' Scenarios approved by all three before sprint start prevent the most expensive bugs: misunderstood requirements.",
  },
];
