import type { QuizRow } from "../../quiz-types";

export const testDataManagementQuizzes: QuizRow[] = [
  {
    lesson_title: "Test Data Management",
    question: "What is test data management and why is it important?",
    option_a: "Managing test files and screenshots in version control",
    option_b: "The practice of creating, maintaining, and cleaning up data needed for tests — poor test data management leads to test failures, flakiness, and data pollution that affects other tests or environments",
    option_c: "Documenting what data is tested in each test case",
    option_d: "Compressing test data files to save storage space",
    answer: "B",
    explanation: "Test data management encompasses: creating test data (factories, seeds), ensuring isolation (no shared data between parallel tests), cleanup (post-test), and data security (no real PII in non-production). Bad test data = flaky tests, order-dependent tests, and data contamination across environments.",
  },
  {
    lesson_title: "Test Data Management",
    question: "What is the main problem with using production data in test environments?",
    option_a: "Production data is too large to copy to test environments",
    option_b: "Production data contains real PII (names, emails, payment info) — using it in test environments risks unauthorized access, regulatory violations (GDPR, HIPAA), and accidental data exposure to developers and testers",
    option_c: "Production data has different formats than test data",
    option_d: "Production data cannot be restored after testing",
    answer: "B",
    explanation: "GDPR Article 25: Privacy by Design — data minimization applies to test environments. Real customer data in a developer laptop is a breach waiting to happen. Solution: data masking (replace real values with realistic fake values) or synthetic data generation. Test with realistic data that has no real individuals behind it.",
  },
  {
    lesson_title: "Test Data Management",
    question: "What is a test data factory and how does it help?",
    option_a: "A factory that manufactures test cases automatically",
    option_b: "A function or class that creates valid test data objects with sensible defaults, allowing tests to override only the values relevant to the scenario — reducing test setup boilerplate and making tests self-documenting",
    option_c: "A database tool that generates large datasets for performance testing",
    option_d: "A CI/CD tool that manages test environment provisioning",
    answer: "B",
    explanation: "`createUser({ role: 'admin' })` returns a full user object with all required fields populated with defaults, only overriding `role`. Without factories, each test sets up 15 fields manually — most irrelevant to the test. Factories: less setup code, clearer test intent, easier maintenance when schema changes.",
  },
  {
    lesson_title: "Test Data Management",
    question: "Your parallel test suite fails intermittently with unique constraint violations. What is the root cause and fix?",
    option_a: "The database server cannot handle parallel writes",
    option_b: "Multiple parallel tests are creating data with the same unique value (same email, same username) — fix by generating unique values per test using timestamps, UUIDs, or a unique prefix: `testuser_${uuid()}@test.com`",
    option_c: "The test framework has a bug in parallel execution mode",
    option_d: "Unique constraints should be removed from the test database",
    answer: "B",
    explanation: "Common parallel failure: Test A creates `user@test.com`, Test B also tries to create `user@test.com` — unique constraint violation. Fix: `email: `test_${Date.now()}_${Math.random()}@example.com`` or use UUIDs. Each parallel test must create completely unique data, never relying on 'this test runs first.'",
  },
  {
    lesson_title: "Test Data Management",
    question: "What is data masking and when is it used?",
    option_a: "Hiding test data behind a UI mask so testers can't see it",
    option_b: "Replacing real sensitive values with fake-but-realistic values — production `John Smith, john@real.com` becomes `Test User_4821, user4821@example.com` — preserving data structure and format while removing all real personal information",
    option_c: "Encrypting test data so only authorized testers can access it",
    option_d: "Removing entire records from a database before copying to test",
    answer: "B",
    explanation: "Masking preserves referential integrity and realistic data patterns while removing PII. Tools: Faker.js, AWS DMS transformation rules, Jailer. A masked database has real row counts, realistic distributions, and valid foreign keys — making it a good test environment without any real customer risk.",
  },
  {
    lesson_title: "Test Data Management",
    question: "A test creates a user, places an order, then the test fails before cleanup. The next test run fails because the user already exists. How do you solve this systematically?",
    option_a: "Manually delete the leftover data before each test run",
    option_b: "Use unique data per test run (UUID-based identifiers) so leftover data never conflicts, and implement teardown in afterEach/finally blocks that run even when tests fail",
    option_c: "Drop and recreate the database before each test run",
    option_d: "Accept that some test runs will fail due to data pollution",
    answer: "B",
    explanation: "Two-pronged solution: (1) Unique data per run — `user_${uuid()}` never conflicts with a previous run's data. (2) Teardown in finally — `afterEach(() => { deleteTestUser(userId); })` runs even on failure. Never rely on cleanup from the previous test run because failures happen.",
  },
  {
    lesson_title: "Test Data Management",
    question: "What is a database seed script and when should you use it?",
    option_a: "A script that generates random data to stress-test the database",
    option_b: "A script that populates a database with a known, consistent dataset before tests run — used when tests require pre-existing data (product catalog, permission roles) that is expensive or complex to create in each test",
    option_c: "A script that cleans up all test data after a test run",
    option_d: "A script that copies production data to the test environment",
    answer: "B",
    explanation: "Seed scripts: `npm run db:seed` creates reference data (product categories, permission roles, country list) that many tests share. Tests that need a specific user create their own; tests that need a product category use seeded data. Seeds run once per environment, not per test — for stable, slow-to-create reference data only.",
  },
  {
    lesson_title: "Test Data Management",
    question: "What is synthetic test data and what are its advantages over real data?",
    option_a: "Synthetic data is data that only exists in test environments, with no real-world equivalent",
    option_b: "Synthetic data is programmatically generated data that mimics real data patterns — advantages: no privacy risk, can be generated at any scale, can include edge cases that are rare in production, and can be controlled precisely for specific test scenarios",
    option_c: "Synthetic data is always lower quality than real data for testing",
    option_d: "Synthetic data only works for simple data types like strings and numbers",
    answer: "B",
    explanation: "Synthetic data advantages: (1) Privacy safe — no real people's information, (2) Controllable — generate exactly the edge cases you need, (3) Scalable — generate 1 million records on demand, (4) Reproducible — same seed = same data every time. Libraries: Faker.js, Factory Bot, Bogus. The tradeoff: may not capture unexpected real-world patterns.",
  },
  {
    lesson_title: "Test Data Management",
    question: "How should test data be managed differently for unit tests vs. E2E tests?",
    option_a: "Both unit and E2E tests should use real database data",
    option_b: "Unit tests use in-memory objects/mocks with no persistence needed; E2E tests require full database state — E2E test data must be created via API/DB setup, guaranteed unique, and cleaned up after each test",
    option_c: "Unit tests need more complex data; E2E tests can use minimal data",
    option_d: "There is no difference — use the same data strategy for both",
    answer: "B",
    explanation: "Unit test data: `const user = { id: 1, email: 'test@test.com', role: 'admin' }` — a plain object, no database needed. E2E test data: `const user = await api.createUser({ email: `${uuid()}@test.com` })` — real DB record, real API call, must be cleaned up. Different scope, different strategy.",
  },
  {
    lesson_title: "Test Data Management",
    question: "You're setting up test data for a multi-step checkout flow test. What is the correct approach?",
    option_a: "Use production-like data from the most recent database backup",
    option_b: "Create all required data in the test setup (product, user account, payment method, shipping address) with unique identifiers, run the test, then clean up all created records in teardown — keeping the test completely self-contained",
    option_c: "Reuse existing test data from previous test runs",
    option_d: "Create the data manually in the test environment before running the test",
    answer: "B",
    explanation: "Self-contained test: beforeEach creates product + user + payment method + address. Test runs checkout flow. afterEach deletes all created records. This test can run in any environment, in any order, in parallel with any other test. If setup fails, the test fails clearly. If teardown fails, unique IDs prevent next-run conflicts.",
  },
  {
    lesson_title: "Test Data Management",
    question: "What is the 'test data as code' principle?",
    option_a: "Writing test data in JSON format stored in the codebase",
    option_b: "Defining test data creation logic in code (factories, builders, fixtures) that is version-controlled alongside tests — so data setup is reproducible, reviewable, and evolves with the application schema",
    option_c: "Using code generation tools to create test data automatically",
    option_d: "Storing all test data in the same file as the test code",
    answer: "B",
    explanation: "Test data as code: factories and seed scripts in version control. When the schema changes (new required field), the factory is updated in the same PR — tests don't fail because of missing fields. Code review catches data design issues. New team members get a complete test data setup with `git clone` and `npm run setup`.",
  },
  {
    lesson_title: "Test Data Management",
    question: "The QA team relies on a shared test user account that all tests use. What problems does this cause?",
    option_a: "Shared test accounts are an efficient practice — no problem",
    option_b: "Shared accounts cause race conditions in parallel tests, order dependency (one test changes state another expects), difficult debugging (which test corrupted the account?), and false failures when account state from one test bleeds into another",
    option_c: "Shared accounts only cause problems with more than 10 parallel tests",
    option_d: "Shared accounts are only a problem if tests modify the account",
    answer: "B",
    explanation: "Parallel tests with shared user: Test A changes password → Test B's login fails. Test A adds item to cart → Test B's cart count assertion fails. Test A deletes the account → Test C crashes. Fix: each test creates its own user. More setup work upfront, but eliminates an entire class of flakiness.",
  },
  {
    lesson_title: "Test Data Management",
    question: "How do you manage test data for an API that enforces rate limiting per user?",
    option_a: "Use a single admin account that bypasses rate limiting",
    option_b: "Create a pool of test user accounts and distribute tests across different users — each user gets their own rate limit bucket, preventing tests from interfering with each other's limits",
    option_c: "Disable rate limiting in the test environment",
    option_d: "Run rate-limit-sensitive tests serially using a single user",
    answer: "B",
    explanation: "Rate limiting in tests: 100 VUs all logging in as `testuser@test.com` = all sharing one rate limit bucket. After ~N requests, all tests start getting 429. Fix: user pool — `users[threadId % users.length]` distributes across accounts. Or disable rate limiting in test env (but then you're not testing it). Choose based on what you're testing.",
  },
  {
    lesson_title: "Test Data Management",
    question: "What is test data versioning and why does it matter?",
    option_a: "Incrementing version numbers on test data files",
    option_b: "Keeping test data creation scripts in version control alongside application code — when application schema changes, the test data scripts are updated in the same commit/PR, ensuring tests always create valid data for the current schema",
    option_c: "Creating different versions of test data for different test types",
    option_d: "Maintaining a changelog of what test data was modified each sprint",
    answer: "B",
    explanation: "Schema drift: developer adds a NOT NULL column `phone_number` to users table. If test factories aren't updated, every test that creates a user fails. Version-controlled factories in the same PR as the schema change: the migration adds the column, the factory adds the field, tests pass. No out-of-sync data scripts.",
  },
  {
    lesson_title: "Test Data Management",
    question: "After running the test suite, the test database has accumulated months of old test records. What is the impact and how do you prevent it?",
    option_a: "Old test records are harmless — they don't affect new tests",
    option_b: "Accumulated test data causes: slow queries (large table scans), false test results (tests finding unexpected records), storage costs, and makes debugging harder. Prevent with: per-test cleanup, scheduled database resets, or using database transactions that rollback after each test",
    option_c: "Just increase the database server size to handle the extra data",
    option_d: "Old test records are cleared automatically by the database",
    answer: "B",
    explanation: "Test data accumulation: `SELECT * FROM users WHERE email LIKE 'test_%'` runs in 50ms with 100 records, 5 seconds with 1 million. Tests asserting 'user count = 3' start failing. Solutions: (1) afterEach cleanup — delete what you created, (2) Transactional tests — wrap in BEGIN/ROLLBACK, (3) Weekly scheduled database reset to seeded state.",
  },
];
