import type { QuizRow } from "../../quiz-types";

export const testDataManagementQuizzes: QuizRow[] = [
  {
    lesson_title: "Test Data Management",
    question: "What is test data management?",
    option_a: "Storing test results in the database",
    option_b: "Creating, maintaining, and organizing realistic data needed for tests to run reliably",
    option_c: "Backing up production data",
    option_d: "Deleting all data after tests",
    answer: "B",
    explanation: "Test data management is the practice of creating and maintaining test data that is realistic, complete, and properly isolated so tests are repeatable and reliable.",
  },
  {
    lesson_title: "Test Data Management",
    question: "Why should test data be isolated from production data?",
    option_a: "To make tests easier to read",
    option_b: "To prevent tests from accidentally modifying real customer data and to maintain test independence",
    option_c: "To slow down tests",
    option_d: "There is no reason",
    answer: "B",
    explanation: "Isolation ensures tests don't corrupt production data, allows tests to run in parallel without interference, and makes test cleanup predictable.",
  },
  {
    lesson_title: "Test Data Management",
    question: "What is a data factory in test automation?",
    option_a: "A building where data is manufactured",
    option_b: "Code that programmatically creates realistic test data on demand (users, orders, etc.)",
    option_c: "A backup system",
    option_d: "A database table",
    answer: "B",
    explanation: "A data factory is a helper function or service that generates test data (user accounts, orders, transactions) programmatically for use in tests.",
  },
  {
    lesson_title: "Test Data Management",
    question: "What is test data cleanup and why is it important?",
    option_a: "Organizing test files alphabetically",
    option_b: "Removing test data created during test execution to leave the database clean",
    option_c: "Compressing test files",
    option_d: "Deleting all tests",
    answer: "B",
    explanation: "Cleanup removes test data after each test so the database is left in a clean state for the next test. This prevents data dependencies between tests.",
  },
  {
    lesson_title: "Test Data Management",
    question: "What is a masking strategy for test data?",
    option_a: "Making tests run faster",
    option_b: "Obscuring sensitive production data (SSN, credit cards) in test copies to protect privacy",
    option_c: "Hiding test data from developers",
    option_d: "Replacing SQL queries",
    answer: "B",
    explanation: "Data masking protects privacy by replacing sensitive values (SSN, credit card numbers, emails) with fake data when creating test copies of production data.",
  },
];
