import type { QuizRow } from "../../quiz-types";

export const chaosEngineeringAndProductionTestingQuizzes: QuizRow[] = [
  {
    lesson_title: "Chaos Engineering & Production Testing",
    question: "What is chaos engineering?",
    option_a: "Making the system chaotic and unpredictable",
    option_b: "Deliberately injecting failures into production systems to test resilience and uncover weaknesses",
    option_c: "Replacing all tests",
    option_d: "A type of game development",
    answer: "B",
    explanation: "Chaos engineering intentionally causes failures (kill servers, introduce latency, disable services) to test how systems handle failure and to discover hidden weaknesses.",
  },
  {
    lesson_title: "Chaos Engineering & Production Testing",
    question: "Why is chaos engineering performed in production or production-like environments?",
    option_a: "To disrupt customer services",
    option_b: "To discover real-world failure modes that don't appear in test environments",
    option_c: "It should never be done",
    option_d: "To train developers",
    answer: "B",
    explanation: "Production and production-like environments have real data, real complexity, and real dependencies. Testing in these environments reveals failures that isolated test environments miss.",
  },
  {
    lesson_title: "Chaos Engineering & Production Testing",
    question: "What is a chaos experiment?",
    option_a: "A scientific study of chaos theory",
    option_b: "A controlled test that injects a specific failure and measures how the system and team respond",
    option_c: "Breaking the system intentionally",
    option_d: "A type of unit test",
    answer: "B",
    explanation: "A chaos experiment is a controlled test: define a hypothesis (\"our system handles database failure\"), inject a failure (kill database), and measure the impact.",
  },
  {
    lesson_title: "Chaos Engineering & Production Testing",
    question: "What is the 'blast radius' in chaos engineering?",
    option_a: "The number of developers affected",
    option_b: "The scope of impact from a failure (how many customers, how much data, how many services are affected)",
    option_c: "The size of the data center",
    option_d: "The test duration",
    answer: "B",
    explanation: "Blast radius is the potential impact scope. Start chaos experiments with small blast radius (single region, subset of users) to limit damage while learning.",
  },
  {
    lesson_title: "Chaos Engineering & Production Testing",
    question: "What should happen after a chaos experiment reveals a failure?",
    option_a: "Ignore it and continue",
    option_b: "Fix the root cause, improve monitoring, and implement circuit breakers or fallbacks",
    option_c: "Only run chaos tests in development",
    option_d: "Ban the experiment",
    answer: "B",
    explanation: "Chaos experiments reveal weaknesses so you can fix root causes, improve monitoring to detect issues faster, and implement resilience patterns (circuit breakers, fallbacks).",
  },
];
