import type { QuizRow } from "../../quiz-types";

export const chaosEngineeringAndProductionTestingQuizzes: QuizRow[] = [
  {
    lesson_title: "Chaos Engineering & Production Testing",
    question: "What is chaos engineering and what is its primary goal?",
    option_a: "Intentionally breaking production systems to create urgency for fixes",
    option_b: "Proactively injecting controlled failures into a system to discover weaknesses before they cause unplanned outages — the goal is to build confidence in system resilience under real failure conditions",
    option_c: "A type of stress testing that pushes system resources to 100%",
    option_d: "Random automated testing without predefined test cases",
    answer: "B",
    explanation: "Chaos engineering principle: 'If you don't practice failure, failure will practice you.' Controlled experiments (kill a server, inject latency, drop network packets) reveal whether monitoring alerts, failover mechanisms, and circuit breakers actually work before a real incident does.",
  },
  {
    lesson_title: "Chaos Engineering & Production Testing",
    question: "What is 'steady state' in chaos engineering and why must you define it before an experiment?",
    option_a: "A steady state is when the system is under zero load",
    option_b: "Steady state is the normal, measurable behavior of a system (error rate < 0.1%, p99 latency < 300ms, all health checks green) — you must define it before chaos experiments to know if the system recovered and to detect when it deviates",
    option_c: "Steady state is when no deployments are happening",
    option_d: "Steady state only applies to database systems",
    answer: "B",
    explanation: "Without steady state definition, you can't tell if the chaos experiment caused damage. Define: baseline metrics (latency, error rate, throughput), monitoring thresholds, and what 'recovered' means. Experiment: inject chaos → observe → confirm steady state returns. If steady state doesn't return, the experiment revealed a real resilience gap.",
  },
  {
    lesson_title: "Chaos Engineering & Production Testing",
    question: "What is 'blast radius' in chaos engineering and why is it critical to control?",
    option_a: "The amount of data deleted during a chaos experiment",
    option_b: "The scope of impact a chaos experiment can have — controlling blast radius means starting with small, isolated experiments (one non-critical service, non-peak hours) before expanding to avoid causing a real outage",
    option_c: "The number of servers affected by a chaos experiment",
    option_d: "The time required to recover from a chaos experiment",
    answer: "B",
    explanation: "Blast radius control: start small. First experiment: kill one instance in a 5-instance cluster during low-traffic hours. Verify the system handles it. Gradually expand: kill 2 instances, then simulate a full zone failure, then test during peak hours. An uncontrolled blast radius turns a chaos experiment into an actual production incident.",
  },
  {
    lesson_title: "Chaos Engineering & Production Testing",
    question: "Your team wants to test what happens when the payment service goes down. How do you design this chaos experiment safely?",
    option_a: "Take the payment service down in production without notice to test real impact",
    option_b: "Define steady state metrics, identify the smallest blast radius (one replica, canary traffic), inject failure during low-traffic hours with monitoring and a kill switch to abort, verify system shows graceful degradation (error message vs. crash), then document findings",
    option_c: "Only test this in staging — never inject failures involving payments in production",
    option_d: "Have developers read the payment service code to reason about failure modes",
    answer: "B",
    explanation: "Safe chaos experiment: (1) Define steady state (error rate, user impact), (2) Hypothesis: 'If payment service is unavailable, users see a friendly error, other features work', (3) Inject: fail one payment service replica in 5% of traffic, (4) Monitor: alert within 30s, no cascade failures, (5) Abort if unexpected impact, (6) Document: did hypothesis hold?",
  },
  {
    lesson_title: "Chaos Engineering & Production Testing",
    question: "What is a GameDay and what is its purpose?",
    option_a: "A team-building event where engineers play games to reduce burnout",
    option_b: "A planned exercise where the team simulates major failure scenarios in real-time — teams practice incident response, verify runbooks, and discover gaps in alerting and recovery procedures under controlled conditions",
    option_c: "A day reserved for running all automated test suites",
    option_d: "A quarterly security audit of production systems",
    answer: "B",
    explanation: "GameDay: 'On Friday we'll simulate a full database region failure.' Teams practice: oncall receives alert (verify monitoring), follows runbook (verify it works), fails over to secondary (verify it's tested), and validates recovery. Gaps discovered: missing alerts, wrong runbook steps, failed failover. Better to find these on a Friday than during a 3am real incident.",
  },
  {
    lesson_title: "Chaos Engineering & Production Testing",
    question: "What is the difference between chaos engineering and traditional testing?",
    option_a: "Chaos engineering is a subset of performance testing",
    option_b: "Traditional testing verifies known scenarios against requirements; chaos engineering probes unknown weaknesses in distributed systems by injecting real-world failures (network partitions, hardware failures, resource exhaustion) that are hard to simulate in pre-production",
    option_c: "Chaos engineering replaces all other forms of testing",
    option_d: "Chaos engineering only applies to microservices architectures",
    answer: "B",
    explanation: "Traditional tests: 'Does feature X work?' Chaos engineering: 'Does the system remain acceptable when service Y fails unexpectedly?' Chaos tests the emergent behavior of distributed systems under failure — things that unit, integration, and E2E tests cannot reveal because they run against a fully healthy system.",
  },
  {
    lesson_title: "Chaos Engineering & Production Testing",
    question: "What is observability and why is it a prerequisite for chaos engineering?",
    option_a: "Observability means being able to see all server logs",
    option_b: "Observability is the ability to understand a system's internal state from its external outputs (metrics, logs, traces) — without it, chaos experiments produce no actionable signal because you can't tell what impact the failure had",
    option_c: "Observability is a monitoring dashboard tool",
    option_d: "Observability only applies to production environments",
    answer: "B",
    explanation: "Chaos experiment without observability: you inject failure, something happens, but you don't know what. With observability: Prometheus metrics show error rate spike at 14:23, Jaeger traces show payment service timeout cascading to checkout, logs show circuit breaker opened. You can verify the hypothesis and understand the failure mode.",
  },
  {
    lesson_title: "Chaos Engineering & Production Testing",
    question: "What is a circuit breaker pattern and how should QA test it?",
    option_a: "A circuit breaker is a network component that prevents power surges",
    option_b: "A circuit breaker is a software pattern that stops calling a failing service after N failures, returns a fallback response instead of cascading failures — QA should test: it opens after N failures, returns the expected fallback, and closes again after the service recovers",
    option_c: "A circuit breaker is a rate limiter for API calls",
    option_d: "Circuit breakers are only relevant for database connections",
    answer: "B",
    explanation: "Test circuit breaker: (1) Simulate downstream service failures — circuit should open after threshold (e.g., 5 consecutive failures). (2) Verify fallback response is returned (not a 500). (3) Simulate service recovery — circuit should close and normal flow resume. (4) Verify no cascade: payment failing shouldn't take down the catalog service.",
  },
  {
    lesson_title: "Chaos Engineering & Production Testing",
    question: "What types of failures should be covered in a comprehensive chaos engineering program?",
    option_a: "Only server crashes — that's the most common real failure",
    option_b: "Infrastructure failures (server crashes, disk full), network failures (latency injection, packet loss, DNS failures), application failures (memory leaks, CPU spikes), dependency failures (third-party APIs unavailable), and data failures (corrupted data, missing records)",
    option_c: "Only third-party service outages since those are outside the team's control",
    option_d: "Only failures that have occurred in production before",
    answer: "B",
    explanation: "Failure taxonomy: (1) Infrastructure: kill node, disk full, memory OOM, (2) Network: add 500ms latency, drop 10% packets, block DNS, (3) Application: force GC pause, thread pool exhaustion, (4) Dependencies: mock payment service timeout, database replication lag, (5) Data: inject null values, corrupt cache. Each category reveals different failure modes.",
  },
  {
    lesson_title: "Chaos Engineering & Production Testing",
    question: "A developer argues: 'We already have 90% test coverage — we don't need chaos engineering.' How do you respond?",
    option_a: "Agree — high test coverage makes chaos engineering redundant",
    option_b: "Explain that unit/integration test coverage verifies individual component behavior under normal conditions. Chaos engineering tests distributed system behavior under failure — how components interact when things break. 90% unit coverage says nothing about what happens when the database becomes unreachable for 2 seconds",
    option_c: "Suggest increasing test coverage to 100% instead",
    option_d: "Agree partially — chaos engineering is only needed for systems with < 50% coverage",
    answer: "B",
    explanation: "Coverage measures which lines were executed. Chaos tests which failure modes are handled. A system can have 100% coverage and still cascade-fail when a downstream service is slow (no timeout configured), a disk fills up (no graceful handling), or a pod is OOM killed (no replica redundancy). These require chaos experiments, not more unit tests.",
  },
  {
    lesson_title: "Chaos Engineering & Production Testing",
    question: "What are synthetic monitoring transactions and how do they differ from traditional tests?",
    option_a: "Synthetic transactions are load test scenarios run at peak hours",
    option_b: "Synthetic transactions are automated scripts that continuously run critical user journeys against production — they verify real-world availability and performance from an end-user perspective, 24/7, rather than only verifying at deployment time",
    option_c: "Synthetic monitoring only checks HTTP status codes, not full flows",
    option_d: "Synthetic transactions are used to generate test data in production",
    answer: "B",
    explanation: "Synthetic monitoring: a Playwright script runs 'buy product' every 5 minutes in production against a synthetic account. If it fails or takes > 5s, alert fires. This catches: CDN issues affecting a region, certificate expiry, payment provider outage, database replication lag — things that only appear in production and only under real traffic.",
  },
  {
    lesson_title: "Chaos Engineering & Production Testing",
    question: "What is the Chaos Monkey and what does it specifically test?",
    option_a: "A tool that randomly deletes test cases from the test suite",
    option_b: "A Netflix-created tool that randomly terminates production EC2 instances — specifically tests whether the system can handle unexpected instance failures without user impact, enforcing that services must be designed for redundancy",
    option_c: "A security testing tool that simulates malicious users",
    option_d: "A tool that injects random test data to find edge case bugs",
    answer: "B",
    explanation: "Chaos Monkey: if your service crashes when one instance dies, you'll know before a real hardware failure. Netflix runs it in production continuously — forcing engineering teams to build resilient, redundant services. Chaos Monkey is part of the Simian Army: Latency Monkey (adds delays), Conformity Monkey (checks config), Doctor Monkey (health checks).",
  },
  {
    lesson_title: "Chaos Engineering & Production Testing",
    question: "How do you measure the success of a chaos engineering experiment?",
    option_a: "Success means no errors occurred during the experiment",
    option_b: "Success means you either confirmed your resilience hypothesis (system handled the failure as expected) or discovered a previously unknown weakness — both outcomes are valuable. A 'failed' experiment that reveals a gap is more valuable than one that confirms everything works",
    option_c: "Success is measured by the number of experiments run per sprint",
    option_d: "Success means the experiment was completed without production impact",
    answer: "B",
    explanation: "Chaos engineering reframes 'failure': finding a weakness IS the success. 'We discovered our circuit breaker doesn't open under partial failures' is a valuable finding. Confirmed hypothesis ('system remains stable with one DB replica down') builds confidence. Track: experiments run, weaknesses discovered, weaknesses fixed — all three matter.",
  },
  {
    lesson_title: "Chaos Engineering & Production Testing",
    question: "When is a system NOT ready for chaos engineering?",
    option_a: "When the system is less than 1 year old",
    option_b: "When there is insufficient observability (you can't tell if the experiment caused harm), when the system is already unstable (chaos would cause actual outages), or when there are no recovery procedures to follow if something goes wrong",
    option_c: "When the team hasn't received formal chaos engineering training",
    option_d: "When the system runs on cloud infrastructure",
    answer: "B",
    explanation: "Prerequisites for chaos engineering: (1) Adequate monitoring — if you can't see what's happening, you can't run safe experiments. (2) Reasonable baseline stability — chaos on an already-unreliable system creates incidents. (3) Runbooks and recovery procedures — when an experiment goes wrong, you need a practiced response. Chaos readiness is a maturity milestone.",
  },
  {
    lesson_title: "Chaos Engineering & Production Testing",
    question: "What is blue-green deployment and how does it reduce risk when releasing new versions?",
    option_a: "Blue-green deployment colors the code by its age",
    option_b: "Blue-green maintains two identical production environments — 'blue' runs the current version, 'green' has the new version. Traffic switches instantly from blue to green at release time. If green has issues, traffic switches back to blue in seconds with zero data loss",
    option_c: "Blue-green deployment runs A/B tests between two UI variants",
    option_d: "Blue-green deployment is only used for database schema changes",
    answer: "B",
    explanation: "Blue-green benefits: zero-downtime deployment (instantaneous traffic switch), instant rollback (switch back to blue), full production testing on green before traffic switch (smoke tests, synthetic transactions). Limitation: requires 2x infrastructure cost and handling of in-flight requests during switch. QA's role: validate green environment before traffic shift.",
  },
];
