import type { QuizRow } from "../../quiz-types";

export const qaLeadershipAndTestManagementQuizzes: QuizRow[] = [
  {
    lesson_title: "QA Leadership & Test Management",
    question: "What is a test strategy document and what should it contain?",
    option_a: "A detailed list of all test cases for the project",
    option_b: "A high-level document defining the overall approach to quality — scope, test types, tools, environments, entry/exit criteria, risk assessment, roles, and how testing integrates with the development process",
    option_c: "A schedule of when each test will be executed",
    option_d: "A report of test results from the previous release",
    answer: "B",
    explanation: "Test strategy answers: what are we testing? How? With what tools and environments? What risks exist? When do we start/stop testing? Who is responsible? It guides the entire testing effort and is agreed with stakeholders before work begins. Unlike a test plan (project-specific), a strategy can apply across multiple projects.",
  },
  {
    lesson_title: "QA Leadership & Test Management",
    question: "It's release day and you have 3 critical bugs open, 2 with workarounds. How do you advise the product team on the release decision?",
    option_a: "Block the release — critical bugs must always be fixed before release",
    option_b: "Present the data: describe each critical bug's user impact, workaround feasibility, and affected user percentage — give a QA recommendation, but acknowledge the release decision belongs to the product owner with all information on the table",
    option_c: "Release without telling anyone about the critical bugs",
    option_d: "Close the bugs and re-open them as post-release issues",
    answer: "B",
    explanation: "QA's role: provide clear, objective data for the decision. 'Bug 1: checkout broken for 10% of users with Gift Cards (no workaround, high business impact). Bug 2: analytics event missing on mobile (workaround: desktop). My recommendation: hold for Bug 1, release with Bug 2 known issue.' The PO decides — QA informs.",
  },
  {
    lesson_title: "QA Leadership & Test Management",
    question: "What is risk-based testing and how do you prioritize which features to test most thoroughly?",
    option_a: "Testing only the features the developer marked as risky",
    option_b: "Prioritizing test effort based on impact × likelihood of failure — high-revenue features, recently changed code, complex integrations, and features with past defect history get deeper testing; stable, low-impact features get less",
    option_c: "Testing all features equally to avoid bias",
    option_d: "Testing features in order of development completion",
    answer: "B",
    explanation: "Risk matrix: Impact (high = checkout, auth, payment) × Probability (high = recently changed, complex, third-party integrated). High × High = most thorough testing. Low × Low = smoke test only. This is how QA teams scale: not everything can be tested thoroughly with finite time — focus on what matters most.",
  },
  {
    lesson_title: "QA Leadership & Test Management",
    question: "Your QA team is seen as a bottleneck that slows down releases. How do you address this perception?",
    option_a: "Accept that QA naturally slows development — it's unavoidable",
    option_b: "Shift QA left (involve earlier), automate regression coverage to remove manual bottlenecks, give developers faster feedback through CI, and make QA a collaborator throughout development rather than a gatekeeper at the end",
    option_c: "Remove manual testing from the process entirely",
    option_d: "Hire more QA engineers to handle the volume",
    answer: "B",
    explanation: "QA as bottleneck = QA acting as a gate at the end. Fix: (1) QA reviews requirements early (shift-left), (2) Automation runs in CI — regressions caught before QA, (3) QA tests in parallel with development, (4) Clear DoD so stories arrive at QA in a known state. QA's goal: quality embedded in the process, not inspected in at the end.",
  },
  {
    lesson_title: "QA Leadership & Test Management",
    question: "How do you measure the ROI of your QA team's work to justify headcount or tooling investment?",
    option_a: "Count the number of test cases written per quarter",
    option_b: "Measure: defect leakage rate reduction, cost of bugs found in QA vs. production, automation savings (hours saved per sprint), and mean time to detection — translate these into business impact (incidents avoided, customer retention, engineering hours saved)",
    option_c: "Track only the number of bugs found by QA",
    option_d: "Show the number of test runs completed per release",
    answer: "B",
    explanation: "QA ROI story: 'We reduced defect leakage from 8% to 2% — at our volume, that's 15 fewer production incidents per quarter. Each incident costs ~$20K in engineering response + customer impact. Automation saves 40 hours/sprint of manual regression. Our team cost is offset by ~$300K/quarter in avoided incidents.' Quantify quality.",
  },
  {
    lesson_title: "QA Leadership & Test Management",
    question: "A new feature is released without any automated tests. The developer says they'll 'add tests later.' How do you handle this as a QA lead?",
    option_a: "Accept it — tests can be added retroactively without issue",
    option_b: "Enforce automation as part of the Definition of Done — stories without tests should not be marked complete. 'Add tests later' becomes never. Raise this in retrospective and work with the team to make automation part of the acceptance criteria",
    option_c: "Write all the automated tests yourself to compensate",
    option_d: "Accept it but track it in a backlog and hope it gets prioritized",
    answer: "B",
    explanation: "Test debt compounds. 'Later' rarely comes. Fix systemically: (1) DoD includes 'automated tests written and passing', (2) PRs require tests — CI fails without them, (3) Sprint planning estimates include test writing time, (4) QA reviews test code in PR review. Prevention beats remediation.",
  },
  {
    lesson_title: "QA Leadership & Test Management",
    question: "What is test debt and how should a QA lead manage it?",
    option_a: "Test debt is the backlog of test cases that haven't been executed yet",
    option_b: "Test debt is the accumulated cost of skipped, broken, or missing tests — manage it by tracking it explicitly (broken tests as bugs, untested areas as stories), allocating sprint capacity for maintenance, and preventing accumulation with DoD requirements",
    option_c: "Test debt is the difference between manual and automated test counts",
    option_d: "Test debt is the number of tests added per sprint minus the tests removed",
    answer: "B",
    explanation: "Test debt is like code debt — invisible until it causes pain. Signs: 30% flaky tests, manual regression taking longer each release, automation suite nobody maintains. Manage: (1) Track broken tests as P2 bugs, (2) Allocate 20% of sprint capacity to test maintenance, (3) 'Boy scout rule' — fix tests you touch, (4) Retrospective: why did debt accumulate?",
  },
  {
    lesson_title: "QA Leadership & Test Management",
    question: "How do you build a QA strategy for a team migrating from quarterly releases to continuous delivery?",
    option_a: "Maintain the same manual testing approach but compress the timeline",
    option_b: "Prioritize automation: build CI regression suite first (covers 80% of release risk), define automated quality gates for the pipeline, establish monitoring/alerting for production quality, and shift QA role from manual tester to quality engineer",
    option_c: "Only test the features changed in each deployment",
    option_d: "Add more QA engineers to handle the increased release frequency",
    answer: "B",
    explanation: "CD QA transformation: (1) Automate regression — can't manually test every deployment. (2) Quality gates in CI — tests must pass before deployment proceeds. (3) Monitoring replaces some pre-deployment testing — fast feedback from production. (4) QA role shift: write automation, define quality standards, analyze production data — not run manual test cycles.",
  },
  {
    lesson_title: "QA Leadership & Test Management",
    question: "A product manager asks you to estimate testing effort for a major new feature before requirements are finalized. How do you respond?",
    option_a: "Refuse to estimate without complete requirements",
    option_b: "Provide a range estimate with explicit assumptions: 'Based on similar features, 3-5 days of testing effort, assuming clear acceptance criteria, API documentation, and test environment availability. Estimate will be refined during sprint planning when requirements are finalized'",
    option_c: "Give a fixed number to make the PM happy",
    option_d: "Say it will take as long as it takes and cannot be estimated",
    answer: "B",
    explanation: "Estimation under uncertainty: give a range, not a point estimate. State assumptions explicitly. 'If the feature requires database migration, add 1 day. If third-party integration is new, add 2 days for contract testing.' This gives the PM useful planning data while being honest about uncertainty — and protects QA from being held to an unrealistic number.",
  },
  {
    lesson_title: "QA Leadership & Test Management",
    question: "What is the 'shift-right' testing philosophy and what role does QA play in production monitoring?",
    option_a: "Shift-right means moving all testing to after the release date",
    option_b: "Shift-right extends quality activities into production — QA defines meaningful SLIs/SLOs, designs synthetic monitoring transactions, analyzes production error trends, and uses feature flags and canary deployments to validate quality with real traffic",
    option_c: "Shift-right is only relevant for DevOps teams, not QA",
    option_d: "Shift-right means QA tests the right side of the screen in production",
    answer: "B",
    explanation: "Production is the ultimate test environment. QA's shift-right contributions: (1) Define SLOs (99.9% uptime, p95 < 500ms) that trigger alerts. (2) Write synthetic monitoring transactions ('buy flow must complete in < 3s'). (3) Analyze production error rates to inform where testing coverage gaps exist. (4) Use feature flags to validate new features with a subset of users.",
  },
  {
    lesson_title: "QA Leadership & Test Management",
    question: "How do you handle a situation where developers consistently deliver features late to QA, leaving insufficient time for testing before release?",
    option_a: "Rush through testing to meet the release date regardless",
    option_b: "Address the process: raise in retrospective, propose QA involvement earlier (Three Amigos, PR reviews), establish a code freeze N days before release, and make testing time visible in sprint planning — if insufficient time remains, escalate the release risk explicitly",
    option_c: "Stay silent and do your best with the time available",
    option_d: "Block all late features from the release automatically",
    answer: "B",
    explanation: "Recurring late delivery is a process problem, not a QA problem. Systemic fixes: (1) Sprint planning: QA testing time is an explicit story point estimate, (2) Code freeze T-2 days before release, (3) QA tests stories as they complete (continuous testing), not all at end, (4) If QA time is consistently compressed, surface the risk in sprint reviews — make the problem visible to leadership.",
  },
  {
    lesson_title: "QA Leadership & Test Management",
    question: "What metrics would you use to measure the health of a QA team over time?",
    option_a: "Number of test cases written per QA engineer per week",
    option_b: "Defect leakage rate (escaped bugs), automation coverage percentage, test suite pass rate stability, MTTR for failing tests, and time-to-test-feedback in CI — these measure quality outcomes, not activity",
    option_c: "Number of bugs filed and number of test runs completed",
    option_d: "QA team velocity (story points) compared to development velocity",
    answer: "B",
    explanation: "Outcome metrics beat activity metrics. Leakage rate shows effectiveness. Automation coverage shows sustainability. Pass rate stability shows reliability. MTTR for tests shows maintenance health. CI feedback time shows development velocity impact. Together, they tell whether QA is actually improving quality — not whether QA is busy.",
  },
  {
    lesson_title: "QA Leadership & Test Management",
    question: "The engineering team wants to remove QA sign-off from the release process to deploy faster. How do you respond?",
    option_a: "Agree — modern teams don't need QA sign-off",
    option_b: "Discuss what sign-off represents: if it's a manual gate that delays 3 days, that's a valid automation problem to solve. If it's final quality confirmation, redesign it as a data-driven dashboard review (15 min) rather than a 3-day manual cycle. Quality standards shouldn't disappear — the ceremony around them should evolve",
    option_c: "Refuse — QA sign-off is mandatory regardless of delivery speed",
    option_d: "Agree but insist on post-release manual testing to compensate",
    answer: "B",
    explanation: "The question isn't 'sign-off yes/no' — it's 'what quality confidence do we need at release time?' If CI automation provides that confidence (test pass rate, coverage, no critical bugs), a manual gate IS waste. Replace with: automated quality gate dashboard that auto-approves or flags for human review. Quality standards remain; process becomes efficient.",
  },
  {
    lesson_title: "QA Leadership & Test Management",
    question: "How do you build a quality culture in a team that views QA as 'someone else's job'?",
    option_a: "Write all tests yourself to demonstrate what good looks like",
    option_b: "Involve developers in test design (Three Amigos), make quality metrics visible to all, celebrate bug prevention not just bug finding, run shared retrospectives on escaped defects, and make writing tests a recognized engineering skill — not a chore",
    option_c: "Enforce quality through management directives",
    option_d: "Accept the culture and work around it",
    answer: "B",
    explanation: "Quality culture shifts: (1) Shared responsibility — QA writes automation framework, developers write feature tests. (2) Visibility — post defect leakage metrics in team dashboard. (3) Blameless retrospectives — 'how did this bug escape?' not 'whose fault was it?' (4) Recognition — celebrate when automation catches a regression pre-production. Culture changes through repeated behaviors, not mandates.",
  },
  {
    lesson_title: "QA Leadership & Test Management",
    question: "What is a test closure report and when should it be produced?",
    option_a: "A report that closes all open test cases at sprint end",
    option_b: "A document produced at the end of a testing cycle summarizing: test execution results, defects found/resolved/deferred, coverage achieved, risks accepted, lessons learned, and a formal recommendation on release readiness — used to inform release decisions and future planning",
    option_c: "A report that marks all tests as complete regardless of results",
    option_d: "A Jira filter showing all closed bugs from the sprint",
    answer: "B",
    explanation: "Test closure report components: (1) Scope: what was tested vs. planned. (2) Results: pass/fail rate, defect counts by severity. (3) Risks: what wasn't tested and why (time, scope changes). (4) Open issues: known defects being released. (5) Recommendation: go/no-go with justification. It's the QA team's formal sign-off document with full transparency.",
  },
];
