import { toQuizRows } from "../supplement-utils";

export const advancedSupplementBanks = {
  "Test Automation Strategy": [
    ["What is the 'testing ice cream cone' an example of?", "An inverted test pyramid with many E2E tests and few unit tests", "The best testing strategy for startups", "A balanced approach to test distribution", "A type of exploratory testing", "A", "The ice cream cone is an anti-pattern — many slow, brittle E2E tests with few unit tests — the opposite of the efficient pyramid."],
    ["Which of the following has the HIGHEST ROI for automation?", "Recording one-time test scripts", "A regression test that runs 50+ times per year on stable features", "Automating rapidly changing UI features", "Testing exploratory scenarios", "B", "High-frequency, stable tests have positive ROI — the test pays for itself after a few runs."],
    ["What is the primary weakness of the test automation pyramid when inverted?", "Unit tests are too simple", "E2E tests are slow, brittle, and expensive — inverting wastes resources", "Integration tests are unreliable", "Too many tests run in parallel", "B", "The inverted pyramid (ice cream cone) multiplies maintenance costs and slows feedback."],
    ["When should a team NOT automate a test?", "When the feature is complex", "When the test will run fewer than 10 times over its lifetime", "When using Selenium", "When the test covers critical functionality", "B", "If the test doesn't run frequently enough, the automation effort exceeds the manual testing cost."],
    ["What is the key benefit of using Page Object Model (POM) for maintenance?", "It makes tests run faster", "It allows UI changes to be isolated to one place, reducing maintenance cost", "It eliminates the need for QA engineers", "It increases test coverage automatically", "B", "POM separates page knowledge from test logic — when UI changes, only the page object needs updating."],
    ["In the ROI calculation for test automation, what is the 'break-even point'?", "When the manual test cost exceeds automation setup cost", "When the test passes for the first time", "When developers stop writing unit tests", "When code is deployed to production", "A", "Break-even is when cumulative time saved by automation equals time spent building/maintaining the automation."],
    ["Which framework selection criterion is MOST critical for a mid-sized team?", "The framework with the most features", "Team skill and ability to maintain it without becoming dependent on one expert", "The cheapest option", "The newest tool on the market", "B", "A tool the team can actually learn, maintain, and fix is more valuable than a perfect tool that only one expert understands."],
    ["What does 'deterministic outcome' mean in automation ROI analysis?", "Tests that produce random results", "Tests where the same input always produces the same output", "Tests that depend on user behavior", "Tests that run overnight", "B", "Deterministic tests are reliable and automatable — the same conditions always produce the same result."],
    ["Why are high-business-impact features good candidates for automation?", "They require the least effort to test", "Catching bugs early reduces revenue loss and customer impact", "They don't have UI elements", "They never change", "B", "High-impact areas (checkout, login, payments) justify automation investment because bugs are costly."],
    ["What skill is most important for reducing test maintenance costs?", "Writing the most comprehensive tests possible", "Choosing stable, resistant-to-change locators and element selectors", "Automating every manual test", "Using the most advanced testing framework", "B", "Stable locators are the #1 factor in maintenance cost — brittle selectors cause constant fixes."],
    ["When evaluating framework fit, what should you prioritize?", "Compatibility with your development tech stack and team skills", "The framework with the best marketing", "The most expensive enterprise tool", "The framework used by your competitor", "A", "Tech stack fit and team expertise are more important than market hype or competitors' choices."],
  ],
  "Selenium WebDriver": [
    ["Which element locator strategy is most vulnerable to breaks during styling refactors?", "ID attribute", "CSS class name", "data-testid attribute", "Name attribute", "B", "CSS class names change frequently during styling updates, making class-based selectors brittle."],
    ["What is the primary difference between implicit and explicit waits?", "Implicit waits are faster", "Explicit waits target specific conditions on specific elements, while implicit applies globally", "Explicit waits are deprecated", "They are the same thing", "B", "Implicit wait slows all interactions; explicit wait is condition-based and only waits when needed."],
    ["Why is StaleElementReferenceException common in Selenium?", "Selenium has bugs", "The page changed or refreshed after finding the element but before interacting with it", "Incorrect import statements", "Browser incompatibility", "B", "When the DOM refreshes (navigation, AJAX reload, overlay), previously found elements become stale."],
    ["What does WebDriverWait do?", "Prevents the browser from loading", "Waits for a specific condition to be true, up to a maximum timeout", "Increases test execution speed", "Clears browser cache", "B", "WebDriverWait polls for a condition and only times out if the condition isn't met before the timeout."],
    ["In Selenium, what is a 'good' locator strategy priority order?", "XPath → CSS → ID → Name", "ID/data-testid → Name → CSS → XPath", "Text → XPath → CSS → ID", "Any strategy that finds the element", "B", "Use stable identifiers first, then more fragile ones only as fallback."],
    ["Why is coordinating with developers to add data-testid attributes valuable?", "It slows development", "It signals testing intent and provides stable, purpose-built locators that don't change with styling", "It increases page size", "It breaks production code", "B", "data-testid attributes exist specifically for testing and are unaffected by styling or layout changes."],
    ["What does ExpectedConditions.elementToBeClickable() verify?", "The element exists in the DOM", "The element is visible AND enabled AND not covered by overlays", "The element is in the correct color", "The element was clicked before", "B", "Clickable means visible, enabled, and not obscured — all conditions necessary for a successful click."],
    ["When should Fluent Wait be used instead of Explicit Wait?", "Always", "When an element appears intermittently or needs a custom polling interval", "Never", "Only for performance tests", "B", "Fluent wait is flexible — custom polling and ignored exceptions handle tricky timing scenarios."],
    ["What is the main limitation of finding elements by text (linkText, partialLinkText)?", "It doesn't work in Chrome", "Text changes due to localization, copy updates, or formatting changes", "It's too fast", "It only works for links", "B", "Text is fragile — any copy change breaks the locator."],
    ["In Selenium, what does driver.navigate().refresh() do?", "Closes the browser", "Reloads the current page", "Navigates to the home page", "Clears all cookies", "B", "Refresh reloads the page — useful for testing fresh state or retry scenarios."],
    ["Why should implicit waits be avoided in production test suites?", "They don't work", "They slow down all interactions unnecessarily, even when elements are already present", "They cause memory leaks", "They only work in headless mode", "B", "Implicit wait adds delay to every findElement call, slowing tests when most elements are already ready."],
    ["What is the best practice for handling elements that appear after JavaScript execution?", "Use Thread.sleep()", "Use explicit waits for the element to be visible", "Ignore the element", "Disable JavaScript", "B", "Explicit waits are the reliable way to handle asynchronous DOM changes."],
  ],
  "Cypress.io Modern Testing": [
    ["Why does Cypress automatically retry commands and assertions?", "Cypress has a bug", "Cypress runs in the browser and knows when elements are ready, animations complete, and XHR requests resolve", "To increase test execution time", "Cypress doesn't retry", "B", "Cypress's in-browser execution gives it visibility into application readiness — enabling smart retries."],
    ["What is the Time Travel Debugger in Cypress?", "A tool for scheduling tests", "A feature that lets you click on any step and see a DOM snapshot of that moment", "A way to run tests in the future", "A browser cache tool", "B", "Time Travel lets you inspect the exact page state at any test step — invaluable for debugging failures."],
    ["What does cy.wait('@alias') do?", "Waits for a fixed time period", "Waits for an intercepted API request with that alias to complete", "Stops test execution", "Clears the browser cache", "B", "cy.wait('@alias') synchronizes the test with network requests — no guessing about API timing."],
    ["In Cypress, which selector strategy is preferred over CSS class names?", "XPath", "data-testid", "CSS class names are always best", "Element ID only", "B", "data-testid is Cypress's recommended selector — stable and unaffected by styling changes."],
    ["Why is Cypress recommended for modern JavaScript applications?", "It's the oldest framework", "Cypress runs in the browser, giving deep visibility into async state, network, and JavaScript execution", "It doesn't support APIs", "It only works with React", "B", "In-browser execution is Cypress's key advantage for modern, async-heavy applications."],
    ["What happens when a Cypress command fails?", "The entire test suite stops", "The test fails and displays a detailed error with the exact DOM state", "Cypress automatically fixes the error", "The command is skipped", "B", "Cypress's error messages are exceptionally clear, showing exactly what went wrong and the page state."],
    ["How does Cypress handle animations and transitions automatically?", "It doesn't — you must disable them", "Cypress automatically waits for animations to complete before interacting", "It speeds up animations", "Animations are unsupported", "B", "Cypress waits for animation completion — a major source of flakiness eliminated."],
    ["What is the advantage of Cypress's cy.intercept() over selenium mocking?", "It doesn't exist", "Cypress can stub/spy on network requests at runtime with full browser context", "It's slower than manual mocking", "It only works for GET requests", "B", "cy.intercept() lets you control API responses dynamically — powerful for edge case testing."],
    ["Can Cypress test across multiple browser tabs?", "Yes, unlimited tabs", "No, Cypress tests single-tab workflows by design", "Yes, but it's not recommended", "Only in headless mode", "B", "Cypress focuses on single-tab testing — multi-tab scenarios are rare in modern SPAs."],
    ["What does cy.fixture() do?", "It breaks the test", "Loads test data from JSON files in the fixtures folder", "Compiles the code", "Uploads files to the server", "B", "Fixtures provide consistent, reusable test data without hardcoding."],
    ["Why should tests use data-testid instead of class selectors in Cypress?", "Classes are faster", "Classes change with styling updates; data-testid is stable and testing-specific", "Cypress doesn't support classes", "It doesn't matter", "B", "Class-based selectors break whenever a designer updates CSS — data-testid doesn't."],
    ["What is the benefit of Cypress's developer-first approach?", "It runs slower", "Excellent error messages, fast feedback, and live reload make debugging and development faster", "It requires more code", "It doesn't help development", "B", "Cypress's UX is designed to save developers time — fast feedback and clear errors = faster development."],
  ],
  "Playwright for E2E Testing": [
    ["What is Playwright's main advantage for cross-browser testing?", "It only supports Chrome", "It tests real Chromium, Firefox, AND WebKit browsers from a single test", "It requires different test code for each browser", "It doesn't support cross-browser", "B", "Playwright tests the same code against three browser engines — true coverage without duplication."],
    ["How does Playwright's auto-wait feature work?", "It doesn't auto-wait", "Playwright waits for elements to be visible, enabled, stable, and attached before interacting", "It waits a fixed time", "Auto-wait is optional", "B", "Playwright's auto-wait eliminates most manual wait logic — elements are ready before interaction."],
    ["What can you observe in Playwright's Trace Viewer?", "Only test names", "Screenshots at every step, network requests, console logs, and DOM state", "Only performance metrics", "Only error messages", "B", "Trace Viewer captures comprehensive execution data — everything you need to debug CI failures locally."],
    ["What is the advantage of Playwright's parallel execution?", "Tests can't run in parallel with Playwright", "Tests run across multiple browsers and workers simultaneously — dramatic speed improvement", "Parallel execution is slower", "It only affects unit tests", "B", "Playwright's parallel design turns 20-minute test runs into 5-minute runs."],
    ["Which Playwright locator strategy is most recommended?", "XPath", "Role-based locators (getByRole) — semantic and accessible", "CSS selectors only", "Text-based only", "B", "Role locators are semantic, user-facing, and align with accessibility best practices."],
    ["What is npx playwright codegen useful for?", "Deleting tests", "Generating test code by recording browser interactions", "Deploying to production", "Analyzing test results", "B", "Codegen is a quick way to scaffold new tests — record interactions, get generated code."],
    ["How does Playwright handle authentication in tests?", "You must hardcode credentials", "Playwright supports context reuse and session storage for efficient authenticated test setup", "Authentication is unsupported", "You must login for every test", "B", "Context reuse lets multiple tests share authenticated sessions — faster and more realistic."],
    ["What does expect(page).toHaveURL() verify?", "The page title", "The current URL matches the expected pattern", "The page is loaded", "The server is responding", "B", "toHaveURL waits for URL navigation — reliable for testing redirects."],
    ["In Playwright, what is a 'test context'?", "A code comment", "An isolated browser session — cookies, cache, storage separate from other tests", "The test file name", "A debug mode", "B", "Contexts are isolated sessions — tests don't interfere with each other's state."],
    ["Why does Playwright support WebKit (Safari) when browsers don't?", "It doesn't", "Playwright uses WebKit engine to simulate Safari behavior without needing macOS", "Firefox also uses WebKit", "WebKit is proprietary", "B", "WebKit support gives CI/CD the ability to test Safari-like behavior without Apple hardware."],
    ["What is the purpose of playwright.config.ts?", "It stores test data", "It configures browsers, timeouts, parallel workers, and reporting", "It runs the tests", "It's optional", "B", "The config file is where you specify test behavior — workers, retries, browsers, reporters."],
    ["How does Playwright differ from Cypress for component testing?", "Playwright only does E2E", "Playwright supports component testing with a similar API to E2E tests", "Cypress is better for components", "Both are identical", "B", "Playwright's component testing uses the same commands as E2E — unified testing."],
  ],
  "API Automation & Contract Testing": [
    ["Why are API tests preferred over UI tests for regression suites?", "They're not", "API tests are faster, more stable, and easier to maintain than UI tests", "UI tests are always better", "API tests don't work", "B", "API tests execute in milliseconds, don't break on UI changes, and provide direct business logic verification."],
    ["What is the primary benefit of contract testing?", "It makes UI tests faster", "It verifies both consumer and provider agree on API contracts — preventing integration breakage", "It replaces unit tests", "It has no benefits", "B", "Contract testing prevents services from silently breaking each other when APIs evolve independently."],
    ["In Supertest, what does expect(response.status).toBe(201) verify?", "The response time", "The HTTP status code is 201 Created", "The response body", "The content type", "B", "Status code verification ensures the API behaves correctly for each scenario."],
    ["Why should test data include unique identifiers like timestamps or UUIDs?", "To make tests slower", "To prevent data collisions when parallel tests create the same data", "Unique IDs are unnecessary", "To break the tests", "B", "Unique IDs prevent collisions in parallel test runs — different jobs won't conflict."],
    ["What is an API test's most valuable feature compared to UI tests?", "It's slower", "Direct verification of contracts, status codes, and data without browser complexity", "It's harder to maintain", "It can't test business logic", "B", "APIs have explicit contracts — test them directly without the variability of UI testing."],
    ["Why should sensitive fields (password, SSN) NOT appear in API responses?", "To make tests faster", "Exposing sensitive data violates security and privacy regulations", "They should always be in responses", "It doesn't matter", "B", "Sensitive fields should be hashed or omitted entirely — never returned to clients."],
    ["What does a 403 status code indicate in an API test?", "Server error", "Forbidden — the user is authenticated but not authorized for this resource", "Not found", "Redirect", "B", "403 is the correct response when access is denied — functionally different from 401 (unauthenticated)."],
    ["In API testing, what is the purpose of checking response schema?", "To waste time", "To verify the response structure matches the contract — preventing breaking changes", "Schemas are optional", "It has no purpose", "B", "Schema validation catches breaking changes early — when a new required field appears unexpectedly."],
    ["Why should API tests clean up after themselves?", "Tests don't need cleanup", "To prevent data pollution and ensure parallel tests don't interfere", "Cleanup is slow", "The database cleans itself", "B", "Cleanup prevents orphaned test data from polluting the database and confusing future test runs."],
    ["What is a 'test token' in API authentication?", "A reward for passing tests", "A special auth credential used only in test environments for automated login", "Something that doesn't exist", "A security risk", "B", "Test tokens are typically long-lived, easily-generated credentials for CI automation."],
    ["Why should you test both success and error paths in APIs?", "Error paths don't matter", "Users encounter both happy paths and errors — both need verification", "Success paths are enough", "Only successful tests count", "B", "Error handling is critical — incorrect error responses confuse users and expose internal details."],
    ["What does a 409 Conflict status indicate?", "The server crashed", "A duplicate resource or constraint violation (e.g., email already exists)", "The page isn't found", "Unauthorized access", "B", "409 signals resource conflicts — important for testing unique constraints."],
    ["Why would you stub an external API in contract tests?", "Stubbing is cheating", "To ensure tests focus on your API contract, not external service behavior", "External APIs are always available", "Stubbing makes tests fail", "B", "Stubbing isolates your service from external dependencies — faster, more reliable tests."],
    ["What should you validate about API response times in tests?", "Response time doesn't matter", "Verify responses meet SLA expectations (e.g., p95 < 500ms) to catch performance regressions", "Response time is random", "Slow responses are fine", "B", "Performance expectations should be part of your contract — test them."],
    ["Why is testing authorization separate from authentication in APIs?", "Authorization is unnecessary", "Authentication (identity) and authorization (permissions) are different — both must work correctly", "They're the same thing", "Authorization is automatic", "B", "A user might be authenticated but lack permissions — these are separate security layers."],
  ],
  "CI/CD Pipeline Integration": [
    ["What is the ideal test execution order in a CI pipeline?", "Slowest tests first", "Fast lint/typecheck → unit → integration → E2E (fail-fast strategy)", "E2E tests first", "Random order", "B", "Running fast checks first saves compute time when failures are caught early."],
    ["Why should E2E tests run on pull requests rather than just after merge?", "E2E tests aren't important", "Running on PRs prevents broken code from merging in the first place", "Tests are too slow for PRs", "Tests should only run on main", "B", "PR testing (shift-left) catches issues before they enter production branches."],
    ["What is a 'quality gate' in practice?", "A manual approval step", "An automated condition that must pass before code can merge or deploy (e.g., all tests pass, coverage > 80%)", "A security review", "A meeting", "B", "Quality gates enforce standards automatically — no manual discretion needed."],
    ["Why should you cache dependencies in CI (npm, Maven)?", "Caching doesn't help", "To avoid downloading the same packages repeatedly — dramatically faster builds", "Caching slows things down", "Only on weekends", "B", "Dependency caching can cut 2 minutes off every build — significant when running hundreds of builds/day."],
    ["What is the benefit of running tests across multiple CI workers?", "More workers means slower tests", "Tests run in parallel on different machines — a 20-minute suite becomes 5 minutes", "Parallel isn't necessary", "One worker is most efficient", "B", "Parallelism is one of the biggest speed improvements in CI — dramatically reduces developer wait time."],
    ["Why should flaky tests be fixed rather than retried?", "Retries solve flakiness", "Retries hide real bugs — fixing the root cause is essential for reliable pipelines", "Flaky tests are fine", "Retrying is better than fixing", "B", "Retrying masks reliability problems — root cause analysis and fixes are necessary."],
    ["What does a 'stage dependency' in CI mean?", "Stages are independent", "Stage 2 only runs if Stage 1 passed — preventing wasted compute on broken code", "All stages run simultaneously", "Dependencies are bad", "B", "Stage dependencies implement fail-fast — no point running expensive tests if fast checks already failed."],
    ["Why should you upload test reports as CI artifacts?", "Reports are unnecessary", "To preserve test history and debug CI failures — artifacts survive after the job completes", "Reports are stored forever anyway", "Artifacts slow down CI", "B", "Artifacts let you debug failures weeks later without re-running — critical for investigation."],
    ["What is a 'build matrix' in CI?", "A mathematical concept", "Testing the same code against multiple OS/Node versions simultaneously", "A single test run", "A reporting feature", "B", "Build matrices catch environment-specific bugs — different platforms, runtimes, databases."],
    ["Why should secrets (API keys, passwords) NOT be in your test code?", "Secrets improve security", "Storing secrets in code exposes them in version control and logs", "It's fine to hardcode secrets", "Secrets are optional", "B", "Secrets must be injected at runtime via CI secrets, never committed to version control."],
    ["What is 'continuous deployment' vs. 'continuous delivery'?", "They're the same", "Continuous delivery = ready to deploy; continuous deployment = automatically deploys to production", "Deployment is always continuous", "There's no difference", "B", "CD can mean either — continuous delivery requires manual approval, continuous deployment is automatic."],
    ["Why should you run security scans in CI?", "Security isn't important in CI", "To detect vulnerabilities in dependencies and code early — before they reach production", "Security scanning slows builds", "Security is a manual process", "B", "Automated security scanning catches common vulnerabilities — faster and cheaper than manual review."],
  ],
  "Performance Testing with k6": [
    ["In k6, what does a Virtual User (VU) represent?", "A manual tester", "A simulated concurrent user executing your test script", "A test machine", "A server instance", "B", "VUs are k6's abstraction for concurrent load — each VU runs your script repeatedly."],
    ["What is the difference between p(95) and p(99) in k6 metrics?", "They're the same", "p(95) = 95% of requests faster than this value; p(99) = even stricter", "p(99) is always faster", "They measure different things", "B", "Percentiles measure SLA compliance — p(99) is stricter, more expensive to meet."],
    ["Why should thresholds be defined in k6 scripts rather than evaluated after?", "Thresholds in scripts are slower", "Thresholds in scripts enable CI quality gates — tests fail automatically if metrics breached", "Thresholds are optional", "Post-test evaluation is better", "B", "Script-based thresholds integrate with CI/CD — automatic pass/fail on performance criteria."],
    ["What does 'ramping up' VUs do in k6?", "Deletes VUs", "Gradually increases concurrent users to simulate realistic traffic growth", "Runs tests faster", "Reduces test duration", "B", "Ramp-up simulates real-world traffic patterns — not an instant spike."],
    ["Why is k6 better for CI than browser-based tools?", "It's not", "k6 is lightweight, outputs JSON metrics, and integrates natively with CI — no browser overhead", "Browser tools are always better", "CI is browser-specific", "B", "k6's design specifically targets CI environments — lightweight, fast, metric-focused."],
    ["What is a k6 'check' vs. an 'assertion'?", "They're identical", "Checks are custom validations that don't fail the test; assertions do", "Checks don't exist", "Assertions are for unit tests", "B", "Checks record pass/fail stats; assertions stop the test — use checks for non-critical validations."],
    ["Why might p(95) be more useful than average latency?", "Average is useless", "Average hides poor performance for some users — p(95) reflects the experience of most users", "p(95) is always better", "Average is better", "B", "A 50ms average with 1% of requests at 5s is bad — p(95) catches this."],
    ["In k6, what is a 'group'?", "Multiple tests", "A logical section of your test script for organizing metrics and improving readability", "A user group", "A test category", "B", "Groups organize your script into logical sections — each group has its own metrics."],
    ["Why should you use custom metrics in k6?", "Custom metrics don't work", "To track business-specific measurements (successful orders, login errors) not covered by built-in metrics", "Built-in metrics are always sufficient", "Custom metrics slow tests", "B", "Custom metrics bridge technical performance and business outcomes."],
    ["What happens when a k6 test breaches a threshold?", "The test continues normally", "The test fails — important for preventing deployment of degraded performance", "Thresholds are warnings only", "Nothing happens", "B", "Threshold breaches should block deployment — they're the CI quality gate."],
    ["Why is 'think time' (sleep between requests) important in k6?", "It's unnecessary", "Think time simulates realistic user behavior — users don't request continuously", "More requests per VU is always better", "Think time slows tests", "B", "Without think time, k6 generates unrealistic traffic — continuous requests from each VU."],
    ["In k6, what is the 'ramp-down' phase?", "A bug in the script", "Gradually reducing VUs at the end to observe system recovery", "Immediately stopping VUs", "The final test report", "B", "Ramp-down reveals how the system recovers when load decreases — important for resilience."],
  ],
  "Security Testing & OWASP Top 10": [
    ["What is Broken Access Control in simple terms?", "A bug in authentication", "Users accessing resources or data they shouldn't have permission to access", "Incorrect database structure", "Server misconfiguration", "B", "Access control = authorization — who is allowed to do what. Broken AC = wrong people get access."],
    ["What is an IDOR vulnerability in practice?", "A database error", "Changing a user ID in the URL to access another user's data (e.g., /api/profile/123 → /api/profile/456)", "An API timeout", "Missing HTTPS", "B", "IDOR is the easiest vulnerability to test — just try changing IDs and see if access is denied."],
    ["Why is parameterized query the correct defense against SQL injection?", "It's slower", "Parameterized queries separate SQL code from data — the database engine never interprets user input as code", "Parameterized queries don't prevent injection", "Input validation is enough", "B", "Parameterization is the database-level defense — it's bulletproof."],
    ["What should happen when a user submits malicious input like <script>alert('XSS')</script>?", "The script executes", "The input is rejected (400) or the tags are escaped in output (harmless HTML)", "The user is banned", "The page crashes", "B", "XSS prevention = either reject the input or escape it before displaying."],
    ["Why is storing passwords as plain text a critical vulnerability?", "It's not a problem", "If the database is breached, attackers get all passwords immediately", "Plain text is fast", "Passwords are encrypted automatically", "B", "Database breaches happen — plaintext passwords are a disaster. Use bcrypt/argon2."],
    ["What does 'HTTPOnly' flag on cookies prevent?", "The cookie from working", "JavaScript from reading the cookie (protects against XSS token theft)", "Cookie expiration", "HTTPS requirements", "B", "HTTPOnly cookies can't be accessed by JavaScript — XSS attackers can't steal them."],
    ["In security testing, why test error messages?", "Error messages don't matter", "Error messages should never reveal internal details (database errors, file paths, stack traces)", "Detailed errors help debugging", "Error messages are security-neutral", "B", "Verbose error messages leak system information to attackers — a reconnaissance vector."],
    ["What is CSRF (Cross-Site Request Forgery)?", "A database issue", "Tricking an authenticated user into performing unintended actions on another site", "A malware type", "A network protocol", "B", "CSRF exploits user trust — the browser automatically sends cookies, but the user didn't intend the request."],
    ["Why should you test rate limiting?", "Rate limiting isn't security", "To verify APIs reject excessive requests — preventing brute force attacks and DoS", "Rate limiting slows legitimate users", "Rate limiting is optional", "B", "Rate limiting stops attackers from trying millions of passwords rapidly."],
    ["What is input validation's role in security?", "It doesn't help", "First line of defense — reject obviously malicious input before it reaches processing logic", "Input validation isn't important", "Only backend validation matters", "B", "Frontend validation provides UX feedback; backend validation is the security boundary."],
    ["Why should Secrets (API keys, tokens) never be in version control?", "Secrets are safe in public repos", "Anyone with git history access gets permanent credentials — impossible to rotate safely", "Secrets should be versioned", "Version control is private anyway", "B", "Once committed, git history keeps secrets forever — even if deleted, they're recoverable."],
    ["What does 'secure by default' mean in security testing?", "Security is optional", "The most secure option should be the default behavior, not something users must opt into", "Defaults should be permissive", "Security is always optional", "B", "Insecure defaults trap users — secure by default protects everyone."],
  ],
  "BDD with Cucumber & Gherkin": [
    ["What is the 'Three Amigos' in BDD?", "A movie reference", "Business Analyst, Developer, and QA writing scenarios together to prevent ambiguity", "Three test frameworks", "A testing technique", "B", "Three Amigos align on concrete examples before coding — eliminating misunderstanding."],
    ["Why is 'Background' useful in Gherkin scenarios?", "It's not necessary", "Background sets up common preconditions once instead of repeating them in every scenario", "Background is a comment", "Background slows tests", "B", "Background eliminates repetitive Given steps — DRY for Gherkin."],
    ["What does 'Scenario Outline' enable in Gherkin?", "Multiple test files", "Running the same scenario with multiple data sets from an Examples table", "Skipping scenarios", "Running tests in parallel", "B", "Scenario Outline = data-driven testing in Gherkin."],
    ["Why are Step Definitions written in code?", "Gherkin can't be automated", "Step Definitions bridge plain-English Gherkin to actual test automation code", "They're optional", "Gherkin runs directly", "B", "Step Definitions are the implementation layer — Gherkin is just the specification."],
    ["What is a 'feature' in Gherkin?", "A new code feature", "A high-level business capability described with multiple scenarios", "A single test case", "A type of assertion", "B", "One Feature file = one business capability with multiple scenarios."],
    ["Why should Gherkin scenarios be written before development?", "They shouldn't be", "Pre-writing scenarios forces agreement on behavior — the specification becomes the test", "Tests are always after development", "Gherkin is for documentation", "B", "BDD's power is specification before code — tests drive development."],
    ["What is a 'tag' in Gherkin?", "A HTML tag", "A label for scenarios enabling selective test execution (e.g., @smoke, @security)", "A type of step", "A test category", "B", "Tags let you run subsets of scenarios — all smoke tests, all security tests, etc."],
    ["Why should step definitions be reusable?", "Reuse is unnecessary", "Reusable steps reduce duplication and maintenance — scenarios share common logic", "Unique steps for each scenario", "Reuse slows tests", "B", "Well-written step definitions are used across multiple scenarios."],
    ["What does 'And' do in Gherkin?", "It starts a new scenario", "It continues the previous step type (Given/When/Then) without repeating the keyword", "And is optional", "And combines scenarios", "B", "And is syntactic sugar — 'And' continues the previous keyword."],
    ["Why is Gherkin valuable to non-technical stakeholders?", "It's not", "Gherkin is plain English — business people can read and verify scenarios without technical knowledge", "Stakeholders ignore Gherkin", "Gherkin is for developers", "B", "Gherkin enables stakeholders to participate in test specification."],
    ["What is a 'hook' in Cucumber?", "A fishing tool", "Code that runs before/after scenarios for setup/teardown (login, database seeding)", "A step definition", "A test assertion", "B", "Hooks handle test setup/cleanup without polluting scenario steps."],
    ["Why is BDD alignment important?", "Alignment isn't important", "Miscommunication is the #1 cause of requirements bugs — BDD prevents it through shared examples", "Everyone understands requirements automatically", "BDD is just testing", "B", "BDD makes requirements explicit through concrete scenarios — no ambiguity."],
  ],
  "Test Data Management": [
    ["What is 'test data pollution'?", "Test data that's slightly dirty", "Leftover data from previous test runs that interferes with current tests or database performance", "Outdated test data", "Data that contains typos", "B", "Pollution accumulates over time — thousands of orphaned test records slow queries and confuse debugging."],
    ["Why should test data use timestamps or UUIDs for uniqueness?", "Hardcoded IDs are fine", "To prevent collisions when parallel tests run simultaneously — each test gets unique data", "Uniqueness isn't necessary", "Timestamps slow tests", "B", "Without uniqueness, parallel test 1 and test 2 might both try to create 'test@example.com' — conflict."],
    ["What is a test data factory?", "A physical location", "A function that generates fresh, unique test data for each test run", "A database", "A manual process", "B", "Factories programmatically generate test data — consistent, collision-free, and maintainable."],
    ["Why should sensitive data (real customer info) never be in test environments?", "It's fine to have real data", "It violates privacy regulations (GDPR, CCPA) — real personal data shouldn't be accessible to developers", "Test environments need real data", "Privacy doesn't apply to testing", "B", "Real user data in test environments is a compliance violation — developers see private information."],
    ["What is 'data seeding' in tests?", "Planting seeds literally", "Pre-populating a test database with known reference data so tests start from a predictable state", "Randomly generating data", "Data backup", "B", "Seeding ensures every test starts with consistent reference data."],
    ["Why should tests clean up test data after running?", "Cleanup is wasteful", "To prevent orphaned data from accumulating and polluting the database", "Databases self-clean", "Cleanup is optional", "B", "Cleanup prevents pollution — essential for sustainable test suites."],
    ["What is the difference between factories and fixtures?", "They're the same", "Factories generate dynamic data; fixtures are static pre-created test data", "Fixtures are code, factories are files", "Factories generate files", "B", "Use factories for unique-per-test data; fixtures for static reference data."],
    ["In test data management, why should you avoid using production IDs?", "Production IDs aren't real", "Using production IDs might accidentally affect production — test environments should be isolated", "Test data should match production", "There's no risk", "B", "Production IDs create risk — test environments must be isolated from production."],
    ["What is 'test data masking'?", "Hiding test data visually", "Replacing sensitive data (SSN, credit card) with fake but realistic-looking values", "Deleting data", "Encryption", "B", "Masking lets you use production-like data shapes without exposing real sensitive information."],
    ["Why should test contexts be isolated from each other?", "Isolation is unnecessary", "So one test's data changes don't affect another test — essential for parallel testing", "Shared data is more efficient", "Isolation slows tests", "B", "Isolated contexts enable reliable parallel testing — tests never interfere."],
    ["What is the risk of hardcoding test data?", "No risk", "Hardcoded data breaks when pre-conditions change, and conflicts occur in parallel runs", "Hardcoding is best practice", "Hardcoded data is unique", "B", "Hardcoding creates brittleness — factories and dynamic data are better."],
    ["Why might you use database transactions in test teardown?", "Transactions are unnecessary", "Wrapping tests in transactions rolls back all data changes after the test — instant cleanup", "Transactions are slow", "Manual cleanup is better", "B", "Transactional rollback is the fastest cleanup — automatic and complete."],
  ],
  "Chaos Engineering & Production Testing": [
    ["What is the core principle of chaos engineering?", "Break things randomly", "Intentionally inject failures in controlled ways to discover weaknesses before they happen in production", "Chaos is uncontrolled", "Testing never involves breaking", "B", "Controlled chaos reveals failures — better to find them yourself than during an outage."],
    ["Why is staging insufficient for validating production resilience?", "Staging is perfect", "Staging lacks production scale, real dependencies, and configuration drift — chaos testing fills this gap", "Production should never be tested", "Staging matches production exactly", "B", "Staging is simplified — production has scale, real APIs, and real infrastructure variables."],
    ["What does 'steady state' mean in chaos experiments?", "A random baseline", "The measurable normal behavior before introducing a failure", "A failed state", "The final test result", "B", "You need a baseline to measure degradation — steady state defines normal."],
    ["In a chaos experiment, what does 'blast radius' control?", "How long the experiment runs", "The scope/size of the failure — start small and expand gradually to minimize risk", "The number of VUs", "How many tests run", "B", "Small blast radius = minimal risk — start with one pod, not the entire cluster."],
    ["Why are chaos experiments run during business hours at some companies?", "They're not", "To catch failures when context switches and alerts are active — revealing real-world response", "Business hours have better networks", "It doesn't matter when you run them", "B", "Chaos during business hours = on-call engineers alert faster, catch issues earlier."],
    ["What is Chaos Monkey?", "An actual monkey", "Netflix's original chaos tool — randomly terminates EC2 instances to force resilience", "A testing framework", "A deployment tool", "B", "Chaos Monkey inspired the entire chaos engineering discipline."],
    ["In chaos engineering, what does 'circuit breaker' prevent?", "Electrical circuit trips", "Cascade failures — when one service fails, circuit breaker stops it from taking down dependent services", "User access", "Data corruption", "B", "Circuit breakers are the defense against cascading failures."],
    ["Why would you inject latency between services in chaos tests?", "Latency doesn't matter", "To verify systems handle slow dependencies gracefully — timeouts work, retries work, fallbacks work", "Latency is always bad", "You shouldn't test latency", "B", "Real-world networks have latency — tests must account for it."],
    ["What does observability mean in chaos engineering?", "Just looking at things", "The ability to understand system behavior through metrics, logs, traces — essential for analyzing chaos results", "Observation doesn't help", "Observability is optional", "B", "Without observability, you can't tell if chaos revealed a real weakness or just noise."],
    ["In chaos experiments, when should you start with small blast radius?", "Always use large radius", "Start small to minimize risk and learn incrementally — expand only after success", "Blast radius doesn't matter", "Large radius is always faster", "B", "Safety first — verify your hypothesis on 1 pod before killing 10."],
    ["Why test resilience with real production traffic?", "Production traffic isn't real", "Real users reveal edge cases and failure modes labs never discover — true validation", "Labs are sufficient", "Production traffic is random", "B", "Production exposes real-world conditions labs can't replicate."],
    ["What is 'synthetic monitoring' in chaos engineering?", "Fake monitoring", "Lightweight, safe checks running continuously in production to verify user-facing functionality", "Monitoring isn't needed", "Synthetic = unrealistic", "B", "Synthetic checks catch real issues without impacting production."],
  ],
  "QA Leadership & Test Management": [
    ["What is 'Defect Leakage' in QA metrics?", "Bugs that aren't serious", "Bugs that escape to production that QA should have caught — a key quality metric", "Defects that are slow to fix", "All bugs are leakage", "B", "Leakage = (production bugs / total bugs) × 100 — lower is better."],
    ["What does 'Mean Time to Detect' (MTTD) measure?", "How long tests take to run", "Average time from a bug being introduced to QA discovering it", "Time to fix a bug", "Test execution time", "B", "Lower MTTD = bugs caught earlier = cheaper fixes."],
    ["Why should QA leaders translate metrics into business language?", "Executives understand technical metrics", "Executives care about business outcomes (revenue, customer impact, time/cost) — not raw test numbers", "Business impact is irrelevant", "Metrics are self-explanatory", "B", "Translate 'prevented 3 critical bugs' into '~40 hours of incident response saved'."],
    ["What is a QA OKR?", "A type of bug severity", "Objective & Key Results — goal-setting framework with measurable outcomes (e.g., reduce leakage to < 2%)", "A test case category", "A metric aggregation", "B", "OKRs align QA team goals with business priorities."],
    ["When building a QA team, which trait predicts strong performance?", "Years of experience", "Curiosity — engineers who naturally ask 'what if?' discover bugs others miss", "Coding speed", "Tool expertise", "B", "Curiosity drives quality insights — the best QA engineers wonder about edge cases."],
    ["What is 'risk-based test planning'?", "Avoiding risky features", "Allocating test effort proportional to business risk — deep testing for high-impact features", "All features get equal testing", "Risk shouldn't affect planning", "B", "Not all features deserve equal testing depth — focus on high-risk areas."],
    ["In QA career development, what are the two tracks post-Senior?", "Only management exists", "Technical (Principal QA) and management (QA Manager) — both are valid senior careers", "QA has no growth paths", "Everyone becomes a manager", "B", "Engineers can pursue deep technical expertise OR people management."],
    ["How should severity levels be defined for defects?", "Subjectively by tester", "Standardized definitions (S1=data loss/security, S4=cosmetic) prevent priority debates", "All bugs are equally important", "Severity doesn't matter", "B", "Clear severity definitions make prioritization objective and consistent."],
    ["Why should QA teams participate in architecture/design discussions?", "QA just tests afterward", "Early participation identifies testability issues and risks before expensive rework", "QA adds no value to design", "Testing happens after delivery", "B", "Shift-left means QA influences design — catching testability issues early."],
    ["What is a 'QA escalation policy'?", "Unnecessary paperwork", "Clear rules for when and how issues go up the chain — prevents ad-hoc escalation confusion", "Problems aren't escalated", "Escalation is optional", "B", "Clear escalation policies ensure critical issues reach the right decision-maker."],
    ["Why measure 'test coverage' rather than just running tests?", "Coverage isn't useful", "Coverage shows what code paths are tested — areas with low coverage have hidden bugs", "All coverage metrics are bad", "Coverage is achieved automatically", "B", "Coverage gaps are bug hotspots — unmeasured coverage is a blind spot."],
    ["In QA leadership, what does 'shift-left' mean?", "Moving offices to the left", "Pushing testing earlier in the lifecycle — test during design/development, not just after", "Left isn't relevant", "Shift-left is a trend", "B", "Shift-left catches bugs when they're cheapest to fix — early detection matters."],
  ],
} as const;

const advancedBalancedBanks = {
  ...advancedSupplementBanks,
  "Security Testing & OWASP Top 10": advancedSupplementBanks[
    "Security Testing & OWASP Top 10"
  ].slice(0, -1),
  "BDD with Cucumber & Gherkin": advancedSupplementBanks["BDD with Cucumber & Gherkin"].slice(
    0,
    -1
  ),
  "QA Leadership & Test Management": advancedSupplementBanks[
    "QA Leadership & Test Management"
  ].slice(0, -1),
};

const advancedTopUpBanks = {
  "Test Data Management": [
    [
      "Why should test data strategies include cleanup ownership?",
      "To increase manual effort",
      "To prevent long-term data pollution and unstable tests",
      "To skip seed scripts",
      "To remove fixtures",
      "B",
      "Clear ownership ensures stale test data is removed consistently.",
    ],
    [
      "PII masking in test environments is primarily for:",
      "Performance tuning",
      "Privacy/compliance and reducing exposure risk",
      "Schema migration speed",
      "Visual testing",
      "B",
      "Masked datasets preserve realism while protecting sensitive information.",
    ],
    [
      "Factory-generated test data helps parallel runs by:",
      "Reducing uniqueness",
      "Avoiding collisions with deterministic unique records",
      "Removing teardown",
      "Disabling validation",
      "B",
      "Unique records reduce race conditions and cross-test interference.",
    ],
  ],
  "Chaos Engineering & Production Testing": [
    [
      "A safe chaos experiment must include:",
      "No rollback path",
      "Abort conditions and rollback criteria",
      "Only high blast radius",
      "No observability",
      "B",
      "Safety guards prevent uncontrolled impact during failure injection.",
    ],
    [
      "Why inject network faults (latency/drop) in resilience testing?",
      "To test UI colors",
      "To validate timeout/retry/fallback behavior",
      "To bypass monitoring",
      "To skip load tests",
      "B",
      "Network chaos reveals whether resilience patterns work as designed.",
    ],
    [
      "Synthetic checks in production are valuable because they:",
      "Replace observability",
      "Provide continuous low-risk validation of critical flows",
      "Disable alerts",
      "Guarantee zero incidents",
      "B",
      "They detect user-impacting failures early without large blast radius.",
    ],
  ],
} as const;

export const advancedSupplementQuizzes = [
  ...toQuizRows(advancedBalancedBanks),
  ...toQuizRows(advancedTopUpBanks),
];
