import "dotenv/config";
import { Pool } from "pg";

const pool = new Pool({ connectionString: process.env.DATABASE_URL });

type QuizRow = {
  lesson_title: string;
  question: string;
  option_a: string;
  option_b: string;
  option_c: string;
  option_d: string;
  answer: "A" | "B" | "C" | "D";
  explanation: string;
};

const quizzes: QuizRow[] = [
  // ══════════════════════════════════════════════════════════════════
  // BEGINNER: What is Software Testing?
  // ══════════════════════════════════════════════════════════════════
  {
    lesson_title: "What is Software Testing?",
    question: "What is the primary goal of software testing?",
    option_a: "To prove the software has no bugs",
    option_b: "To find defects and evaluate software quality",
    option_c: "To replace code reviews",
    option_d: "To write user documentation",
    answer: "B",
    explanation: "Testing evaluates quality and finds defects. It cannot prove a system has zero bugs — only that known scenarios pass.",
  },
  {
    lesson_title: "What is Software Testing?",
    question: "What is the difference between an error and a defect?",
    option_a: "They are the same thing",
    option_b: "An error is a human mistake that causes a defect in code",
    option_c: "A defect is a human mistake and an error is in the system",
    option_d: "An error only occurs in production",
    answer: "B",
    explanation: "An error is the human mistake (typo, logic flaw). The defect is the resulting fault in the code. A failure is when that defect causes observable incorrect behavior.",
  },
  {
    lesson_title: "What is Software Testing?",
    question: "Which statement best describes software quality?",
    option_a: "The software compiles without errors",
    option_b: "The software has 100% code coverage",
    option_c: "The software meets specified requirements and user expectations",
    option_d: "The software passes all performance tests",
    answer: "C",
    explanation: "Quality is about meeting requirements AND user expectations. Passing some tests or compiling does not guarantee quality.",
  },
  {
    lesson_title: "What is Software Testing?",
    question: "When is a bug most expensive to fix?",
    option_a: "During requirements phase",
    option_b: "During design phase",
    option_c: "During development",
    option_d: "After release to production",
    answer: "D",
    explanation: "The cost of fixing a bug grows exponentially the later it is found. Bugs found in production can cost 100x more than bugs found during requirements.",
  },
  {
    lesson_title: "What is Software Testing?",
    question: "What is a software failure?",
    option_a: "A mistake made by a programmer",
    option_b: "A flaw introduced into the source code",
    option_c: "Observable incorrect behavior when running the software",
    option_d: "A bug reported by a user",
    answer: "C",
    explanation: "A failure is the manifestation of a defect — observable incorrect system behavior. Errors cause defects; defects may cause failures.",
  },
  {
    lesson_title: "What is Software Testing?",
    question: "What does a QA engineer primarily advocate for?",
    option_a: "Faster development velocity",
    option_b: "Quality throughout the entire project",
    option_c: "Writing all the code",
    option_d: "Managing project timelines",
    answer: "B",
    explanation: "QA engineers champion quality throughout the SDLC — from reviewing requirements to verifying fixes in production.",
  },
  {
    lesson_title: "What is Software Testing?",
    question: "Testing can guarantee software is completely bug-free. True or False?",
    option_a: "True — exhaustive testing covers everything",
    option_b: "False — exhaustive testing is impossible for most systems",
    option_c: "True — if 100% code coverage is achieved",
    option_d: "True — if both manual and automated testing are used",
    answer: "B",
    explanation: "Exhaustive testing (testing every possible input) is impractical for any non-trivial system. Testing reduces risk but cannot guarantee zero bugs.",
  },
  {
    lesson_title: "What is Software Testing?",
    question: "What is the distinction between testing and debugging?",
    option_a: "Testing and debugging are the same activity",
    option_b: "Testing finds that a problem exists; debugging finds and fixes the cause",
    option_c: "Debugging is done by QA; testing is done by developers",
    option_d: "Testing fixes bugs; debugging reports them",
    answer: "B",
    explanation: "Testing is about finding defects. Debugging is about diagnosing the root cause and fixing it. Different skills, often done by different people.",
  },
  {
    lesson_title: "What is Software Testing?",
    question: "Which of these is a non-functional requirement?",
    option_a: "The user can reset their password",
    option_b: "The checkout form validates email format",
    option_c: "The login page must load within 2 seconds",
    option_d: "Admin users can view all reports",
    answer: "C",
    explanation: "Non-functional requirements describe HOW the system performs (speed, security, usability), not WHAT it does. Load time is a performance (non-functional) requirement.",
  },
  {
    lesson_title: "What is Software Testing?",
    question: "What is 'verification' in software testing?",
    option_a: "Are we building the right product?",
    option_b: "Are we building the product right?",
    option_c: "Is the product deployed correctly?",
    option_d: "Does the product satisfy user needs?",
    answer: "B",
    explanation: "Verification checks that the product is built correctly (reviews, inspections, walkthroughs). Validation checks that the right product was built (are we meeting user needs?).",
  },

  // ══════════════════════════════════════════════════════════════════
  // BEGINNER: SDLC
  // ══════════════════════════════════════════════════════════════════
  {
    lesson_title: "Software Development Life Cycle (SDLC)",
    question: "In traditional Waterfall SDLC, when does testing typically begin?",
    option_a: "During requirements gathering",
    option_b: "After the design phase",
    option_c: "After all coding is complete",
    option_d: "During deployment",
    answer: "C",
    explanation: "In classic Waterfall, testing is a separate phase that starts only after development is complete — one of its major drawbacks.",
  },
  {
    lesson_title: "Software Development Life Cycle (SDLC)",
    question: "What does V-Model stand for?",
    option_a: "Version and Variant Model",
    option_b: "Verification and Validation Model",
    option_c: "Variable and Value Model",
    option_d: "Visual and Verbal Model",
    answer: "B",
    explanation: "The V-Model represents Verification (building correctly) and Validation (building the right thing), with each development phase paired with a testing phase.",
  },
  {
    lesson_title: "Software Development Life Cycle (SDLC)",
    question: "In Agile SDLC, when does testing occur?",
    option_a: "Only at the end of each sprint",
    option_b: "Only during dedicated test sprints",
    option_c: "Throughout every sprint, in parallel with development",
    option_d: "After the product backlog is complete",
    answer: "C",
    explanation: "Agile promotes continuous testing within every sprint. QA works in parallel with development, not after.",
  },
  {
    lesson_title: "Software Development Life Cycle (SDLC)",
    question: "In the V-Model, which testing phase corresponds to the requirements phase?",
    option_a: "Unit Testing",
    option_b: "Integration Testing",
    option_c: "System Testing",
    option_d: "Acceptance Testing",
    answer: "D",
    explanation: "In V-Model: Requirements ↔ Acceptance Testing. System Design ↔ System Testing. Architecture ↔ Integration Testing. Coding ↔ Unit Testing.",
  },
  {
    lesson_title: "Software Development Life Cycle (SDLC)",
    question: "What is the main disadvantage of the Waterfall SDLC for QA?",
    option_a: "Too many meetings",
    option_b: "Bugs are discovered very late, making them expensive to fix",
    option_c: "No documentation is produced",
    option_d: "Developers don't write unit tests",
    answer: "B",
    explanation: "Waterfall's sequential nature means bugs found in the testing phase were introduced much earlier, making them expensive to fix.",
  },
  {
    lesson_title: "Software Development Life Cycle (SDLC)",
    question: "What is a sprint in Agile?",
    option_a: "A full product release cycle",
    option_b: "A time-boxed iteration (typically 2-4 weeks) that produces shippable software",
    option_c: "A planning meeting",
    option_d: "A bug-fixing period",
    answer: "B",
    explanation: "A sprint is a fixed-length iteration in Scrum (typically 2-4 weeks) that results in a potentially shippable product increment.",
  },
  {
    lesson_title: "Software Development Life Cycle (SDLC)",
    question: "During which SDLC phase should QA engineers review requirements?",
    option_a: "Only during the testing phase",
    option_b: "As early as the requirements gathering phase",
    option_c: "After deployment",
    option_d: "Only when developers ask",
    answer: "B",
    explanation: "QA should be involved from the requirements phase to identify ambiguous, incomplete, or untestable requirements — catching issues when they're cheapest to fix.",
  },
  {
    lesson_title: "Software Development Life Cycle (SDLC)",
    question: "What is meant by 'shift-left testing'?",
    option_a: "Moving testers to a different team",
    option_b: "Starting testing activities earlier in the SDLC",
    option_c: "Using left-hand navigations in test management tools",
    option_d: "Reducing test case count",
    answer: "B",
    explanation: "Shift-left means moving testing activities earlier in the development process — catching defects sooner when they're cheaper to fix.",
  },
  {
    lesson_title: "Software Development Life Cycle (SDLC)",
    question: "Which SDLC phase produces the Test Plan?",
    option_a: "Requirements Gathering",
    option_b: "System Design",
    option_c: "Testing Phase (Test Planning within STLC)",
    option_d: "Maintenance",
    answer: "C",
    explanation: "The Test Plan is created during the Test Planning phase of STLC, which runs in parallel with the System Design phase of SDLC.",
  },
  {
    lesson_title: "Software Development Life Cycle (SDLC)",
    question: "What makes Agile better suited for QA compared to Waterfall?",
    option_a: "Agile has no testing requirements",
    option_b: "Agile allows continuous testing and early defect detection every sprint",
    option_c: "Agile requires less documentation",
    option_d: "Agile uses only automated testing",
    answer: "B",
    explanation: "Agile's iterative nature means QA continuously tests within each sprint, finding and fixing bugs much earlier than in Waterfall.",
  },

  // ══════════════════════════════════════════════════════════════════
  // BEGINNER: STLC
  // ══════════════════════════════════════════════════════════════════
  {
    lesson_title: "Software Testing Life Cycle (STLC)",
    question: "How many phases are there in the STLC?",
    option_a: "4",
    option_b: "5",
    option_c: "6",
    option_d: "7",
    answer: "C",
    explanation: "The STLC has 6 phases: Requirement Analysis, Test Planning, Test Case Development, Test Environment Setup, Test Execution, and Test Closure.",
  },
  {
    lesson_title: "Software Testing Life Cycle (STLC)",
    question: "What is the first phase of STLC?",
    option_a: "Test Planning",
    option_b: "Test Execution",
    option_c: "Requirement Analysis",
    option_d: "Test Case Development",
    answer: "C",
    explanation: "Requirement Analysis is the first phase — QA studies the requirements to understand what must be tested before any planning begins.",
  },
  {
    lesson_title: "Software Testing Life Cycle (STLC)",
    question: "What document is produced during the Test Planning phase?",
    option_a: "Requirements Traceability Matrix",
    option_b: "Test Plan",
    option_c: "Defect Report",
    option_d: "Test Summary Report",
    answer: "B",
    explanation: "The Test Planning phase produces the Test Plan — covering scope, approach, resources, schedule, and risks.",
  },
  {
    lesson_title: "Software Testing Life Cycle (STLC)",
    question: "What is the entry criterion for the Test Execution phase?",
    option_a: "All bugs are fixed",
    option_b: "Test cases are written and the test environment is set up",
    option_c: "The product is deployed to production",
    option_d: "Management approval is received",
    answer: "B",
    explanation: "Test Execution can begin when test cases are ready and the test environment is configured and verified to work.",
  },
  {
    lesson_title: "Software Testing Life Cycle (STLC)",
    question: "What happens during the Test Closure phase?",
    option_a: "New test cases are written",
    option_b: "Bugs are filed for the first time",
    option_c: "Metrics are analyzed and a test summary report is created",
    option_d: "The test environment is set up",
    answer: "C",
    explanation: "Test Closure is the wrap-up phase: analyze metrics, document lessons learned, create the test summary report, and archive test artifacts.",
  },
  {
    lesson_title: "Software Testing Life Cycle (STLC)",
    question: "During which STLC phase are test cases peer-reviewed?",
    option_a: "Test Planning",
    option_b: "Test Case Development",
    option_c: "Test Execution",
    option_d: "Test Closure",
    answer: "B",
    explanation: "Test Case Development includes writing test cases AND having them peer-reviewed to ensure quality before execution.",
  },
  {
    lesson_title: "Software Testing Life Cycle (STLC)",
    question: "What is a smoke test in the context of environment setup?",
    option_a: "A test to find performance issues",
    option_b: "A quick check that the test environment is working",
    option_c: "A test that fills the database with data",
    option_d: "A security vulnerability scan",
    answer: "B",
    explanation: "In environment setup, a smoke test verifies that the environment is configured correctly and basic functionality works before full testing begins.",
  },
  {
    lesson_title: "Software Testing Life Cycle (STLC)",
    question: "What is an exit criterion?",
    option_a: "Conditions that must be met to start a testing phase",
    option_b: "Conditions that must be met to end a testing phase",
    option_c: "Conditions under which testing is skipped",
    option_d: "The final test case in a suite",
    answer: "B",
    explanation: "Exit criteria define when a testing phase is considered complete. Example: 100% test cases executed, no open Critical bugs, test coverage > 80%.",
  },
  {
    lesson_title: "Software Testing Life Cycle (STLC)",
    question: "What is produced at the end of the STLC?",
    option_a: "A new Test Plan",
    option_b: "Updated requirements",
    option_c: "Test Closure Report",
    option_d: "Source code",
    answer: "C",
    explanation: "The Test Closure Report summarizes all testing activities, metrics, lessons learned, and formally closes the testing effort.",
  },
  {
    lesson_title: "Software Testing Life Cycle (STLC)",
    question: "During Requirement Analysis, what is the output?",
    option_a: "Test cases",
    option_b: "Requirements Understanding Document (RUD) or similar",
    option_c: "Bug reports",
    option_d: "Test scripts",
    answer: "B",
    explanation: "The output of Requirement Analysis is a Requirements Understanding Document (or RTM baseline) capturing what QA understands about what needs to be tested.",
  },

  // ══════════════════════════════════════════════════════════════════
  // BEGINNER: Types of Testing
  // ══════════════════════════════════════════════════════════════════
  {
    lesson_title: "Types of Testing",
    question: "What does black-box testing mean?",
    option_a: "Testing in a dark room",
    option_b: "Testing without knowledge of internal code structure",
    option_c: "Testing only the backend",
    option_d: "Testing with full access to source code",
    answer: "B",
    explanation: "Black-box testing treats the system as a black box — the tester focuses on inputs and outputs without knowing the internal implementation.",
  },
  {
    lesson_title: "Types of Testing",
    question: "Which testing type verifies that new changes haven't broken existing functionality?",
    option_a: "Smoke Testing",
    option_b: "Acceptance Testing",
    option_c: "Regression Testing",
    option_d: "Unit Testing",
    answer: "C",
    explanation: "Regression testing ensures existing functionality still works after code changes. It's the most common candidate for automation.",
  },
  {
    lesson_title: "Types of Testing",
    question: "What is the primary goal of load testing?",
    option_a: "Find security vulnerabilities",
    option_b: "Verify the system handles expected normal traffic",
    option_c: "Push the system beyond its limits",
    option_d: "Test the UI layout",
    answer: "B",
    explanation: "Load testing simulates expected normal usage to verify the system meets performance SLAs under typical conditions.",
  },
  {
    lesson_title: "Types of Testing",
    question: "Who typically performs User Acceptance Testing (UAT)?",
    option_a: "QA engineers",
    option_b: "Developers",
    option_c: "End users or business stakeholders",
    option_d: "Project managers",
    answer: "C",
    explanation: "UAT is performed by actual end users or business stakeholders to validate that the system meets their business needs before go-live.",
  },
  {
    lesson_title: "Types of Testing",
    question: "What distinguishes integration testing from unit testing?",
    option_a: "Unit testing is faster",
    option_b: "Integration testing tests how multiple components work together",
    option_c: "Integration testing uses real databases, unit testing doesn't",
    option_d: "Unit testing covers more code",
    answer: "B",
    explanation: "Unit testing isolates individual functions/components. Integration testing verifies that multiple components interact correctly at their interfaces.",
  },
  {
    lesson_title: "Types of Testing",
    question: "What is the goal of stress testing?",
    option_a: "Verify normal operation under expected load",
    option_b: "Find the breaking point and observe failure behavior",
    option_c: "Test UI responsiveness",
    option_d: "Detect memory leaks over time",
    answer: "B",
    explanation: "Stress testing pushes the system beyond expected capacity to find the breaking point and observe how it fails (gracefully or catastrophically).",
  },
  {
    lesson_title: "Types of Testing",
    question: "Which type of testing evaluates how easy the software is to use?",
    option_a: "Security Testing",
    option_b: "Performance Testing",
    option_c: "Usability Testing",
    option_d: "Regression Testing",
    answer: "C",
    explanation: "Usability testing evaluates user experience — how easy and intuitive the software is to use for its intended audience.",
  },
  {
    lesson_title: "Types of Testing",
    question: "Soak testing is designed to find what type of issue?",
    option_a: "SQL injection vulnerabilities",
    option_b: "Memory leaks and performance degradation over extended time",
    option_c: "Broken UI layouts",
    option_d: "Missing features",
    answer: "B",
    explanation: "Soak testing (endurance testing) runs the system at normal load for an extended period to find issues like memory leaks that only appear over time.",
  },
  {
    lesson_title: "Types of Testing",
    question: "What is grey-box testing?",
    option_a: "Testing in staging environment only",
    option_b: "Testing with partial knowledge of the internal system",
    option_c: "Testing only non-functional requirements",
    option_d: "Testing using only automated tools",
    answer: "B",
    explanation: "Grey-box testing combines black-box (user perspective) and white-box (internal knowledge) — the tester has partial insight into the system's internals.",
  },
  {
    lesson_title: "Types of Testing",
    question: "Which testing type is BEST suited for automation?",
    option_a: "Exploratory Testing",
    option_b: "Usability Testing",
    option_c: "Ad-hoc Testing",
    option_d: "Regression Testing",
    answer: "D",
    explanation: "Regression testing is the best automation candidate — it's repetitive, stable, runs frequently, and has clear pass/fail criteria.",
  },

  // ══════════════════════════════════════════════════════════════════
  // BEGINNER: Writing Test Cases
  // ══════════════════════════════════════════════════════════════════
  {
    lesson_title: "Writing Your First Test Case",
    question: "Which field in a test case specifies the required state BEFORE test execution?",
    option_a: "Expected Result",
    option_b: "Test Steps",
    option_c: "Preconditions",
    option_d: "Actual Result",
    answer: "C",
    explanation: "Preconditions define the state that must exist before the test can be executed — e.g., user must be registered, browser must be open.",
  },
  {
    lesson_title: "Writing Your First Test Case",
    question: "What is the best practice for a single test case?",
    option_a: "Test as many features as possible in one test",
    option_b: "Test one specific scenario per test case",
    option_c: "Combine positive and negative tests together",
    option_d: "Share test data across all test cases",
    answer: "B",
    explanation: "Each test case should have one clear goal. Testing multiple things in one case makes it hard to isolate failures and understand what went wrong.",
  },
  {
    lesson_title: "Writing Your First Test Case",
    question: "A test case status of 'Blocked' means:",
    option_a: "The test failed",
    option_b: "The test passed but has warnings",
    option_c: "The test cannot be executed due to a dependency or environment issue",
    option_d: "The test was skipped intentionally",
    answer: "C",
    explanation: "Blocked means the test couldn't be executed — typically due to a prerequisite not being met, like a dependency feature not being built yet.",
  },
  {
    lesson_title: "Writing Your First Test Case",
    question: "What should test data in a test case contain?",
    option_a: "General descriptions like 'enter a valid email'",
    option_b: "Exact, specific values like 'qa_tester@example.com'",
    option_c: "Random data generated at runtime",
    option_d: "Data from production systems",
    answer: "B",
    explanation: "Test data must be specific and exact so the test is repeatable. Vague descriptions like 'a valid email' lead to inconsistent results.",
  },
  {
    lesson_title: "Writing Your First Test Case",
    question: "What is a negative test case?",
    option_a: "A test that always fails",
    option_b: "A test with invalid inputs to verify the system handles errors correctly",
    option_c: "A test for deprecated features",
    option_d: "A test written in a negative tone",
    answer: "B",
    explanation: "Negative tests verify system behavior with invalid inputs — e.g., wrong password, missing required fields, out-of-range values. Systems must handle these gracefully.",
  },
  {
    lesson_title: "Writing Your First Test Case",
    question: "What makes a test case 'independent'?",
    option_a: "It runs faster than other tests",
    option_b: "It can be executed without relying on other test cases",
    option_c: "It doesn't need a test environment",
    option_d: "It doesn't require any input data",
    answer: "B",
    explanation: "Independent test cases can run in any order and don't require other tests to run first. This prevents cascading failures and makes debugging easier.",
  },
  {
    lesson_title: "Writing Your First Test Case",
    question: "What is the 'Actual Result' field used for?",
    option_a: "Predicted outcome before running the test",
    option_b: "What the system actually did when the test was executed",
    option_c: "The test case author's name",
    option_d: "The environment the test ran in",
    answer: "B",
    explanation: "Actual Result is filled in during test execution and records what actually happened. Comparing it to Expected Result determines pass/fail.",
  },
  {
    lesson_title: "Writing Your First Test Case",
    question: "Why should test cases be repeatable?",
    option_a: "To increase the test count metric",
    option_b: "So the same steps produce the same result every time, enabling reliable verification",
    option_c: "To reduce the need for test data",
    option_d: "Because automation tools require it",
    answer: "B",
    explanation: "Repeatable test cases give consistent results. If a test passes sometimes and fails other times, it's unreliable (flaky) and loses value.",
  },
  {
    lesson_title: "Writing Your First Test Case",
    question: "What is test case priority?",
    option_a: "How quickly a test runs",
    option_b: "The order in which tests should be executed based on business importance",
    option_c: "The severity of the bug it found",
    option_d: "The number of steps in the test",
    answer: "B",
    explanation: "Priority indicates which tests should run first based on business importance. High priority tests cover critical functionality.",
  },
  {
    lesson_title: "Writing Your First Test Case",
    question: "A test case ID (like TC-LOGIN-001) serves what purpose?",
    option_a: "Shows the date the test was created",
    option_b: "Uniquely identifies the test case for tracking and referencing",
    option_c: "Indicates the automation framework used",
    option_d: "Shows which developer wrote the feature",
    answer: "B",
    explanation: "Test case IDs uniquely identify test cases so they can be referenced in bug reports, test plans, and traceability matrices.",
  },

  // ══════════════════════════════════════════════════════════════════
  // BEGINNER: Bug Reporting
  // ══════════════════════════════════════════════════════════════════
  {
    lesson_title: "Bug Reporting Fundamentals",
    question: "What is the difference between bug severity and priority?",
    option_a: "They mean the same thing",
    option_b: "Severity is the technical impact; priority is the urgency to fix",
    option_c: "Priority is the technical impact; severity is the urgency",
    option_d: "Severity is set by developers; priority by QA",
    answer: "B",
    explanation: "Severity = how bad the impact is technically. Priority = how urgently it needs fixing (business decision). A typo on the homepage might be low severity but high priority.",
  },
  {
    lesson_title: "Bug Reporting Fundamentals",
    question: "Which is the best bug title?",
    option_a: "Login broken",
    option_b: "Page error",
    option_c: "Login button unresponsive when email contains + character",
    option_d: "Bug in authentication",
    answer: "C",
    explanation: "Good bug titles are specific: what is broken + under what conditions. This lets developers understand the scope without reading the full report.",
  },
  {
    lesson_title: "Bug Reporting Fundamentals",
    question: "Why is 'Steps to Reproduce' the most critical section of a bug report?",
    option_a: "It shows the severity of the bug",
    option_b: "Without it, developers cannot reliably reproduce and fix the bug",
    option_c: "It determines who fixes the bug",
    option_d: "It calculates the priority of the bug",
    answer: "B",
    explanation: "Developers need to reproduce the bug to understand and fix it. Vague or incomplete reproduction steps are the #1 cause of bugs being marked 'Cannot Reproduce'.",
  },
  {
    lesson_title: "Bug Reporting Fundamentals",
    question: "A critical bug that crashes the payment system but only happens once is best described as:",
    option_a: "High Severity, High Priority",
    option_b: "Low Severity, Low Priority",
    option_c: "High Severity, Low Priority",
    option_d: "Low Severity, High Priority",
    answer: "A",
    explanation: "Payment system crashes are critical business impact (high severity) AND need immediate attention regardless of frequency (high priority).",
  },
  {
    lesson_title: "Bug Reporting Fundamentals",
    question: "What should you include in the 'Environment' field of a bug report?",
    option_a: "Your personal opinion about the feature",
    option_b: "OS, browser version, app version, and URL where the bug occurred",
    option_c: "The developer's name",
    option_d: "Your test case ID only",
    answer: "B",
    explanation: "Environment details (OS, browser, version, URL) help developers reproduce the bug in the same conditions. The same bug may not appear on different OS/browser combinations.",
  },
  {
    lesson_title: "Bug Reporting Fundamentals",
    question: "What does 'intermittent' reproducibility mean?",
    option_a: "The bug happens every time",
    option_b: "The bug only happens in production",
    option_c: "The bug happens some of the time but not consistently",
    option_d: "The bug cannot be reproduced",
    answer: "C",
    explanation: "Intermittent bugs don't reproduce every time — they might occur 30-70% of attempts. These are especially difficult to diagnose and fix.",
  },
  {
    lesson_title: "Bug Reporting Fundamentals",
    question: "When should you attach a screenshot or video to a bug report?",
    option_a: "Never — they take up too much space",
    option_b: "Only for UI bugs",
    option_c: "Always when possible — visual evidence speeds up developer understanding",
    option_d: "Only when the bug is Critical severity",
    answer: "C",
    explanation: "Visual evidence (screenshots, videos, logs) dramatically speeds up bug resolution by giving developers immediate context without needing to reproduce it first.",
  },
  {
    lesson_title: "Bug Reporting Fundamentals",
    question: "A bug report where 'Expected Result' and 'Actual Result' are identical indicates:",
    option_a: "A valid bug",
    option_b: "A critical bug",
    option_c: "The test passed — no defect",
    option_d: "The environment is broken",
    answer: "C",
    explanation: "A bug exists when actual results differ from expected results. If they match, the feature works as specified — it's not a bug.",
  },
  {
    lesson_title: "Bug Reporting Fundamentals",
    question: "Who assigns priority to a bug?",
    option_a: "Always the QA engineer who found it",
    option_b: "Always the developer who fixes it",
    option_c: "Business/product owner or team consensus",
    option_d: "The test management tool automatically",
    answer: "C",
    explanation: "Priority is a business decision — it depends on business impact, customer impact, and release timelines. Product owners or the team make this decision, not QA alone.",
  },
  {
    lesson_title: "Bug Reporting Fundamentals",
    question: "What is an 'orphan bug'?",
    option_a: "A bug not linked to any test case or requirement",
    option_b: "A bug only reproducible in production",
    option_c: "A bug that cannot be reproduced",
    option_d: "A bug reported by an external user",
    answer: "A",
    explanation: "An orphan bug has no traceability to requirements or test cases — making it hard to understand its scope and impact on the release.",
  },

  // ══════════════════════════════════════════════════════════════════
  // BEGINNER: Defect Life Cycle
  // ══════════════════════════════════════════════════════════════════
  {
    lesson_title: "Defect Life Cycle",
    question: "What is the first state of a newly reported bug?",
    option_a: "Open",
    option_b: "New",
    option_c: "Assigned",
    option_d: "In Progress",
    answer: "B",
    explanation: "When a bug is first reported, it enters the 'New' state — awaiting review and confirmation by the team.",
  },
  {
    lesson_title: "Defect Life Cycle",
    question: "When does a bug move to 'Reopen' state?",
    option_a: "When the bug is first reported",
    option_b: "When a developer starts working on it",
    option_c: "When QA retests and finds the fix didn't work",
    option_d: "When the bug is assigned to a developer",
    answer: "C",
    explanation: "A bug is reopened when it was marked Fixed, QA retested it, but the fix was insufficient — the bug still exists.",
  },
  {
    lesson_title: "Defect Life Cycle",
    question: "What does 'Deferred' status mean for a bug?",
    option_a: "The bug was fixed automatically",
    option_b: "The bug is not valid",
    option_c: "The valid bug will be fixed in a future release",
    option_d: "The bug requires more investigation",
    answer: "C",
    explanation: "Deferred means the bug is confirmed valid but the fix is scheduled for a future release — usually due to lower priority or resource constraints.",
  },
  {
    lesson_title: "Defect Life Cycle",
    question: "What should QA do in the 'Retest' phase?",
    option_a: "Write new test cases for the bug",
    option_b: "Report a new bug",
    option_c: "Verify the fix works AND check for regression",
    option_d: "Close the bug immediately",
    answer: "C",
    explanation: "During Retest, QA verifies the specific fix works AND runs surrounding tests to ensure the fix didn't introduce new issues (regression).",
  },
  {
    lesson_title: "Defect Life Cycle",
    question: "What does 'Rejected' status indicate?",
    option_a: "The developer cannot fix the bug",
    option_b: "The reported issue is not actually a bug — it's working as designed",
    option_c: "The bug is too old to fix",
    option_d: "The bug was found by an external user",
    answer: "B",
    explanation: "Rejected means the team determined the reported behavior is correct and intentional — it's not a defect. QA must document the reasoning.",
  },
  {
    lesson_title: "Defect Life Cycle",
    question: "Before closing a bug, QA must:",
    option_a: "Delete the bug report",
    option_b: "Retest the fix in the same environment where the bug was found",
    option_c: "Only verify the fix works on their local machine",
    option_d: "Get approval from the product manager",
    answer: "B",
    explanation: "QA must verify the fix in the same environment where the bug was found (not just locally or in a different environment).",
  },
  {
    lesson_title: "Defect Life Cycle",
    question: "In which state does QA verify that the bug is fixed?",
    option_a: "New",
    option_b: "Fixed",
    option_c: "Retest",
    option_d: "Closed",
    answer: "C",
    explanation: "The Retest state is when QA verifies the fix. If verified successfully, the bug moves to Verified → Closed. If not, it goes back to Reopen.",
  },
  {
    lesson_title: "Defect Life Cycle",
    question: "What is bug triage?",
    option_a: "Writing test cases for bugs",
    option_b: "A team meeting to review, prioritize, and assign open defects",
    option_c: "Automated bug detection",
    option_d: "The process of closing all bugs before release",
    answer: "B",
    explanation: "Bug triage is a regular team meeting where open defects are reviewed, their severity/priority assessed, and they're assigned to team members for resolution.",
  },

  // ══════════════════════════════════════════════════════════════════
  // BEGINNER: Test Environments
  // ══════════════════════════════════════════════════════════════════
  {
    lesson_title: "Test Environments & Configurations",
    question: "Which environment most closely mirrors production?",
    option_a: "Development",
    option_b: "QA/Testing",
    option_c: "Staging/Pre-production",
    option_d: "Local",
    answer: "C",
    explanation: "Staging (pre-production) is specifically designed to mirror production as closely as possible for final validation before release.",
  },
  {
    lesson_title: "Test Environments & Configurations",
    question: "What is 'environment parity'?",
    option_a: "All testers share the same computer",
    option_b: "Test environments match production in software versions and configurations",
    option_c: "All environments run the same test cases",
    option_d: "Developers and QA use the same environments",
    answer: "B",
    explanation: "Environment parity means your test environment has the same OS, database version, dependencies, and configuration as production — preventing 'works on my machine' issues.",
  },
  {
    lesson_title: "Test Environments & Configurations",
    question: "What is the main risk of using a shared test environment?",
    option_a: "It's more expensive",
    option_b: "Multiple testers can interfere with each other's test data",
    option_c: "It takes longer to deploy",
    option_d: "It doesn't support automation",
    answer: "B",
    explanation: "In shared environments, multiple testers can create, modify, or delete data that others rely on — causing false failures and confusion.",
  },
  {
    lesson_title: "Test Environments & Configurations",
    question: "What should always be documented about a test environment?",
    option_a: "Only the URL",
    option_b: "URL, OS, app version, database version, and last deployment date",
    option_c: "Only the database version",
    option_d: "Only the test cases that ran in it",
    answer: "B",
    explanation: "Complete environment documentation (URL, OS, versions, deployment date) ensures bugs can be reproduced reliably and environment issues can be diagnosed.",
  },
  {
    lesson_title: "Test Environments & Configurations",
    question: "What is 'environment drift'?",
    option_a: "When environments run too slow",
    option_b: "When the test environment gradually diverges from production configuration",
    option_c: "When test data is deleted accidentally",
    option_d: "When different browsers behave differently",
    answer: "B",
    explanation: "Environment drift occurs when manual changes, hotfixes, or configuration updates are applied to production but not reflected in test environments — causing false test results.",
  },

  // ══════════════════════════════════════════════════════════════════
  // BEGINNER: Exploratory Testing
  // ══════════════════════════════════════════════════════════════════
  {
    lesson_title: "Exploratory Testing",
    question: "What is the primary characteristic of exploratory testing?",
    option_a: "All test cases are written before execution",
    option_b: "Testing and test design happen simultaneously",
    option_c: "Only automated tools are used",
    option_d: "Only functional areas are tested",
    answer: "B",
    explanation: "Exploratory testing is simultaneous learning, test design, and execution. The tester uses their knowledge and creativity in real-time rather than following pre-written scripts.",
  },
  {
    lesson_title: "Exploratory Testing",
    question: "What is a 'charter' in session-based exploratory testing?",
    option_a: "A legal document for testing",
    option_b: "A mission statement that guides a testing session",
    option_c: "A list of all test cases",
    option_d: "A bug report template",
    answer: "B",
    explanation: "A charter defines the mission of an exploratory session: what area to explore, how to approach it, and what you're trying to learn or find.",
  },
  {
    lesson_title: "Exploratory Testing",
    question: "What is the recommended duration for a session-based exploratory testing session?",
    option_a: "5-10 minutes",
    option_b: "4-8 hours",
    option_c: "45-90 minutes",
    option_d: "1 full day",
    answer: "C",
    explanation: "Sessions of 45-90 minutes are optimal — long enough to explore deeply, short enough to maintain focus and document findings accurately.",
  },
  {
    lesson_title: "Exploratory Testing",
    question: "Which of these is a good heuristic to use during exploratory testing?",
    option_a: "Only test the happy path",
    option_b: "CRUD — verify Create, Read, Update, Delete for every entity",
    option_c: "Focus only on the most recent feature",
    option_d: "Never take notes during exploration",
    answer: "B",
    explanation: "CRUD is a powerful heuristic — verifying all four operations exist and work correctly for every entity catches common omissions and bugs.",
  },
  {
    lesson_title: "Exploratory Testing",
    question: "When is exploratory testing most valuable?",
    option_a: "When all requirements are perfectly documented",
    option_b: "For regression testing of stable features",
    option_c: "For new features with incomplete specs and to find unexpected bugs",
    option_d: "When running automated test suites",
    answer: "C",
    explanation: "Exploratory testing shines for new or incomplete features where scripted tests can't anticipate everything, and when trying to find bugs that formal test cases miss.",
  },

  // ══════════════════════════════════════════════════════════════════
  // BEGINNER: API Testing Introduction
  // ══════════════════════════════════════════════════════════════════
  {
    lesson_title: "Introduction to API Testing",
    question: "What HTTP method is used to retrieve data from a server?",
    option_a: "POST",
    option_b: "PUT",
    option_c: "GET",
    option_d: "DELETE",
    answer: "C",
    explanation: "GET is used to read/retrieve resources. It should not change server state — it's a read-only operation.",
  },
  {
    lesson_title: "Introduction to API Testing",
    question: "What HTTP status code indicates a resource was not found?",
    option_a: "200",
    option_b: "400",
    option_c: "401",
    option_d: "404",
    answer: "D",
    explanation: "404 Not Found means the requested resource doesn't exist. This is one of the most important status codes for API testers to know.",
  },
  {
    lesson_title: "Introduction to API Testing",
    question: "What does HTTP status 401 mean?",
    option_a: "Resource not found",
    option_b: "Request not authenticated — no or invalid credentials provided",
    option_c: "Authenticated but not authorized",
    option_d: "Server error",
    answer: "B",
    explanation: "401 Unauthorized means authentication is required or has failed. The request lacks valid authentication credentials.",
  },
  {
    lesson_title: "Introduction to API Testing",
    question: "What does HTTP status 403 mean?",
    option_a: "Not authenticated",
    option_b: "Resource not found",
    option_c: "Authenticated but forbidden — user lacks permission",
    option_d: "Bad request",
    answer: "C",
    explanation: "403 Forbidden means the user IS authenticated but does NOT have permission for the requested resource (different from 401).",
  },
  {
    lesson_title: "Introduction to API Testing",
    question: "What HTTP method is used to create a new resource?",
    option_a: "GET",
    option_b: "POST",
    option_c: "DELETE",
    option_d: "PATCH",
    answer: "B",
    explanation: "POST is used to create new resources. The server creates the resource and typically returns 201 Created with the new resource's data.",
  },
  {
    lesson_title: "Introduction to API Testing",
    question: "What is an advantage of API testing over UI testing?",
    option_a: "API tests are always cheaper to write",
    option_b: "API tests validate user experience better",
    option_c: "API tests are faster, more stable, and catch business logic issues early",
    option_d: "API tests don't need test data",
    answer: "C",
    explanation: "API tests are significantly faster than UI tests, more stable (APIs change less than UIs), and can test business logic without a working UI.",
  },
  {
    lesson_title: "Introduction to API Testing",
    question: "In REST APIs, what does the response body typically contain?",
    option_a: "HTML markup",
    option_b: "JSON or XML data",
    option_c: "SQL queries",
    option_d: "Binary files only",
    answer: "B",
    explanation: "REST APIs typically return JSON (most common) or XML formatted data that represents the requested resource or operation result.",
  },
  {
    lesson_title: "Introduction to API Testing",
    question: "What is Postman primarily used for?",
    option_a: "Writing and running automated UI tests",
    option_b: "Sending and testing HTTP requests to APIs",
    option_c: "Managing databases",
    option_d: "Creating test plans",
    answer: "B",
    explanation: "Postman is an API testing tool that allows you to send HTTP requests, inspect responses, write assertions, and manage collections of API tests.",
  },

  // ══════════════════════════════════════════════════════════════════
  // INTERMEDIATE: Test Planning
  // ══════════════════════════════════════════════════════════════════
  {
    lesson_title: "Test Planning & Test Strategy",
    question: "What is the difference between a Test Strategy and a Test Plan?",
    option_a: "They are the same document",
    option_b: "Test Strategy is organization-wide; Test Plan is project-specific",
    option_c: "Test Plan is organization-wide; Test Strategy is project-specific",
    option_d: "Test Strategy is written by developers",
    answer: "B",
    explanation: "Test Strategy defines the overall organization approach to testing (high level). Test Plan implements that strategy for a specific project or release.",
  },
  {
    lesson_title: "Test Planning & Test Strategy",
    question: "What are 'suspension criteria' in a test plan?",
    option_a: "Conditions to start testing",
    option_b: "Conditions under which testing should be temporarily stopped",
    option_c: "The end date of testing",
    option_d: "Criteria for closing bugs",
    answer: "B",
    explanation: "Suspension criteria define when to pause testing — for example, if more than 30% of test cases are blocked due to critical bugs, testing is suspended until fixes are delivered.",
  },
  {
    lesson_title: "Test Planning & Test Strategy",
    question: "Risk-Based Testing prioritizes tests based on:",
    option_a: "Test case execution speed",
    option_b: "The likelihood and impact of failure",
    option_c: "Alphabetical order of features",
    option_d: "Number of lines of code",
    answer: "B",
    explanation: "Risk = Likelihood × Impact. Risk-based testing ensures the highest-risk features receive the most thorough testing, maximizing value when time is limited.",
  },
  {
    lesson_title: "Test Planning & Test Strategy",
    question: "What should be explicitly documented in a test plan as 'Features NOT to Test'?",
    option_a: "All features that work perfectly",
    option_b: "Features explicitly excluded from the current test scope and why",
    option_c: "Automated test cases only",
    option_d: "Features assigned to other teams",
    answer: "B",
    explanation: "Explicitly documenting out-of-scope features prevents misunderstandings and ensures stakeholders know what is and isn't being tested in this release.",
  },
  {
    lesson_title: "Test Planning & Test Strategy",
    question: "What is an exit criterion for a test phase?",
    option_a: "When the QA team takes a break",
    option_b: "Conditions that must be met before the phase can be considered complete",
    option_c: "The number of bugs found",
    option_d: "The final test case in the suite",
    answer: "B",
    explanation: "Exit criteria are measurable conditions that define 'done' for a testing phase — e.g., 100% test execution, no open critical bugs, pass rate > 90%.",
  },

  // ══════════════════════════════════════════════════════════════════
  // INTERMEDIATE: RTM
  // ══════════════════════════════════════════════════════════════════
  {
    lesson_title: "Requirements Analysis & Traceability Matrix",
    question: "What is the primary purpose of a Requirements Traceability Matrix (RTM)?",
    option_a: "Track developer progress",
    option_b: "Ensure every requirement has corresponding test coverage",
    option_c: "Schedule testing activities",
    option_d: "Report bugs to stakeholders",
    answer: "B",
    explanation: "An RTM maps requirements to test cases bidirectionally, ensuring 100% test coverage and no orphan test cases.",
  },
  {
    lesson_title: "Requirements Analysis & Traceability Matrix",
    question: "What does 'forward traceability' mean in an RTM?",
    option_a: "Test cases → Requirements",
    option_b: "Requirements → Test Cases",
    option_c: "Requirements → Source Code",
    option_d: "Test Cases → Bug Reports",
    answer: "B",
    explanation: "Forward traceability maps from requirements to test cases — ensuring every requirement has at least one test case covering it.",
  },
  {
    lesson_title: "Requirements Analysis & Traceability Matrix",
    question: "A requirement that says 'the system should be user-friendly' is an example of:",
    option_a: "A clear, testable requirement",
    option_b: "An ambiguous requirement that needs clarification",
    option_c: "A security requirement",
    option_d: "A functional requirement",
    answer: "B",
    explanation: "'User-friendly' is unmeasurable and subjective — an ambiguous requirement. QA should raise this and ask for specific, measurable criteria (e.g., task completion rate > 90%).",
  },
  {
    lesson_title: "Requirements Analysis & Traceability Matrix",
    question: "What is an 'orphan test case' in the context of RTM?",
    option_a: "A test case with no expected result",
    option_b: "A test case not linked to any requirement",
    option_c: "A test case that always fails",
    option_d: "A test case written by a contractor",
    answer: "B",
    explanation: "An orphan test case has no requirement traceability — it may be testing something not required, wasting effort, or the requirement was deleted.",
  },

  // ══════════════════════════════════════════════════════════════════
  // INTERMEDIATE: Equivalence Partitioning
  // ══════════════════════════════════════════════════════════════════
  {
    lesson_title: "Equivalence Partitioning",
    question: "What is the main benefit of Equivalence Partitioning?",
    option_a: "It finds more bugs",
    option_b: "It reduces the number of test cases while maintaining coverage",
    option_c: "It eliminates the need for boundary testing",
    option_d: "It improves test execution speed",
    answer: "B",
    explanation: "EP reduces test cases by identifying groups where all values behave the same. Testing one value per group gives the same confidence as testing every value.",
  },
  {
    lesson_title: "Equivalence Partitioning",
    question: "For a field accepting values 1-100, how many equivalence partitions are there?",
    option_a: "1",
    option_b: "2",
    option_c: "3",
    option_d: "100",
    answer: "C",
    explanation: "Three partitions: invalid low (< 1), valid (1-100), invalid high (> 100). You test one value per partition — typically 0, 50, and 101.",
  },
  {
    lesson_title: "Equivalence Partitioning",
    question: "If a discount applies to purchases of $50-$200, which value is in the valid partition?",
    option_a: "$49",
    option_b: "$125",
    option_c: "$201",
    option_d: "$0",
    answer: "B",
    explanation: "$125 falls within the valid range $50-$200 and represents the valid equivalence partition.",
  },
  {
    lesson_title: "Equivalence Partitioning",
    question: "Can equivalence partitioning be applied to output values?",
    option_a: "No, only to input values",
    option_b: "Yes, outputs can also be partitioned into equivalence classes",
    option_c: "Only to numerical outputs",
    option_d: "Only in automated testing",
    answer: "B",
    explanation: "EP applies to both inputs AND outputs. If a function produces different results in ranges (e.g., 0%, 10%, 20% discount), each output range is a partition.",
  },

  // ══════════════════════════════════════════════════════════════════
  // INTERMEDIATE: BVA
  // ══════════════════════════════════════════════════════════════════
  {
    lesson_title: "Boundary Value Analysis",
    question: "For a field accepting 1-10, which values should be tested using two-value BVA?",
    option_a: "1, 5, 10",
    option_b: "0, 1, 10, 11",
    option_c: "1, 2, 9, 10",
    option_d: "0, 5, 11",
    answer: "B",
    explanation: "Two-value BVA tests: minimum boundary (1), just below minimum (0), maximum boundary (10), just above maximum (11).",
  },
  {
    lesson_title: "Boundary Value Analysis",
    question: "Why are bugs more common at boundaries?",
    option_a: "Developers write fewer tests for boundaries",
    option_b: "Off-by-one errors are common in boundary conditions",
    option_c: "Boundaries have more complex code",
    option_d: "Boundaries require more database queries",
    answer: "B",
    explanation: "Off-by-one errors are extremely common — using < instead of <=, or > instead of >=. BVA targets exactly these boundary conditions.",
  },
  {
    lesson_title: "Boundary Value Analysis",
    question: "What is the advantage of three-value BVA over two-value BVA?",
    option_a: "Fewer test cases",
    option_b: "Also tests values just inside the boundary for extra confidence",
    option_c: "Faster execution",
    option_d: "Requires no test data",
    answer: "B",
    explanation: "Three-value BVA adds values just inside each boundary (min+1 and max-1), giving extra confidence that the valid range is correctly implemented.",
  },
  {
    lesson_title: "Boundary Value Analysis",
    question: "For a username field with 3-15 characters, which values should be tested at the minimum boundary?",
    option_a: "2 characters and 4 characters",
    option_b: "2 characters, 3 characters, 4 characters",
    option_c: "1 character and 3 characters",
    option_d: "3 characters only",
    answer: "B",
    explanation: "Three-value BVA at the minimum: 2 (just below), 3 (minimum boundary), 4 (just above minimum). All three reveal different types of boundary defects.",
  },

  // ══════════════════════════════════════════════════════════════════
  // INTERMEDIATE: Agile Testing
  // ══════════════════════════════════════════════════════════════════
  {
    lesson_title: "Agile Testing & Scrum",
    question: "What is the purpose of the 'Three Amigos' meeting?",
    option_a: "A social team-building activity",
    option_b: "Business, Development, and QA align on requirements before development",
    option_c: "Three developers review each other's code",
    option_d: "Three managers approve the test plan",
    answer: "B",
    explanation: "Three Amigos brings together Business (what?), Developer (how?), and QA (what could go wrong?) to align on requirements before dev starts — preventing expensive misunderstandings.",
  },
  {
    lesson_title: "Agile Testing & Scrum",
    question: "What is the Definition of Done (DoD)?",
    option_a: "The sprint end date",
    option_b: "A checklist that defines when a user story is truly complete",
    option_c: "The number of bugs allowed per release",
    option_d: "The test case pass rate threshold",
    answer: "B",
    explanation: "The DoD is a shared checklist that all team members agree defines 'complete' — e.g., code reviewed, tests passed, QA signed off, documentation updated.",
  },
  {
    lesson_title: "Agile Testing & Scrum",
    question: "In Scrum, what is the main QA anti-pattern?",
    option_a: "Testing too many features",
    option_b: "Treating QA as a gate at the end of the sprint",
    option_c: "Writing too many test cases",
    option_d: "Attending too many meetings",
    answer: "B",
    explanation: "In Agile, QA should test in parallel with development throughout the sprint — not wait until all code is done at the end. Late testing creates sprint bottlenecks.",
  },
  {
    lesson_title: "Agile Testing & Scrum",
    question: "Acceptance criteria in Given/When/Then format is called:",
    option_a: "Test cases",
    option_b: "User stories",
    option_c: "Gherkin",
    option_d: "Sprint goals",
    answer: "C",
    explanation: "Gherkin is the plain-English format using Given/When/Then for writing acceptance criteria and BDD scenarios readable by both technical and non-technical stakeholders.",
  },

  // ══════════════════════════════════════════════════════════════════
  // ADVANCED: Automation Strategy
  // ══════════════════════════════════════════════════════════════════
  {
    lesson_title: "Test Automation Strategy",
    question: "According to the test automation pyramid, what should have the MOST tests?",
    option_a: "E2E tests",
    option_b: "Integration tests",
    option_c: "Unit tests",
    option_d: "UI tests",
    answer: "C",
    explanation: "Unit tests form the pyramid's base — they're the fastest, cheapest, and most numerous. The typical ratio is 70% unit, 20% integration, 10% E2E.",
  },
  {
    lesson_title: "Test Automation Strategy",
    question: "What does ROI mean in the context of test automation?",
    option_a: "Rules Of Implementation",
    option_b: "Return On Investment — the value gained vs. the cost of automating",
    option_c: "Rate Of Increase in test execution",
    option_d: "Risk Of Implementation",
    answer: "B",
    explanation: "ROI in automation = time saved by automation vs. time spent writing/maintaining it. Automate when the savings exceed the investment over the expected lifetime.",
  },
  {
    lesson_title: "Test Automation Strategy",
    question: "Which type of testing should NOT typically be automated?",
    option_a: "Regression testing",
    option_b: "Smoke testing",
    option_c: "Exploratory testing",
    option_d: "API testing",
    answer: "C",
    explanation: "Exploratory testing requires human creativity, intuition, and real-time decision making — it cannot be effectively automated. Automation excels at repetitive, predictable tests.",
  },
  {
    lesson_title: "Test Automation Strategy",
    question: "What is the Page Object Model (POM)?",
    option_a: "A design pattern separating page element locators from test logic",
    option_b: "A tool for recording browser interactions",
    option_c: "A type of API testing framework",
    option_d: "A reporting tool for test results",
    answer: "A",
    explanation: "POM separates page interactions (locators, actions) from test logic. When the UI changes, only the page object is updated — not every test that uses it.",
  },

  // ══════════════════════════════════════════════════════════════════
  // ADVANCED: Selenium
  // ══════════════════════════════════════════════════════════════════
  {
    lesson_title: "Selenium WebDriver",
    question: "Why should Thread.sleep() be avoided in Selenium tests?",
    option_a: "It uses too much memory",
    option_b: "It's not supported in Java",
    option_c: "It wastes time on fast systems and is still unreliable on slow ones",
    option_d: "It prevents screenshots from being taken",
    answer: "C",
    explanation: "Thread.sleep waits a fixed time regardless of when the element is ready — too slow on fast systems and still fails on slow ones. Explicit waits are condition-based and reliable.",
  },
  {
    lesson_title: "Selenium WebDriver",
    question: "Which Selenium locator strategy is most recommended for stability?",
    option_a: "XPath",
    option_b: "CSS class name",
    option_c: "ID or data-testid attribute",
    option_d: "Link text",
    answer: "C",
    explanation: "IDs and data-testid attributes are stable — they're specifically added for testing and don't change with styling or layout refactors.",
  },
  {
    lesson_title: "Selenium WebDriver",
    question: "What does an Explicit Wait do in Selenium?",
    option_a: "Pauses execution for a fixed time",
    option_b: "Waits for a specific condition to be true before proceeding",
    option_c: "Runs all tests simultaneously",
    option_d: "Clears cookies automatically",
    answer: "B",
    explanation: "Explicit wait waits for a specific, testable condition (element visible, clickable, text present) — only waiting as long as needed, up to a maximum timeout.",
  },

  // ══════════════════════════════════════════════════════════════════
  // ADVANCED: Cypress
  // ══════════════════════════════════════════════════════════════════
  {
    lesson_title: "Cypress.io Modern Testing",
    question: "What is the key advantage of Cypress over Selenium?",
    option_a: "Cypress supports more browsers",
    option_b: "Cypress runs inside the browser with automatic waiting — no flakiness",
    option_c: "Cypress is faster to install",
    option_d: "Cypress doesn't require JavaScript",
    answer: "B",
    explanation: "Cypress runs directly inside the browser and automatically waits for elements, animations, and XHR requests — eliminating the main cause of flaky tests.",
  },
  {
    lesson_title: "Cypress.io Modern Testing",
    question: "What does cy.intercept() do?",
    option_a: "Intercepts keyboard input from users",
    option_b: "Intercepts network requests to stub or spy on API calls",
    option_c: "Intercepts console errors",
    option_d: "Intercepts page navigation",
    answer: "B",
    explanation: "cy.intercept() allows you to stub API responses (return fake data) or spy on real requests, enabling tests to control the API layer without hitting real backends.",
  },
  {
    lesson_title: "Cypress.io Modern Testing",
    question: "What is the Cypress best practice for selecting elements?",
    option_a: "Use CSS class names",
    option_b: "Use XPath expressions",
    option_c: "Use data-testid attributes",
    option_d: "Use element position (nth-child)",
    answer: "C",
    explanation: "data-testid attributes are the recommended Cypress selector strategy — they're stable, unaffected by styling changes, and communicate testing intent clearly.",
  },

  // ══════════════════════════════════════════════════════════════════
  // ADVANCED: Playwright
  // ══════════════════════════════════════════════════════════════════
  {
    lesson_title: "Playwright for E2E Testing",
    question: "What makes Playwright unique compared to Cypress for cross-browser testing?",
    option_a: "Playwright only supports Chrome",
    option_b: "Playwright supports real Chromium, Firefox, AND WebKit (Safari)",
    option_c: "Playwright uses a different testing language",
    option_d: "Playwright doesn't support mobile testing",
    answer: "B",
    explanation: "Playwright supports all three major browser engines: Chromium (Chrome/Edge), Firefox, and WebKit (Safari) — real browsers, not just wrappers.",
  },
  {
    lesson_title: "Playwright for E2E Testing",
    question: "What is the Playwright Trace Viewer used for?",
    option_a: "Real-time test monitoring",
    option_b: "Debugging failed tests by viewing step-by-step screenshots and network activity",
    option_c: "Writing test code automatically",
    option_d: "Comparing screenshots pixel by pixel",
    answer: "B",
    explanation: "Trace Viewer shows a full execution trace of a test — every action with DOM snapshots, network requests, and console logs — making CI failures easy to debug.",
  },
  {
    lesson_title: "Playwright for E2E Testing",
    question: "What does 'npx playwright codegen' do?",
    option_a: "Generates a test report",
    option_b: "Records browser interactions and generates test code automatically",
    option_c: "Runs all tests in parallel",
    option_d: "Deploys the app to staging",
    answer: "B",
    explanation: "Codegen records your browser interactions (clicks, typing, navigation) and automatically generates Playwright test code — great for getting started quickly.",
  },

  // ══════════════════════════════════════════════════════════════════
  // ADVANCED: CI/CD
  // ══════════════════════════════════════════════════════════════════
  {
    lesson_title: "CI/CD Pipeline Integration",
    question: "What is the main benefit of running tests in a CI/CD pipeline?",
    option_a: "Tests run faster locally",
    option_b: "Automatic feedback on every code change, preventing regressions from merging",
    option_c: "No need for manual testing",
    option_d: "Developers don't need to write unit tests",
    answer: "B",
    explanation: "CI/CD runs tests automatically on every commit/PR, giving developers instant feedback and preventing broken code from reaching main branches or production.",
  },
  {
    lesson_title: "CI/CD Pipeline Integration",
    question: "What is a 'quality gate' in CI/CD?",
    option_a: "A security checkpoint for deployments",
    option_b: "A condition that must pass before code can merge or deploy",
    option_c: "A manual review step",
    option_d: "A load balancer configuration",
    answer: "B",
    explanation: "Quality gates are automated checks (test pass rate, coverage thresholds, no critical bugs) that must pass before code can proceed to the next stage of the pipeline.",
  },
  {
    lesson_title: "CI/CD Pipeline Integration",
    question: "What is the 'fail-fast' strategy in CI testing?",
    option_a: "Run only the fastest tests",
    option_b: "Skip failed tests and continue",
    option_c: "Stop the pipeline immediately when a critical test fails",
    option_d: "Delete failed test results",
    answer: "C",
    explanation: "Fail-fast stops the pipeline at the first critical failure — saving compute time and giving developers faster feedback about what's broken.",
  },

  // ══════════════════════════════════════════════════════════════════
  // ADVANCED: Performance Testing
  // ══════════════════════════════════════════════════════════════════
  {
    lesson_title: "Performance Testing with k6",
    question: "In k6, what are 'Virtual Users' (VUs)?",
    option_a: "Simulated users that execute test scripts concurrently",
    option_b: "Actual registered test users in the database",
    option_c: "Browser extensions for testing",
    option_d: "Performance metrics",
    answer: "A",
    explanation: "Virtual Users are k6's simulated concurrent users. Each VU runs your script repeatedly, allowing you to simulate real-world concurrent load.",
  },
  {
    lesson_title: "Performance Testing with k6",
    question: "What does p(95) mean in k6 metrics?",
    option_a: "95% of users are happy",
    option_b: "95% of requests completed faster than this value",
    option_c: "95% of tests passed",
    option_d: "The test ran for 95 seconds",
    answer: "B",
    explanation: "p(95) is the 95th percentile — 95% of requests completed in less time than this value. It's a standard SLA metric for API performance.",
  },
  {
    lesson_title: "Performance Testing with k6",
    question: "What is a 'threshold' in k6?",
    option_a: "The maximum number of virtual users",
    option_b: "A pass/fail criterion for performance metrics",
    option_c: "The test duration limit",
    option_d: "A database connection limit",
    answer: "B",
    explanation: "Thresholds define acceptable performance criteria. If p(95) < 500ms is a threshold and p(95) = 600ms, the test fails — enabling quality gates in CI.",
  },

  // ══════════════════════════════════════════════════════════════════
  // ADVANCED: Security Testing
  // ══════════════════════════════════════════════════════════════════
  {
    lesson_title: "Security Testing & OWASP Top 10",
    question: "What is SQL Injection?",
    option_a: "A way to speed up database queries",
    option_b: "Inserting malicious SQL code through input fields to manipulate the database",
    option_c: "A database migration technique",
    option_d: "A method for backing up databases",
    answer: "B",
    explanation: "SQL injection inserts malicious SQL through user input fields. If inputs aren't sanitized, attackers can read, modify, or delete database data.",
  },
  {
    lesson_title: "Security Testing & OWASP Top 10",
    question: "What is IDOR (Insecure Direct Object Reference)?",
    option_a: "A type of SQL injection",
    option_b: "Accessing other users' resources by changing an ID in the request",
    option_c: "A method for cross-site scripting",
    option_d: "A broken authentication pattern",
    answer: "B",
    explanation: "IDOR occurs when users can access another user's data by changing a predictable identifier (like /api/users/123 → /api/users/456) without authorization checks.",
  },
  {
    lesson_title: "Security Testing & OWASP Top 10",
    question: "What is the OWASP Top 10?",
    option_a: "The 10 most popular web frameworks",
    option_b: "The 10 most critical web application security risks",
    option_c: "10 best practices for API design",
    option_d: "10 performance testing tools",
    answer: "B",
    explanation: "OWASP Top 10 is the industry-standard list of the most critical web application security risks, updated regularly by the Open Web Application Security Project.",
  },
  {
    lesson_title: "Security Testing & OWASP Top 10",
    question: "What is XSS (Cross-Site Scripting)?",
    option_a: "Styling web pages with CSS",
    option_b: "Injecting malicious scripts into web pages viewed by other users",
    option_c: "Cross-server communication",
    option_d: "A type of SQL injection",
    answer: "B",
    explanation: "XSS injects malicious JavaScript into web pages. When other users view the page, the script executes in their browser, potentially stealing cookies or redirecting them.",
  },

  // ══════════════════════════════════════════════════════════════════
  // ADVANCED: BDD
  // ══════════════════════════════════════════════════════════════════
  {
    lesson_title: "BDD with Cucumber & Gherkin",
    question: "What does BDD stand for?",
    option_a: "Bug-Driven Development",
    option_b: "Behavior-Driven Development",
    option_c: "Build-Deploy-Debug",
    option_d: "Back-end Development Design",
    answer: "B",
    explanation: "BDD (Behavior-Driven Development) focuses on system behavior from the user's perspective, using plain language scenarios shared between business, dev, and QA.",
  },
  {
    lesson_title: "BDD with Cucumber & Gherkin",
    question: "What is the Gherkin keyword used to describe the context or starting state?",
    option_a: "When",
    option_b: "Then",
    option_c: "Given",
    option_d: "And",
    answer: "C",
    explanation: "Given establishes the context — the initial state before an action occurs. Example: 'Given the user is on the login page and is registered'.",
  },
  {
    lesson_title: "BDD with Cucumber & Gherkin",
    question: "What does 'Scenario Outline' with 'Examples' enable in Gherkin?",
    option_a: "Combining multiple scenarios into one",
    option_b: "Running the same scenario with multiple data sets",
    option_c: "Skipping scenarios in CI",
    option_d: "Adding code comments",
    answer: "B",
    explanation: "Scenario Outline + Examples creates data-driven tests — the same scenario runs once per row in the Examples table with different input values.",
  },
  {
    lesson_title: "BDD with Cucumber & Gherkin",
    question: "What are 'Step Definitions' in Cucumber?",
    option_a: "Comments in Gherkin scenarios",
    option_b: "The code that maps Gherkin steps to actual test actions",
    option_c: "Database setup scripts",
    option_d: "Test configuration files",
    answer: "B",
    explanation: "Step definitions are the code (TypeScript, Java, etc.) that implements each Gherkin step. They bridge the plain-English scenarios and the actual test automation code.",
  },

  // ══════════════════════════════════════════════════════════════════
  // ADVANCED: QA Leadership
  // ══════════════════════════════════════════════════════════════════
  {
    lesson_title: "QA Leadership & Test Management",
    question: "What is 'Defect Leakage'?",
    option_a: "Bugs that take too long to fix",
    option_b: "Bugs that escape to production that should have been caught in QA",
    option_c: "Duplicate bug reports",
    option_d: "Bugs found in third-party components",
    answer: "B",
    explanation: "Defect leakage measures how many bugs escaped QA and were found in production. Lower leakage = better QA effectiveness. Formula: (Prod bugs / Total bugs) × 100.",
  },
  {
    lesson_title: "QA Leadership & Test Management",
    question: "What is a QA OKR?",
    option_a: "A type of test case",
    option_b: "An Objective with measurable Key Results to track QA team goals",
    option_c: "A bug severity classification",
    option_d: "An automated test framework",
    answer: "B",
    explanation: "OKRs (Objectives & Key Results) are goal-setting frameworks. For QA: Objective = 'Improve release quality'; Key Results = measurable metrics like defect leakage < 2%.",
  },
  {
    lesson_title: "QA Leadership & Test Management",
    question: "When communicating quality to executives, QA leaders should:",
    option_a: "Use technical jargon like 'p95 latency' and 'code coverage'",
    option_b: "Translate metrics into business impact (time/money/customer experience)",
    option_c: "Only report when there are major incidents",
    option_d: "Share all raw test data",
    answer: "B",
    explanation: "Executives care about business outcomes, not technical metrics. Translate: 'We prevented 3 critical bugs from reaching production, saving ~40 hours of incident response'.",
  },
  {
    lesson_title: "QA Leadership & Test Management",
    question: "What is 'Mean Time to Detect' (MTTD) in QA?",
    option_a: "How long it takes to write a test case",
    option_b: "Average time from a bug being introduced to it being discovered",
    option_c: "How long automated tests take to run",
    option_d: "The average number of bugs per release",
    answer: "B",
    explanation: "MTTD measures how quickly QA finds bugs after they're introduced. Lower MTTD means QA is catching issues faster, reducing the cost of fixes.",
  },
];

async function seedQuizzes() {
  const client = await pool.connect();
  try {
    await client.query("BEGIN");

    let inserted = 0;
    let skipped = 0;

    for (const quiz of quizzes) {
      const lessonRes = await client.query(
        "SELECT id FROM lessons WHERE title = $1 LIMIT 1",
        [quiz.lesson_title]
      );

      if (lessonRes.rows.length === 0) {
        console.warn(`⚠️  Lesson not found: "${quiz.lesson_title}" — skipping`);
        skipped++;
        continue;
      }

      const lessonId = lessonRes.rows[0].id;

      await client.query(
        `INSERT INTO quizzes (lesson_id, question, option_a, option_b, option_c, option_d, answer, explanation)
         VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
         ON CONFLICT DO NOTHING`,
        [
          lessonId,
          quiz.question,
          quiz.option_a,
          quiz.option_b,
          quiz.option_c,
          quiz.option_d,
          quiz.answer,
          quiz.explanation,
        ]
      );
      inserted++;
    }

    await client.query("COMMIT");
    console.log(`✅ Quiz seed complete — ${inserted} inserted, ${skipped} skipped`);

    // Summary by lesson
    const summary = await client.query(`
      SELECT l.title, COUNT(q.id) as quiz_count
      FROM lessons l
      LEFT JOIN quizzes q ON q.lesson_id = l.id
      GROUP BY l.id, l.title
      ORDER BY l.id
    `);

    console.log("\n📊 Quiz counts per lesson:");
    for (const row of summary.rows) {
      const count = parseInt(row.quiz_count);
      const icon = count >= 10 ? "✅" : count > 0 ? "⚠️ " : "❌";
      console.log(`  ${icon} ${row.title}: ${count} questions`);
    }
  } catch (err) {
    await client.query("ROLLBACK");
    console.error("❌ Seed failed:", err);
    throw err;
  } finally {
    client.release();
    await pool.end();
  }
}

seedQuizzes();
