import type { LessonRow } from "../lesson-types";

export const bugReportingFundamentalsLesson: LessonRow = {
  level_slug: "beginner",
  title: "Bug Reporting Fundamentals",
  description: "Write bug reports that developers actually want to read and can act on",
  step_order: 6,
  duration_min: 12,
  content: `## Bug Reporting Fundamentals

A bug report is a document that communicates a defect to the development team. A great bug report gets the bug fixed faster; a poor one wastes everyone's time and causes disputes.

### The Anatomy of a Bug Report

**Structured reference**

- **Bug ID**: Auto-generated by the tracking tool (e.g., BUG-2341)
- **Title**: Concise summary: what's broken + under what condition
- **Environment**: OS, browser, app version, URL, device
- **Severity**: How bad is the technical or user impact?
- **Priority**: How urgently does it need fixing?
- **Steps to Reproduce**: Exact, numbered steps to trigger the bug
- **Expected Result**: What should happen according to the spec
- **Actual Result**: What actually happens
- **Attachments**: Screenshots, screen recordings, logs, HAR files
- **Reproducibility**: Always / Intermittent / Rare
- **Assigned To**: Developer responsible for the fix

### Severity vs Priority

These are different concepts that are often confused:

**Severity** = technical or user impact on the system
**Priority** = business urgency of the fix (decided by stakeholders)

**Structured reference**

- **Critical**: System crash, data loss, security breach, cannot proceed
- **High**: Major feature broken, no workaround available
- **Medium**: Feature impaired, workaround exists
- **Low**: Cosmetic, minor UI issue, spelling error

A bug can be **high severity but low priority** (e.g., crash on a rarely used admin page).
A bug can be **low severity but high priority** (e.g., CEO's name misspelled on the login screen).

### Writing a Great Bug Title

The title formula: **[Component] [Action/Condition] causes [Failure]**

❌ Bad: "Login doesn't work"
✅ Good: "Login button unresponsive when email contains a + character"

❌ Bad: "Error on profile page"
✅ Good: "Profile photo upload returns 500 error when file size exceeds 2 MB"

❌ Bad: "Cart broken"
✅ Good: "Cart quantity resets to 1 after page refresh on iOS Safari 17"

### Steps to Reproduce — The Most Important Section

Steps must be **exact, numbered, and include test data**. A developer should be able to follow them and reproduce the bug without asking any questions.

\`\`\`
Steps to Reproduce:
1. Go to https://staging.app.com/login
2. Enter email: test+user@example.com
3. Enter password: Abc123!
4. Click "Login"
5. Observe: Button spins indefinitely, no error message, no redirect

Expected: User is redirected to /dashboard
Actual: Login button shows a loading spinner forever. Network tab shows no request sent.
\`\`\`

### Reproducibility

Always state how reliably the bug reproduces:
- **Always (100%)** — reproducible every single time with the given steps
- **Intermittent** — reproduces ~50% of the time; document conditions
- **Rare** — happened once or twice; hard to reproduce; include logs

For intermittent bugs, attach timestamps, logs, and any environmental variations observed.

### Bug Report Quality Checklist

Before submitting:
- [ ] Title describes condition and failure, not just symptoms
- [ ] All environment details captured (OS, browser version, app version)
- [ ] Steps are numbered and specific enough to reproduce independently
- [ ] Exact test data included (real values, not "some data")
- [ ] Expected and actual results are both documented
- [ ] Screenshot or screen recording attached
- [ ] Severity and priority set appropriately
- [ ] Checked for duplicates before submitting

### Bug Reporting in JIRA

JIRA is the most common bug tracking tool. A typical JIRA bug issue includes:

- **Issue Type**: Bug
- **Summary** (= Title): Concise condition + failure
- **Description**: Steps, expected, actual, environment
- **Severity/Priority**: Custom fields or labels
- **Attachments**: Images, videos, log files
- **Linked Issues**: Blocks / Is blocked by / Duplicates

**Labels to use:** \`regression\`, \`blocker\`, \`security\`, \`intermittent\`, \`needs-repro\`

### Root Cause vs Symptom

Report the **symptom** (what the user sees) as the title. The root cause is for the developer to investigate — but if you know it, include it in the description.

**Symptom (report this):** "Order confirmation email not sent after successful checkout"
**Root cause (investigation):** "Email queue service is timing out due to a misconfigured connection pool"

### API Bug Reports

For API defects, include the full request and response:

\`\`\`
Endpoint: POST /api/orders
Request Headers:
  Authorization: Bearer <token>
  Content-Type: application/json
Request Body:
  { "productId": 42, "quantity": 1 }

Expected Response: 201 Created with order ID
Actual Response: 500 Internal Server Error
  { "error": "Cannot read property 'price' of undefined" }

Stack trace attached in: error-log-2024-01-15.txt
\`\`\`

### Real-World Use Cases

#### Case 1: UI bug report

The Save button overlaps the address field on iPhone width. QA includes device, browser, viewport, screenshot, steps, expected layout, and actual layout.

#### Case 2: API bug report

A POST request returns 500 when the phone field is missing. QA includes endpoint, request body, headers, response body, status code, and expected 400 validation response.

#### Case 3: Intermittent bug report

Payment confirmation appears only 6 out of 10 attempts. QA records frequency, timestamps, test cards, network condition, and logs to help developers find timing issues.

### How to Apply This in Real QA Work

A bug report is a compact investigation report that helps the team understand impact, reproduce the problem, and make a good fix decision.

#### Practical Workflow

- Reproduce the issue at least once, then simplify the steps to the smallest path that still triggers the bug.
- Write the title as condition plus failure.
- Include environment, test data, expected result, actual result, attachments, logs, and reproducibility rate.
- State severity based on technical or user impact; let priority reflect release timing and business urgency.

#### Common Mistakes to Avoid

- Submitting screenshots without steps to reproduce.
- Mixing several unrelated failures in one bug report.
- Calling a bug critical because it is annoying, even when user or business impact is low.
- Reporting the root cause assumption in the title instead of the observable symptom.

### Interview Questions

**Q: What is the difference between severity and priority?**
Severity is the technical or user impact of the defect (Critical/High/Medium/Low). Priority is the business urgency of when it needs to be fixed. A cosmetic bug on the CEO's profile page could be low severity but high priority.

**Q: What makes a good bug report?**
A good bug report has a descriptive title (condition + failure), exact reproducible steps, specific test data, expected and actual results, environment details, and relevant attachments. The developer should be able to reproduce it without asking any follow-up questions.

**Q: What information should always be included in a bug report?**
Environment (OS, browser, app version), steps to reproduce with exact test data, expected result, actual result, severity/priority, reproducibility rate, and attachments (screenshot, video, or logs).

**Q: How do you handle an intermittent bug that's hard to reproduce?**
Document every attempt: what steps, what data, what environment, what time, and what result. Capture logs and network traffic. Describe the failure frequency. Even partial reproduction evidence helps developers investigate.

#### Practice Prompt

Rewrite the title "Login broken" into a precise bug title with condition, location, and visible failure.`,
};
