import type { LessonRow } from "../lesson-types";

export const bugReportingFundamentalsLesson: LessonRow = {
  level_slug: "beginner",
  title: "Bug Reporting Fundamentals",
  description: "Write bug reports that developers actually want to read",
  step_order: 6,
  duration_min: 10,
  content: `## Bug Reporting Fundamentals

A bug report is a document that communicates a defect to the development team. A great bug report gets the bug fixed faster; a poor one wastes everyone's time.

### The Anatomy of a Bug Report


**Structured reference**

- **Bug ID**: Auto-generated by the tracking tool
- **Title**: Concise summary (what's broken + where)
- **Environment**: OS, browser, app version, URL
- **Severity**: How bad is the impact?
- **Priority**: How urgently does it need fixing?
- **Steps to Reproduce**: Exact steps to trigger the bug
- **Expected Result**: What should happen
- **Actual Result**: What actually happens
- **Attachments**: Screenshots, videos, logs
- **Assigned To**: Developer responsible for the fix


### Severity vs Priority

These are different! A bug can be high severity but low priority, or vice versa.


**Structured reference**

- **High Severity**
  - High Priority: App crashes on checkout
  - Low Priority: Typo on rarely-visited page
- **Low Severity**
  - High Priority: CEO's name misspelled on login
  - Low Priority: Minor color misalignment


**Severity** = impact on the system
**Priority** = urgency of the fix (business decision)

### Writing a Great Title

❌ Bad: "Login doesn't work"
✅ Good: "Login button unresponsive when email contains special characters"

❌ Bad: "Error on profile page"
✅ Good: "Profile photo upload fails with 500 error when file size exceeds 2MB"

### Steps to Reproduce — The Key to a Good Bug Report

Be precise, numbered, and include exact data:

1. Go to https://app.example.com/login
2. Enter email: \`test+user@example.com\`
3. Enter password: \`Abc123!\`
4. Click "Login"
5. **Observe:** Button becomes unresponsive, no error message

### Reproducibility

Always state how often the bug reproduces:
- **Always (100%)** — reproducible every single time
- **Intermittent** — reproducible ~50% of the time
- **Rare** — happened once or twice, hard to reproduce


### Real-World Use Cases

#### Case 1: UI bug report

The Save button overlaps the address field on iPhone width. QA includes device, browser, viewport, screenshot, steps, expected layout, and actual layout.

#### Case 2: API bug report

A POST request returns 500 when the phone field is missing. QA includes endpoint, request body, headers, response body, status code, and expected 400 validation response.

#### Case 3: Intermittent bug report

Payment confirmation appears only 6 out of 10 attempts. QA records frequency, timestamps, test cards, network condition, and logs to help developers find timing issues.

### How to Apply This in Real QA Work

A bug report is not just a complaint. It is a compact investigation report that helps the team understand impact, reproduce the problem, and make a good fix decision.

#### Practical Workflow

- Reproduce the issue at least once, then simplify the steps to the smallest path that still triggers the bug.
- Write the title as condition plus failure, for example Checkout button stays disabled when coupon has lowercase letters.
- Include environment, test data, expected result, actual result, attachments, logs, and reproducibility rate.
- State severity based on technical or user impact; let priority reflect release timing and business urgency.

#### Common Mistakes to Avoid

- Submitting screenshots without steps to reproduce.
- Mixing several unrelated failures in one bug report.
- Calling a bug critical because it is annoying, even when user or business impact is low.

#### Practice Prompt

Rewrite the title Login broken into a precise bug title with condition, location, and visible failure.`,
};
