import type { LessonRow } from "../lesson-types";

export const bugReportingFundamentalsLesson: LessonRow = {
  level_slug: "beginner",
  title: "Bug Reporting Fundamentals",
  description: "Write bug reports that developers actually want to read",
  step_order: 6,
  duration_min: 10,
  content: `## Bug Reporting Fundamentals

A bug report is a document that communicates a defect to the development team. A great bug report gets the bug fixed faster; a poor one wastes everyone's time.

### The Anatomy of a Bug Report

| Field | Description |
|-------|-------------|
| **Bug ID** | Auto-generated by the tracking tool |
| **Title** | Concise summary (what's broken + where) |
| **Environment** | OS, browser, app version, URL |
| **Severity** | How bad is the impact? |
| **Priority** | How urgently does it need fixing? |
| **Steps to Reproduce** | Exact steps to trigger the bug |
| **Expected Result** | What should happen |
| **Actual Result** | What actually happens |
| **Attachments** | Screenshots, videos, logs |
| **Assigned To** | Developer responsible for the fix |

### Severity vs Priority

These are different! A bug can be high severity but low priority, or vice versa.

| | High Priority | Low Priority |
|--|---|---|
| **High Severity** | App crashes on checkout | Typo on rarely-visited page |
| **Low Severity** | CEO's name misspelled on login | Minor color misalignment |

**Severity** = impact on the system
**Priority** = urgency of the fix (business decision)

### Writing a Great Title

❌ Bad: "Login doesn't work"
✅ Good: "Login button unresponsive when email contains special characters"

❌ Bad: "Error on profile page"
✅ Good: "Profile photo upload fails with 500 error when file size exceeds 2MB"

### Steps to Reproduce — The Key to a Good Bug Report

Be precise, numbered, and include exact data:

1. Go to https://app.example.com/login
2. Enter email: \`test+user@example.com\`
3. Enter password: \`Abc123!\`
4. Click "Login"
5. **Observe:** Button becomes unresponsive, no error message

### Reproducibility

Always state how often the bug reproduces:
- **Always (100%)** — reproducible every single time
- **Intermittent** — reproducible ~50% of the time
- **Rare** — happened once or twice, hard to reproduce`,
};
