import type { QuizRow } from "../../quiz-types";

export const whatIsSoftwareTestingQuizzes: QuizRow[] = [
  {
    lesson_title: "What is Software Testing?",
    question: "What is the primary goal of software testing?",
    option_a: "To prove the software has no bugs",
    option_b: "To find defects and evaluate software quality",
    option_c: "To replace code reviews",
    option_d: "To write user documentation",
    answer: "B",
    explanation: "Testing evaluates quality and finds defects. It cannot prove a system has zero bugs — only that known scenarios pass.",
  },
  {
    lesson_title: "What is Software Testing?",
    question: "What is the difference between an error and a defect?",
    option_a: "They are the same thing",
    option_b: "An error is a human mistake that causes a defect in code",
    option_c: "A defect is a human mistake and an error is in the system",
    option_d: "An error only occurs in production",
    answer: "B",
    explanation: "An error is the human mistake (typo, logic flaw). The defect is the resulting fault in the code. A failure is when that defect causes observable incorrect behavior.",
  },
  {
    lesson_title: "What is Software Testing?",
    question: "Which statement best describes software quality?",
    option_a: "The software compiles without errors",
    option_b: "The software has 100% code coverage",
    option_c: "The software meets specified requirements and user expectations",
    option_d: "The software passes all performance tests",
    answer: "C",
    explanation: "Quality is about meeting requirements AND user expectations. Passing some tests or compiling does not guarantee quality.",
  },
  {
    lesson_title: "What is Software Testing?",
    question: "When is a bug most expensive to fix?",
    option_a: "During requirements phase",
    option_b: "During design phase",
    option_c: "During development",
    option_d: "After release to production",
    answer: "D",
    explanation: "The cost of fixing a bug grows exponentially the later it is found. Bugs found in production can cost 100x more than bugs found during requirements.",
  },
  {
    lesson_title: "What is Software Testing?",
    question: "What is a software failure?",
    option_a: "A mistake made by a programmer",
    option_b: "A flaw introduced into the source code",
    option_c: "Observable incorrect behavior when running the software",
    option_d: "A bug reported by a user",
    answer: "C",
    explanation: "A failure is the manifestation of a defect — observable incorrect system behavior. Errors cause defects; defects may cause failures.",
  },
  {
    lesson_title: "What is Software Testing?",
    question: "What does a QA engineer primarily advocate for?",
    option_a: "Faster development velocity",
    option_b: "Quality throughout the entire project",
    option_c: "Writing all the code",
    option_d: "Managing project timelines",
    answer: "B",
    explanation: "QA engineers champion quality throughout the SDLC — from reviewing requirements to verifying fixes in production.",
  },
  {
    lesson_title: "What is Software Testing?",
    question: "Testing can guarantee software is completely bug-free. True or False?",
    option_a: "True — exhaustive testing covers everything",
    option_b: "False — exhaustive testing is impossible for most systems",
    option_c: "True — if 100% code coverage is achieved",
    option_d: "True — if both manual and automated testing are used",
    answer: "B",
    explanation: "Exhaustive testing (testing every possible input) is impractical for any non-trivial system. Testing reduces risk but cannot guarantee zero bugs.",
  },
  {
    lesson_title: "What is Software Testing?",
    question: "What is the distinction between testing and debugging?",
    option_a: "Testing and debugging are the same activity",
    option_b: "Testing finds that a problem exists; debugging finds and fixes the cause",
    option_c: "Debugging is done by QA; testing is done by developers",
    option_d: "Testing fixes bugs; debugging reports them",
    answer: "B",
    explanation: "Testing is about finding defects. Debugging is about diagnosing the root cause and fixing it. Different skills, often done by different people.",
  },
  {
    lesson_title: "What is Software Testing?",
    question: "Which of these is a non-functional requirement?",
    option_a: "The user can reset their password",
    option_b: "The checkout form validates email format",
    option_c: "The login page must load within 2 seconds",
    option_d: "Admin users can view all reports",
    answer: "C",
    explanation: "Non-functional requirements describe HOW the system performs (speed, security, usability), not WHAT it does. Load time is a performance (non-functional) requirement.",
  },
  {
    lesson_title: "What is Software Testing?",
    question: "What is 'verification' in software testing?",
    option_a: "Are we building the right product?",
    option_b: "Are we building the product right?",
    option_c: "Is the product deployed correctly?",
    option_d: "Does the product satisfy user needs?",
    answer: "B",
    explanation: "Verification checks that the product is built correctly (reviews, inspections, walkthroughs). Validation checks that the right product was built (meeting user needs).",
  },
  {
    lesson_title: "What is Software Testing?",
    question: "Your team shipped a release and 3 customers immediately report the checkout flow is broken. What type of testing should have caught this before release?",
    option_a: "Unit testing — developers should have caught this in their tests",
    option_b: "Regression testing — verifying existing flows still work after changes",
    option_c: "Performance testing — the system couldn't handle the user load",
    option_d: "UAT — customers should be involved in testing",
    answer: "B",
    explanation: "Regression testing verifies that existing functionality still works after new changes are introduced. A broken checkout after a release is a classic regression that a regression suite should catch.",
  },
  {
    lesson_title: "What is Software Testing?",
    question: "A developer says 'all unit tests pass, so we don't need QA testing.' What is the strongest counterargument?",
    option_a: "Unit tests are written by developers who make mistakes",
    option_b: "Unit tests verify individual functions in isolation but do not test integration, user flows, or real-world scenarios",
    option_c: "Unit tests run too fast to find real bugs",
    option_d: "QA testing is required by law",
    answer: "B",
    explanation: "Unit tests check isolated functions. They can't verify that components work together correctly, that the UI behaves as expected, or that the system meets user needs — those require higher-level testing.",
  },
  {
    lesson_title: "What is Software Testing?",
    question: "What is the 'pesticide paradox' in software testing?",
    option_a: "Testing tools become obsolete over time",
    option_b: "If you run the same tests repeatedly, they stop finding new bugs",
    option_c: "Developers fix bugs faster when QA tests more",
    option_d: "Bugs multiply when code is not tested regularly",
    answer: "B",
    explanation: "The pesticide paradox means that re-running the same tests repeatedly yields diminishing returns — bugs grow 'resistant'. To find new defects, tests must be reviewed and updated regularly.",
  },
  {
    lesson_title: "What is Software Testing?",
    question: "You have 100 test cases but only 2 hours before a critical release. How do you decide which tests to run first?",
    option_a: "Run tests alphabetically by test case ID",
    option_b: "Run the fastest tests first to maximize coverage count",
    option_c: "Run tests that cover the highest-risk areas and core user flows first",
    option_d: "Run the tests that failed most recently",
    answer: "C",
    explanation: "Risk-based prioritization runs tests that cover the most critical business flows and high-risk areas first. This ensures the most important functionality is verified within the time constraint.",
  },
  {
    lesson_title: "What is Software Testing?",
    question: "What does 'quality cannot be tested in' mean?",
    option_a: "QA teams cannot improve software quality",
    option_b: "Testing alone cannot create quality — it must be built into the process from the start",
    option_c: "Code quality tools are unreliable",
    option_d: "Quality is subjective and cannot be measured",
    answer: "B",
    explanation: "Testing reveals defects but doesn't create quality. Quality must be built in through good requirements, design, code reviews, and development practices. Testing is a safety net, not a quality factory.",
  },
];
