import type { QuizRow } from "../../quiz-types";

export const softwareDevelopmentLifeCycleSdlcQuizzes: QuizRow[] = [
  {
    lesson_title: "Software Development Life Cycle (SDLC)",
    question: "In traditional Waterfall SDLC, when does testing typically begin?",
    option_a: "During requirements gathering",
    option_b: "After the design phase",
    option_c: "After all coding is complete",
    option_d: "During deployment",
    answer: "C",
    explanation: "In classic Waterfall, testing is a separate phase that starts only after development is complete — one of its major drawbacks.",
  },
  {
    lesson_title: "Software Development Life Cycle (SDLC)",
    question: "The V-Model pairs each development phase with a corresponding testing phase. Which testing phase pairs with the Requirements phase?",
    option_a: "Unit Testing",
    option_b: "Integration Testing",
    option_c: "System Testing",
    option_d: "Acceptance Testing",
    answer: "D",
    explanation: "In V-Model: Requirements ↔ Acceptance Testing. System Design ↔ System Testing. Architecture ↔ Integration Testing. Coding ↔ Unit Testing.",
  },
  {
    lesson_title: "Software Development Life Cycle (SDLC)",
    question: "In Agile SDLC, when does testing occur?",
    option_a: "Only at the end of each sprint",
    option_b: "Only during dedicated test sprints",
    option_c: "Throughout every sprint, in parallel with development",
    option_d: "After the product backlog is complete",
    answer: "C",
    explanation: "Agile promotes continuous testing within every sprint. QA works in parallel with development, not after.",
  },
  {
    lesson_title: "Software Development Life Cycle (SDLC)",
    question: "What is the main disadvantage of Waterfall SDLC for QA?",
    option_a: "Too many meetings",
    option_b: "Bugs are discovered very late, making them expensive to fix",
    option_c: "No documentation is produced",
    option_d: "Developers don't write unit tests",
    answer: "B",
    explanation: "Waterfall's sequential nature means bugs found in the testing phase were introduced much earlier, making them expensive to fix.",
  },
  {
    lesson_title: "Software Development Life Cycle (SDLC)",
    question: "What is a sprint in Agile?",
    option_a: "A full product release cycle",
    option_b: "A time-boxed iteration (typically 2–4 weeks) that produces shippable software",
    option_c: "A planning meeting",
    option_d: "A bug-fixing period",
    answer: "B",
    explanation: "A sprint is a fixed-length iteration in Scrum (typically 2–4 weeks) that results in a potentially shippable product increment.",
  },
  {
    lesson_title: "Software Development Life Cycle (SDLC)",
    question: "During which SDLC phase should QA engineers review requirements?",
    option_a: "Only during the testing phase",
    option_b: "As early as the requirements gathering phase",
    option_c: "After deployment",
    option_d: "Only when developers ask",
    answer: "B",
    explanation: "QA should be involved from the requirements phase to identify ambiguous, incomplete, or untestable requirements — catching issues when they're cheapest to fix.",
  },
  {
    lesson_title: "Software Development Life Cycle (SDLC)",
    question: "What is meant by 'shift-left testing'?",
    option_a: "Moving testers to a different team",
    option_b: "Starting testing activities earlier in the SDLC",
    option_c: "Using left-hand navigations in test management tools",
    option_d: "Reducing test case count",
    answer: "B",
    explanation: "Shift-left means moving testing activities earlier in the development process — catching defects sooner when they're cheaper to fix.",
  },
  {
    lesson_title: "Software Development Life Cycle (SDLC)",
    question: "Which SDLC phase produces the Test Plan?",
    option_a: "Requirements Gathering",
    option_b: "System Design",
    option_c: "Test Planning within STLC (runs parallel to System Design)",
    option_d: "Maintenance",
    answer: "C",
    explanation: "The Test Plan is created during the Test Planning phase of STLC, which runs in parallel with the System Design phase of SDLC.",
  },
  {
    lesson_title: "Software Development Life Cycle (SDLC)",
    question: "What makes Agile better suited for QA compared to Waterfall?",
    option_a: "Agile has no testing requirements",
    option_b: "Agile allows continuous testing and early defect detection every sprint",
    option_c: "Agile requires less documentation",
    option_d: "Agile uses only automated testing",
    answer: "B",
    explanation: "Agile's iterative nature means QA continuously tests within each sprint, finding and fixing bugs much earlier than in Waterfall.",
  },
  {
    lesson_title: "Software Development Life Cycle (SDLC)",
    question: "In which SDLC model does every development phase have a corresponding testing phase planned in advance?",
    option_a: "Waterfall",
    option_b: "Agile",
    option_c: "V-Model",
    option_d: "Spiral",
    answer: "C",
    explanation: "The V-Model is structured so each development phase (requirements, design, coding) has a corresponding test phase planned simultaneously — enabling early test preparation.",
  },
  {
    lesson_title: "Software Development Life Cycle (SDLC)",
    question: "A PM says 'we'll handle QA after all features are built.' Why is this a red flag from a QA perspective?",
    option_a: "QA will have too much work to do",
    option_b: "Defects found late are far more expensive to fix and may delay the release significantly",
    option_c: "Developers will stop writing unit tests",
    option_d: "The product owner will lose confidence in the team",
    answer: "B",
    explanation: "Testing after all features are built mirrors the Waterfall anti-pattern. Defects found late require rework across multiple completed features, are expensive to fix, and compress the release timeline.",
  },
  {
    lesson_title: "Software Development Life Cycle (SDLC)",
    question: "In Agile, what is the QA engineer's primary focus during the development days of a sprint?",
    option_a: "Writing the test plan for the next sprint",
    option_b: "Reviewing requirements, writing test cases, and testing features as they are completed by developers",
    option_c: "Waiting for all features to be complete before starting any testing",
    option_d: "Attending only the daily standup",
    answer: "B",
    explanation: "In Agile, QA works in parallel with development — reviewing acceptance criteria early, preparing test cases, and testing each story as soon as it's dev-complete, not waiting until the sprint end.",
  },
  {
    lesson_title: "Software Development Life Cycle (SDLC)",
    question: "You join a Waterfall project. Testing is scheduled to begin in week 8 of a 10-week project. What risk do you flag to the team?",
    option_a: "Not enough time to write test cases",
    option_b: "Only 2 weeks to find and fix bugs means any significant defects could miss the release",
    option_c: "There will be too many testers on the team",
    option_d: "The test environment won't be ready",
    answer: "B",
    explanation: "With only 20% of the timeline remaining for testing and fixing, any non-trivial defects discovered will either ship or delay the project — the core risk of late-phase testing.",
  },
  {
    lesson_title: "Software Development Life Cycle (SDLC)",
    question: "What is a 'release candidate' build?",
    option_a: "The first internal build given to developers",
    option_b: "A build that has passed all testing and is potentially ready for production release",
    option_c: "A build that is only for stakeholder demos",
    option_d: "A debug build with extra logging enabled",
    answer: "B",
    explanation: "A release candidate is a build that has passed all planned testing activities and is considered production-ready. It's the final candidate before the official release.",
  },
  {
    lesson_title: "Software Development Life Cycle (SDLC)",
    question: "What is the key advantage of the V-Model over standard Waterfall for QA teams?",
    option_a: "QA can skip writing test cases",
    option_b: "Testing activities and test preparation begin in parallel with development phases, not after",
    option_c: "All testing is automated by default",
    option_d: "Requirements never change in V-Model",
    answer: "B",
    explanation: "In V-Model, QA starts designing tests (acceptance test cases, system test cases) during the corresponding development phases. This means test assets are ready when code is complete, reducing the total timeline.",
  },
];
