import type { QuizRow } from "../../quiz-types";

export const softwareDevelopmentLifeCycleSdlcQuizzes: QuizRow[] = [
  {
    lesson_title: "Software Development Life Cycle (SDLC)",
    question: "In traditional Waterfall SDLC, when does testing typically begin?",
    option_a: "During requirements gathering",
    option_b: "After the design phase",
    option_c: "After all coding is complete",
    option_d: "During deployment",
    answer: "C",
    explanation: "In classic Waterfall, testing is a separate phase that starts only after development is complete — one of its major drawbacks.",
  },
  {
    lesson_title: "Software Development Life Cycle (SDLC)",
    question: "What does V-Model stand for?",
    option_a: "Version and Variant Model",
    option_b: "Verification and Validation Model",
    option_c: "Variable and Value Model",
    option_d: "Visual and Verbal Model",
    answer: "B",
    explanation: "The V-Model represents Verification (building correctly) and Validation (building the right thing), with each development phase paired with a testing phase.",
  },
  {
    lesson_title: "Software Development Life Cycle (SDLC)",
    question: "In Agile SDLC, when does testing occur?",
    option_a: "Only at the end of each sprint",
    option_b: "Only during dedicated test sprints",
    option_c: "Throughout every sprint, in parallel with development",
    option_d: "After the product backlog is complete",
    answer: "C",
    explanation: "Agile promotes continuous testing within every sprint. QA works in parallel with development, not after.",
  },
  {
    lesson_title: "Software Development Life Cycle (SDLC)",
    question: "In the V-Model, which testing phase corresponds to the requirements phase?",
    option_a: "Unit Testing",
    option_b: "Integration Testing",
    option_c: "System Testing",
    option_d: "Acceptance Testing",
    answer: "D",
    explanation: "In V-Model: Requirements ↔ Acceptance Testing. System Design ↔ System Testing. Architecture ↔ Integration Testing. Coding ↔ Unit Testing.",
  },
  {
    lesson_title: "Software Development Life Cycle (SDLC)",
    question: "What is the main disadvantage of the Waterfall SDLC for QA?",
    option_a: "Too many meetings",
    option_b: "Bugs are discovered very late, making them expensive to fix",
    option_c: "No documentation is produced",
    option_d: "Developers don't write unit tests",
    answer: "B",
    explanation: "Waterfall's sequential nature means bugs found in the testing phase were introduced much earlier, making them expensive to fix.",
  },
  {
    lesson_title: "Software Development Life Cycle (SDLC)",
    question: "What is a sprint in Agile?",
    option_a: "A full product release cycle",
    option_b: "A time-boxed iteration (typically 2-4 weeks) that produces shippable software",
    option_c: "A planning meeting",
    option_d: "A bug-fixing period",
    answer: "B",
    explanation: "A sprint is a fixed-length iteration in Scrum (typically 2-4 weeks) that results in a potentially shippable product increment.",
  },
  {
    lesson_title: "Software Development Life Cycle (SDLC)",
    question: "During which SDLC phase should QA engineers review requirements?",
    option_a: "Only during the testing phase",
    option_b: "As early as the requirements gathering phase",
    option_c: "After deployment",
    option_d: "Only when developers ask",
    answer: "B",
    explanation: "QA should be involved from the requirements phase to identify ambiguous, incomplete, or untestable requirements — catching issues when they're cheapest to fix.",
  },
  {
    lesson_title: "Software Development Life Cycle (SDLC)",
    question: "What is meant by 'shift-left testing'?",
    option_a: "Moving testers to a different team",
    option_b: "Starting testing activities earlier in the SDLC",
    option_c: "Using left-hand navigations in test management tools",
    option_d: "Reducing test case count",
    answer: "B",
    explanation: "Shift-left means moving testing activities earlier in the development process — catching defects sooner when they're cheaper to fix.",
  },
  {
    lesson_title: "Software Development Life Cycle (SDLC)",
    question: "Which SDLC phase produces the Test Plan?",
    option_a: "Requirements Gathering",
    option_b: "System Design",
    option_c: "Testing Phase (Test Planning within STLC)",
    option_d: "Maintenance",
    answer: "C",
    explanation: "The Test Plan is created during the Test Planning phase of STLC, which runs in parallel with the System Design phase of SDLC.",
  },
  {
    lesson_title: "Software Development Life Cycle (SDLC)",
    question: "What makes Agile better suited for QA compared to Waterfall?",
    option_a: "Agile has no testing requirements",
    option_b: "Agile allows continuous testing and early defect detection every sprint",
    option_c: "Agile requires less documentation",
    option_d: "Agile uses only automated testing",
    answer: "B",
    explanation: "Agile's iterative nature means QA continuously tests within each sprint, finding and fixing bugs much earlier than in Waterfall.",
  },
];
