import type { QuizRow } from "../../quiz-types";

export const softwareTestingLifeCycleStlcQuizzes: QuizRow[] = [
  {
    lesson_title: "Software Testing Life Cycle (STLC)",
    question: "How many phases are there in the STLC?",
    option_a: "4",
    option_b: "5",
    option_c: "6",
    option_d: "7",
    answer: "C",
    explanation: "The STLC has 6 phases: Requirement Analysis, Test Planning, Test Case Development, Test Environment Setup, Test Execution, and Test Closure.",
  },
  {
    lesson_title: "Software Testing Life Cycle (STLC)",
    question: "What is the first phase of STLC?",
    option_a: "Test Planning",
    option_b: "Test Execution",
    option_c: "Requirement Analysis",
    option_d: "Test Case Development",
    answer: "C",
    explanation: "Requirement Analysis is the first phase — QA studies the requirements to understand what must be tested before any planning begins.",
  },
  {
    lesson_title: "Software Testing Life Cycle (STLC)",
    question: "What document is produced during the Test Planning phase?",
    option_a: "Requirements Traceability Matrix",
    option_b: "Test Plan",
    option_c: "Defect Report",
    option_d: "Test Summary Report",
    answer: "B",
    explanation: "The Test Planning phase produces the Test Plan — covering scope, approach, resources, schedule, and risks.",
  },
  {
    lesson_title: "Software Testing Life Cycle (STLC)",
    question: "What is the entry criterion for the Test Execution phase?",
    option_a: "All bugs are fixed",
    option_b: "Test cases are written and the test environment is set up",
    option_c: "The product is deployed to production",
    option_d: "Management approval is received",
    answer: "B",
    explanation: "Test Execution can begin when test cases are ready and the test environment is configured and verified to work.",
  },
  {
    lesson_title: "Software Testing Life Cycle (STLC)",
    question: "What happens during the Test Closure phase?",
    option_a: "New test cases are written",
    option_b: "Bugs are filed for the first time",
    option_c: "Metrics are analyzed and a test summary report is created",
    option_d: "The test environment is set up",
    answer: "C",
    explanation: "Test Closure is the wrap-up phase: analyze metrics, document lessons learned, create the test summary report, and archive test artifacts.",
  },
  {
    lesson_title: "Software Testing Life Cycle (STLC)",
    question: "During which STLC phase are test cases peer-reviewed?",
    option_a: "Test Planning",
    option_b: "Test Case Development",
    option_c: "Test Execution",
    option_d: "Test Closure",
    answer: "B",
    explanation: "Test Case Development includes writing test cases AND having them peer-reviewed to ensure quality before execution.",
  },
  {
    lesson_title: "Software Testing Life Cycle (STLC)",
    question: "What is a smoke test in the context of environment setup?",
    option_a: "A test to find performance issues",
    option_b: "A quick check that the test environment is working before full testing begins",
    option_c: "A test that fills the database with data",
    option_d: "A security vulnerability scan",
    answer: "B",
    explanation: "In environment setup, a smoke test verifies that the environment is configured correctly and basic functionality works before full testing begins.",
  },
  {
    lesson_title: "Software Testing Life Cycle (STLC)",
    question: "What is an exit criterion?",
    option_a: "Conditions that must be met to start a testing phase",
    option_b: "Conditions that must be met to end a testing phase",
    option_c: "Conditions under which testing is skipped",
    option_d: "The final test case in a suite",
    answer: "B",
    explanation: "Exit criteria define when a testing phase is considered complete. Example: 100% test cases executed, no open Critical bugs, pass rate > 90%.",
  },
  {
    lesson_title: "Software Testing Life Cycle (STLC)",
    question: "What is produced at the end of the STLC?",
    option_a: "A new Test Plan",
    option_b: "Updated requirements",
    option_c: "Test Closure Report",
    option_d: "Source code",
    answer: "C",
    explanation: "The Test Closure Report summarizes all testing activities, metrics, lessons learned, and formally closes the testing effort.",
  },
  {
    lesson_title: "Software Testing Life Cycle (STLC)",
    question: "During Requirement Analysis, what is the primary output?",
    option_a: "Test cases",
    option_b: "A Requirements Understanding Document capturing what needs to be tested",
    option_c: "Bug reports",
    option_d: "Test scripts",
    answer: "B",
    explanation: "The output of Requirement Analysis is a document (RTM baseline or RUD) capturing what QA understands about what needs to be tested — including testability concerns flagged to stakeholders.",
  },
  {
    lesson_title: "Software Testing Life Cycle (STLC)",
    question: "What is the difference between entry criteria and exit criteria in STLC?",
    option_a: "They are the same thing — both define when to stop testing",
    option_b: "Entry criteria are conditions to START a phase; exit criteria are conditions to END a phase",
    option_c: "Entry criteria are written by developers; exit criteria by QA",
    option_d: "Exit criteria apply only to the Test Closure phase",
    answer: "B",
    explanation: "Entry criteria define the prerequisites to begin a phase (e.g., test environment ready). Exit criteria define when the phase is done (e.g., 100% test execution, no critical open bugs).",
  },
  {
    lesson_title: "Software Testing Life Cycle (STLC)",
    question: "You are in the Test Execution phase when a critical defect blocks 30% of your test cases. What is the proper STLC response?",
    option_a: "Continue executing the remaining 70% and ignore the blocked tests",
    option_b: "Invoke suspension criteria, stop testing those areas, and notify the team to resolve the blocking defect",
    option_c: "Move immediately to Test Closure since 70% was executed",
    option_d: "Rewrite the blocked test cases to work around the defect",
    answer: "B",
    explanation: "When blockers prevent significant test execution, suspension criteria kick in — testing is paused for the affected areas. The team is notified to fix the blocking issue, and testing resumes after verification.",
  },
  {
    lesson_title: "Software Testing Life Cycle (STLC)",
    question: "Midway through Test Execution, developers push a major code change that affects most features. How does this affect your STLC phase?",
    option_a: "Continue executing as-is since the test cases are already written",
    option_b: "Stop execution, re-evaluate test cases for validity, and potentially loop back to Test Case Development",
    option_c: "Move directly to Test Closure since the code changed",
    option_d: "File all existing test failures as bugs immediately",
    answer: "B",
    explanation: "A major mid-cycle code change may invalidate existing test cases. QA must assess the impact, update affected test cases, and re-execute affected scenarios — this loop-back is normal in iterative environments.",
  },
  {
    lesson_title: "Software Testing Life Cycle (STLC)",
    question: "During which STLC phase does QA first create the Requirements Traceability Matrix (RTM)?",
    option_a: "Test Planning",
    option_b: "Requirement Analysis",
    option_c: "Test Execution",
    option_d: "Test Closure",
    answer: "B",
    explanation: "The RTM baseline is created during Requirement Analysis — mapping requirements to planned test coverage. It is then completed with test case IDs during Test Case Development.",
  },
  {
    lesson_title: "Software Testing Life Cycle (STLC)",
    question: "What is the key output of the Test Case Development phase?",
    option_a: "A deployed test environment",
    option_b: "A signed-off test plan",
    option_c: "Peer-reviewed test cases and test data ready for execution",
    option_d: "A test summary report",
    answer: "C",
    explanation: "Test Case Development outputs reviewed and approved test cases, along with the test data required to execute them — ready for the Test Execution phase.",
  },
];
