import type { QuizRow } from "../../quiz-types";

export const writingYourFirstTestCaseQuizzes: QuizRow[] = [
  {
    lesson_title: "Writing Your First Test Case",
    question: "Which field in a test case specifies the required state BEFORE test execution?",
    option_a: "Expected Result",
    option_b: "Test Steps",
    option_c: "Preconditions",
    option_d: "Actual Result",
    answer: "C",
    explanation: "Preconditions define the state that must exist before the test can be executed — e.g., user must be registered, browser must be open.",
  },
  {
    lesson_title: "Writing Your First Test Case",
    question: "What is the best practice for a single test case?",
    option_a: "Test as many features as possible in one test",
    option_b: "Test one specific scenario per test case",
    option_c: "Combine positive and negative tests together",
    option_d: "Share test data across all test cases",
    answer: "B",
    explanation: "Each test case should have one clear goal. Testing multiple things in one case makes it hard to isolate failures and understand what went wrong.",
  },
  {
    lesson_title: "Writing Your First Test Case",
    question: "A test case status of 'Blocked' means:",
    option_a: "The test failed",
    option_b: "The test passed but has warnings",
    option_c: "The test cannot be executed due to a dependency or environment issue",
    option_d: "The test was skipped intentionally",
    answer: "C",
    explanation: "Blocked means the test couldn't be executed — typically due to a prerequisite not being met, like a dependency feature not being built yet.",
  },
  {
    lesson_title: "Writing Your First Test Case",
    question: "What should test data in a test case contain?",
    option_a: "General descriptions like 'enter a valid email'",
    option_b: "Exact, specific values like 'qa_tester@example.com'",
    option_c: "Random data generated at runtime",
    option_d: "Data from production systems",
    answer: "B",
    explanation: "Test data must be specific and exact so the test is repeatable. Vague descriptions like 'a valid email' lead to inconsistent results.",
  },
  {
    lesson_title: "Writing Your First Test Case",
    question: "What is a negative test case?",
    option_a: "A test that always fails",
    option_b: "A test with invalid inputs to verify the system handles errors correctly",
    option_c: "A test for deprecated features",
    option_d: "A test written in a negative tone",
    answer: "B",
    explanation: "Negative tests verify system behavior with invalid inputs — e.g., wrong password, missing required fields, out-of-range values. Systems must handle these gracefully.",
  },
  {
    lesson_title: "Writing Your First Test Case",
    question: "What makes a test case 'independent'?",
    option_a: "It runs faster than other tests",
    option_b: "It can be executed without relying on other test cases",
    option_c: "It doesn't need a test environment",
    option_d: "It doesn't require any input data",
    answer: "B",
    explanation: "Independent test cases can run in any order and don't require other tests to run first. This prevents cascading failures and makes debugging easier.",
  },
  {
    lesson_title: "Writing Your First Test Case",
    question: "What is the 'Actual Result' field used for?",
    option_a: "Predicted outcome before running the test",
    option_b: "What the system actually did when the test was executed",
    option_c: "The test case author's name",
    option_d: "The environment the test ran in",
    answer: "B",
    explanation: "Actual Result is filled in during test execution and records what actually happened. Comparing it to Expected Result determines pass/fail.",
  },
  {
    lesson_title: "Writing Your First Test Case",
    question: "Why should test cases be repeatable?",
    option_a: "To increase the test count metric",
    option_b: "So the same steps produce the same result every time, enabling reliable verification",
    option_c: "To reduce the need for test data",
    option_d: "Because automation tools require it",
    answer: "B",
    explanation: "Repeatable test cases give consistent results. If a test passes sometimes and fails other times, it's unreliable (flaky) and loses value.",
  },
  {
    lesson_title: "Writing Your First Test Case",
    question: "What is test case priority?",
    option_a: "How quickly a test runs",
    option_b: "The order in which tests should be executed based on business importance",
    option_c: "The severity of the bug it found",
    option_d: "The number of steps in the test",
    answer: "B",
    explanation: "Priority indicates which tests should run first based on business importance. High priority tests cover critical functionality.",
  },
  {
    lesson_title: "Writing Your First Test Case",
    question: "A test case ID (like TC-LOGIN-001) serves what purpose?",
    option_a: "Shows the date the test was created",
    option_b: "Uniquely identifies the test case for tracking and referencing",
    option_c: "Indicates the automation framework used",
    option_d: "Shows which developer wrote the feature",
    answer: "B",
    explanation: "Test case IDs uniquely identify test cases so they can be referenced in bug reports, test plans, and traceability matrices.",
  },
];
