import type { QuizRow } from "../../quiz-types";

export const writingYourFirstTestCaseQuizzes: QuizRow[] = [
  {
    lesson_title: "Writing Your First Test Case",
    question: "Which field in a test case specifies the required state BEFORE test execution?",
    option_a: "Expected Result",
    option_b: "Test Steps",
    option_c: "Preconditions",
    option_d: "Actual Result",
    answer: "C",
    explanation: "Preconditions define the state that must exist before the test can be executed — e.g., user must be registered, browser must be open.",
  },
  {
    lesson_title: "Writing Your First Test Case",
    question: "What is the best practice for a single test case?",
    option_a: "Test as many features as possible in one test",
    option_b: "Test one specific scenario per test case",
    option_c: "Combine positive and negative tests together",
    option_d: "Share test data across all test cases",
    answer: "B",
    explanation: "Each test case should have one clear goal. Testing multiple things in one case makes it hard to isolate failures and understand what went wrong.",
  },
  {
    lesson_title: "Writing Your First Test Case",
    question: "A test case status of 'Blocked' means:",
    option_a: "The test failed",
    option_b: "The test passed but has warnings",
    option_c: "The test cannot be executed due to a dependency or environment issue",
    option_d: "The test was skipped intentionally",
    answer: "C",
    explanation: "Blocked means the test couldn't be executed — typically due to a prerequisite not being met, like a dependency feature not being built yet.",
  },
  {
    lesson_title: "Writing Your First Test Case",
    question: "What should test data in a test case contain?",
    option_a: "General descriptions like 'enter a valid email'",
    option_b: "Exact, specific values like 'qa_tester@example.com'",
    option_c: "Random data generated at runtime",
    option_d: "Data from production systems",
    answer: "B",
    explanation: "Test data must be specific and exact so the test is repeatable. Vague descriptions like 'a valid email' lead to inconsistent results.",
  },
  {
    lesson_title: "Writing Your First Test Case",
    question: "What is a negative test case?",
    option_a: "A test that always fails",
    option_b: "A test with invalid inputs to verify the system handles errors correctly",
    option_c: "A test for deprecated features",
    option_d: "A test written in a negative tone",
    answer: "B",
    explanation: "Negative tests verify system behavior with invalid inputs — e.g., wrong password, missing required fields, out-of-range values. Systems must handle these gracefully.",
  },
  {
    lesson_title: "Writing Your First Test Case",
    question: "What makes a test case 'independent'?",
    option_a: "It runs faster than other tests",
    option_b: "It can be executed without relying on other test cases",
    option_c: "It doesn't need a test environment",
    option_d: "It doesn't require any input data",
    answer: "B",
    explanation: "Independent test cases can run in any order and don't require other tests to run first. This prevents cascading failures and makes debugging easier.",
  },
  {
    lesson_title: "Writing Your First Test Case",
    question: "What is the 'Actual Result' field used for?",
    option_a: "Predicted outcome before running the test",
    option_b: "What the system actually did when the test was executed",
    option_c: "The test case author's name",
    option_d: "The environment the test ran in",
    answer: "B",
    explanation: "Actual Result is filled in during test execution and records what actually happened. Comparing it to Expected Result determines pass/fail.",
  },
  {
    lesson_title: "Writing Your First Test Case",
    question: "Why should test cases be repeatable?",
    option_a: "To increase the test count metric",
    option_b: "So the same steps produce the same result every time, enabling reliable verification",
    option_c: "To reduce the need for test data",
    option_d: "Because automation tools require it",
    answer: "B",
    explanation: "Repeatable test cases give consistent results. If a test passes sometimes and fails other times, it's unreliable (flaky) and loses value.",
  },
  {
    lesson_title: "Writing Your First Test Case",
    question: "What is test case priority?",
    option_a: "How quickly a test runs",
    option_b: "The order in which tests should be executed based on business importance",
    option_c: "The severity of the bug it found",
    option_d: "The number of steps in the test",
    answer: "B",
    explanation: "Priority indicates which tests should run first based on business importance. High priority tests cover critical functionality.",
  },
  {
    lesson_title: "Writing Your First Test Case",
    question: "A test case ID (like TC-LOGIN-001) serves what purpose?",
    option_a: "Shows the date the test was created",
    option_b: "Uniquely identifies the test case for tracking and referencing in bug reports and the RTM",
    option_c: "Indicates the automation framework used",
    option_d: "Shows which developer wrote the feature",
    answer: "B",
    explanation: "Test case IDs uniquely identify test cases so they can be referenced in bug reports, test plans, and traceability matrices.",
  },
  {
    lesson_title: "Writing Your First Test Case",
    question: "What is the difference between a test scenario and a test case?",
    option_a: "They are the same thing — just different names",
    option_b: "A test scenario is a high-level goal; a test case contains the specific steps, data, and expected results to achieve it",
    option_c: "A test scenario is more detailed than a test case",
    option_d: "Test scenarios are only used in agile; test cases in waterfall",
    answer: "B",
    explanation: "A test scenario is a high-level statement of what to test (e.g., 'Verify login with valid credentials'). A test case expands it into exact steps, test data, preconditions, and expected results.",
  },
  {
    lesson_title: "Writing Your First Test Case",
    question: "A test case you wrote 6 months ago suddenly fails, but the feature it tests hasn't changed. What do you investigate first?",
    option_a: "Assume the test case is wrong and delete it",
    option_b: "Check if test data, environment, or a dependency changed that could cause the failure",
    option_c: "File a P1 bug immediately without investigating",
    option_d: "Rewrite the test case from scratch",
    answer: "B",
    explanation: "Before filing a bug, investigate: did test data expire? Did an environment change? Did a dependent API change? Flaky failures from external factors are common and must be distinguished from real regressions.",
  },
  {
    lesson_title: "Writing Your First Test Case",
    question: "What is the purpose of peer-reviewing test cases before execution?",
    option_a: "To slow down the testing process with approvals",
    option_b: "To catch missing scenarios, incorrect expected results, and ambiguous steps before they cause false passes or false failures",
    option_c: "To ensure QA follows the development coding standards",
    option_d: "To allow developers to modify the test cases",
    answer: "B",
    explanation: "Peer review of test cases catches issues early: missing edge cases, wrong expected results, unclear steps, and missing preconditions — all before time is wasted executing flawed tests.",
  },
  {
    lesson_title: "Writing Your First Test Case",
    question: "Your test suite has 200 test cases but you can only run 50 before a critical release. How do you select which ones?",
    option_a: "Run the 50 newest test cases since they cover the latest features",
    option_b: "Run 50 random test cases to get a representative sample",
    option_c: "Run the 50 highest-priority test cases covering core business flows and recently changed areas",
    option_d: "Run the 50 shortest test cases to maximize the number of scenarios tested",
    answer: "C",
    explanation: "Prioritize by risk: run test cases that cover critical user journeys (checkout, login, payments) and areas that were recently changed. This gives the highest confidence in the release with limited time.",
  },
  {
    lesson_title: "Writing Your First Test Case",
    question: "What is 'test case traceability' and why does it matter?",
    option_a: "The ability to track test execution time across multiple runs",
    option_b: "Linking each test case back to the requirement it covers, so gaps in coverage are visible",
    option_c: "Tracking which tester wrote each test case",
    option_d: "The ability to run test cases in any order",
    answer: "B",
    explanation: "Traceability links test cases to requirements, ensuring every requirement is covered and every test case has a purpose. Without it, you can't know if gaps exist or if a test case is orphaned.",
  },
];
