import type { QuizRow } from "../../quiz-types";

export const bugReportingFundamentalsQuizzes: QuizRow[] = [
  {
    lesson_title: "Bug Reporting Fundamentals",
    question: "What is the difference between bug severity and priority?",
    option_a: "They mean the same thing",
    option_b: "Severity is the technical impact; priority is the urgency to fix",
    option_c: "Priority is the technical impact; severity is the urgency",
    option_d: "Severity is set by developers; priority by QA",
    answer: "B",
    explanation: "Severity = how bad the impact is technically. Priority = how urgently it needs fixing (business decision). A typo on the homepage might be low severity but high priority.",
  },
  {
    lesson_title: "Bug Reporting Fundamentals",
    question: "Which is the best bug title?",
    option_a: "Login broken",
    option_b: "Page error",
    option_c: "Login button unresponsive when email contains + character",
    option_d: "Bug in authentication",
    answer: "C",
    explanation: "Good bug titles are specific: what is broken + under what conditions. This lets developers understand the scope without reading the full report.",
  },
  {
    lesson_title: "Bug Reporting Fundamentals",
    question: "Why is 'Steps to Reproduce' the most critical section of a bug report?",
    option_a: "It shows the severity of the bug",
    option_b: "Without it, developers cannot reliably reproduce and fix the bug",
    option_c: "It determines who fixes the bug",
    option_d: "It calculates the priority of the bug",
    answer: "B",
    explanation: "Developers need to reproduce the bug to understand and fix it. Vague or incomplete reproduction steps are the #1 cause of bugs being marked 'Cannot Reproduce'.",
  },
  {
    lesson_title: "Bug Reporting Fundamentals",
    question: "A critical bug crashes the payment system. It is high severity. What priority is it most likely?",
    option_a: "Low priority — only happens once",
    option_b: "Medium priority — needs to be scheduled",
    option_c: "High priority — needs immediate attention regardless of frequency",
    option_d: "No priority until a workaround is found",
    answer: "C",
    explanation: "Payment system crashes are critical business impact AND require immediate attention. Frequency doesn't reduce priority for critical revenue-impacting bugs.",
  },
  {
    lesson_title: "Bug Reporting Fundamentals",
    question: "What should you include in the 'Environment' field of a bug report?",
    option_a: "Your personal opinion about the feature",
    option_b: "OS, browser version, app version, and URL where the bug occurred",
    option_c: "The developer's name",
    option_d: "Your test case ID only",
    answer: "B",
    explanation: "Environment details (OS, browser, version, URL) help developers reproduce the bug in the same conditions. The same bug may not appear on different OS/browser combinations.",
  },
  {
    lesson_title: "Bug Reporting Fundamentals",
    question: "What does 'intermittent' reproducibility mean?",
    option_a: "The bug happens every time",
    option_b: "The bug only happens in production",
    option_c: "The bug happens some of the time but not consistently",
    option_d: "The bug cannot be reproduced",
    answer: "C",
    explanation: "Intermittent bugs don't reproduce every time — they might occur 30–70% of attempts. These are especially difficult to diagnose and fix.",
  },
  {
    lesson_title: "Bug Reporting Fundamentals",
    question: "When should you attach a screenshot or video to a bug report?",
    option_a: "Never — they take up too much space",
    option_b: "Only for UI bugs",
    option_c: "Always when possible — visual evidence speeds up developer understanding",
    option_d: "Only when the bug is Critical severity",
    answer: "C",
    explanation: "Visual evidence (screenshots, videos, logs) dramatically speeds up bug resolution by giving developers immediate context without needing to reproduce it first.",
  },
  {
    lesson_title: "Bug Reporting Fundamentals",
    question: "A bug report where 'Expected Result' and 'Actual Result' are identical indicates:",
    option_a: "A valid bug",
    option_b: "A critical bug",
    option_c: "The test passed — no defect found",
    option_d: "The environment is broken",
    answer: "C",
    explanation: "A bug exists when actual results differ from expected results. If they match, the feature works as specified — it's not a bug.",
  },
  {
    lesson_title: "Bug Reporting Fundamentals",
    question: "Who assigns priority to a bug?",
    option_a: "Always the QA engineer who found it",
    option_b: "Always the developer who fixes it",
    option_c: "Business/product owner or team consensus",
    option_d: "The test management tool automatically",
    answer: "C",
    explanation: "Priority is a business decision — it depends on business impact, customer impact, and release timelines. Product owners or the team make this decision, not QA alone.",
  },
  {
    lesson_title: "Bug Reporting Fundamentals",
    question: "What is an 'orphan bug'?",
    option_a: "A bug not linked to any test case or requirement",
    option_b: "A bug only reproducible in production",
    option_c: "A bug that cannot be reproduced",
    option_d: "A bug reported by an external user",
    answer: "A",
    explanation: "An orphan bug has no traceability to requirements or test cases — making it hard to understand its scope and impact on the release.",
  },
  {
    lesson_title: "Bug Reporting Fundamentals",
    question: "You file a bug and the developer marks it 'Working as Designed.' You disagree because it clearly contradicts the requirements document. What is your next step?",
    option_a: "Accept the developer's decision and close the bug",
    option_b: "Escalate to your manager immediately without further discussion",
    option_c: "Attach the specific requirement that contradicts the behavior and reopen the bug with evidence",
    option_d: "File a duplicate bug with a more alarming title",
    answer: "C",
    explanation: "Reopen with evidence — link to the exact requirement, acceptance criteria, or design document that defines the expected behavior. This turns a dispute into a fact-based discussion.",
  },
  {
    lesson_title: "Bug Reporting Fundamentals",
    question: "When should a bug be marked as 'Duplicate'?",
    option_a: "When two people file bugs on the same day",
    option_b: "When the same defect has already been reported and the new report adds no new information",
    option_c: "When a bug occurs in multiple environments",
    option_d: "When a bug affects multiple users",
    answer: "B",
    explanation: "A bug is a duplicate when another report already tracks the same root cause. The duplicate should be linked to the original and closed, so fixes are tracked in one place.",
  },
  {
    lesson_title: "Bug Reporting Fundamentals",
    question: "A Critical severity bug you reported 3 days ago is still unassigned with the release in 1 day. What do you do?",
    option_a: "Wait — the team will get to it eventually",
    option_b: "Close the bug to keep the dashboard clean",
    option_c: "Escalate to the QA lead or PM immediately — an unassigned critical bug 1 day before release is a release risk",
    option_d: "Assign it to yourself and fix it",
    answer: "C",
    explanation: "An unassigned critical bug the day before release is a significant risk that needs immediate visibility. Escalate so the team can make a conscious go/no-go decision with full information.",
  },
  {
    lesson_title: "Bug Reporting Fundamentals",
    question: "What is a 'workaround' note in a bug report and when should you include it?",
    option_a: "A description of how to fix the code — include it always",
    option_b: "A temporary way for users to avoid the bug — include it when one exists, to reduce business impact while waiting for a fix",
    option_c: "An excuse for why the bug wasn't caught earlier",
    option_d: "A note only relevant for low-priority bugs",
    answer: "B",
    explanation: "A workaround gives the business a way to function despite the bug. Documenting it helps the product owner weigh priority — a bug with an easy workaround may be lower priority than one with none.",
  },
  {
    lesson_title: "Bug Reporting Fundamentals",
    question: "What is the minimum information required to write a valid, actionable bug report?",
    option_a: "Title only — developers can figure out the rest",
    option_b: "Title, steps to reproduce, expected result, actual result, and environment details",
    option_c: "Title and a screenshot",
    option_d: "Severity and the developer's name",
    answer: "B",
    explanation: "A valid bug report must have: a clear title, reproducible steps, expected vs. actual results, and environment details. Without all five, developers cannot reliably understand or reproduce the issue.",
  },
];
