import type { QuizRow } from "../../quiz-types";

export const defectLifeCycleQuizzes: QuizRow[] = [
  {
    lesson_title: "Defect Life Cycle",
    question: "What is the first state of a newly reported bug?",
    option_a: "Open",
    option_b: "New",
    option_c: "Assigned",
    option_d: "In Progress",
    answer: "B",
    explanation: "When a bug is first reported, it enters the 'New' state — awaiting review and confirmation by the team.",
  },
  {
    lesson_title: "Defect Life Cycle",
    question: "When does a bug move to 'Reopen' state?",
    option_a: "When the bug is first reported",
    option_b: "When a developer starts working on it",
    option_c: "When QA retests and finds the fix didn't work",
    option_d: "When the bug is assigned to a developer",
    answer: "C",
    explanation: "A bug is reopened when it was marked Fixed, QA retested it, but the fix was insufficient — the bug still exists.",
  },
  {
    lesson_title: "Defect Life Cycle",
    question: "What does 'Deferred' status mean for a bug?",
    option_a: "The bug was fixed automatically",
    option_b: "The bug is not valid",
    option_c: "The valid bug will be fixed in a future release",
    option_d: "The bug requires more investigation",
    answer: "C",
    explanation: "Deferred means the bug is confirmed valid but the fix is scheduled for a future release — usually due to lower priority or resource constraints.",
  },
  {
    lesson_title: "Defect Life Cycle",
    question: "What should QA do in the 'Retest' phase?",
    option_a: "Write new test cases for the bug",
    option_b: "Report a new bug",
    option_c: "Verify the fix works AND check for regression in surrounding areas",
    option_d: "Close the bug immediately",
    answer: "C",
    explanation: "During Retest, QA verifies the specific fix works AND runs surrounding tests to ensure the fix didn't introduce new issues (regression).",
  },
  {
    lesson_title: "Defect Life Cycle",
    question: "What does 'Rejected' status indicate?",
    option_a: "The developer cannot fix the bug",
    option_b: "The reported issue is not actually a bug — it's working as designed",
    option_c: "The bug is too old to fix",
    option_d: "The bug was found by an external user",
    answer: "B",
    explanation: "Rejected means the team determined the reported behavior is correct and intentional — it's not a defect. QA must document the reasoning.",
  },
  {
    lesson_title: "Defect Life Cycle",
    question: "Before closing a bug, QA must:",
    option_a: "Delete the bug report",
    option_b: "Retest the fix in the same environment where the bug was found",
    option_c: "Only verify the fix works on their local machine",
    option_d: "Get approval from the product manager",
    answer: "B",
    explanation: "QA must verify the fix in the same environment where the bug was found (not just locally or in a different environment).",
  },
  {
    lesson_title: "Defect Life Cycle",
    question: "In which state does QA verify that the bug is fixed?",
    option_a: "New",
    option_b: "Fixed",
    option_c: "Retest",
    option_d: "Closed",
    answer: "C",
    explanation: "The Retest state is when QA verifies the fix. If verified successfully, the bug moves to Verified → Closed. If not, it goes back to Reopen.",
  },
  {
    lesson_title: "Defect Life Cycle",
    question: "What is bug triage?",
    option_a: "Writing test cases for bugs",
    option_b: "A team meeting to review, prioritize, and assign open defects",
    option_c: "Automated bug detection",
    option_d: "The process of closing all bugs before release",
    answer: "B",
    explanation: "Bug triage is a regular team meeting where open defects are reviewed, their severity/priority assessed, and they're assigned to team members for resolution.",
  },
  {
    lesson_title: "Defect Life Cycle",
    question: "You retest a bug marked 'Fixed' and it still occurs, but only about 30% of the time — not every attempt. How do you handle this?",
    option_a: "Close the bug since it passes most of the time",
    option_b: "Reopen the bug, document the intermittent behavior, and provide the exact reproduction rate and any new details",
    option_c: "Mark it as a new bug and file a separate report",
    option_d: "Wait until it reproduces consistently before reopening",
    answer: "B",
    explanation: "Reopen the bug — an intermittent failure means the fix is incomplete or introduced a race condition. Document exactly how often it occurs and any patterns you observe to help the developer diagnose it.",
  },
  {
    lesson_title: "Defect Life Cycle",
    question: "What is the correct bug status after a developer applies a fix but QA has NOT yet retested it?",
    option_a: "Closed",
    option_b: "Resolved / Fixed (awaiting QA verification)",
    option_c: "Rejected",
    option_d: "Deferred",
    answer: "B",
    explanation: "After the developer fixes the bug it moves to 'Fixed' or 'Resolved' — indicating the fix is deployed and ready for QA to verify. It should NOT be closed until QA confirms the fix.",
  },
  {
    lesson_title: "Defect Life Cycle",
    question: "In a bug triage meeting, a critical P1 bug gets deprioritized because a workaround exists. As QA, how do you respond?",
    option_a: "Agree — if users can work around it, it can wait",
    option_b: "Document your disagreement, quantify the impact (workaround effort, affected users, risk), and ensure the decision is formally recorded",
    option_c: "Refuse to continue the meeting until the bug is reprioritized",
    option_d: "Close the bug since the workaround makes it no longer critical",
    answer: "B",
    explanation: "Voice your concern with data — how many users are affected, how complex is the workaround, and what risk remains. Ensure the decision is documented so accountability is clear if the bug impacts production.",
  },
  {
    lesson_title: "Defect Life Cycle",
    question: "What happens to a bug's state if it was closed but the identical issue recurs in a new build?",
    option_a: "The original closed bug is reopened",
    option_b: "A new bug is filed as a separate report",
    option_c: "Either is acceptable — team decides based on whether it's the same root cause",
    option_d: "The developer is automatically notified",
    answer: "C",
    explanation: "If it's clearly the same root cause resurfacing, reopen the original bug. If it looks similar but may be different code, file a new bug. Either way, link them for context.",
  },
  {
    lesson_title: "Defect Life Cycle",
    question: "You have 20 open bugs 1 day before release. How do you communicate which ones block the release?",
    option_a: "All 20 must be fixed before release",
    option_b: "Categorize by severity: Critical/High bugs that affect core flows block the release; Medium/Low are candidate for deferral with documented acceptance",
    option_c: "None of them block the release — it's the PM's decision",
    option_d: "Run a vote with the team to decide",
    answer: "B",
    explanation: "Create a clear picture: these X bugs are release blockers (Critical/High impact on core flows), these Y are deferrable (workaround exists, low impact). Let the PM make an informed go/no-go decision.",
  },
  {
    lesson_title: "Defect Life Cycle",
    question: "What is the purpose of a 'bug aging' report?",
    option_a: "To track how old the codebase is",
    option_b: "To identify bugs that have been open for a long time without resolution, highlighting process breakdowns",
    option_c: "To count how many bugs each developer fixes per week",
    option_d: "To archive closed bugs after 90 days",
    answer: "B",
    explanation: "Bug aging reports surface defects that are stagnating — open for weeks or months with no action. These often indicate unclear ownership, forgotten deferrals, or process issues that need addressing.",
  },
  {
    lesson_title: "Defect Life Cycle",
    question: "A bug is marked 'Cannot Reproduce' by the developer. What information should QA provide to help?",
    option_a: "Nothing — it's the developer's problem now",
    option_b: "Exact environment details, step-by-step reproduction steps, screenshots/video, and confirmation it still reproduces on QA's machine",
    option_c: "Increase the priority and reassign to a different developer",
    option_d: "Close the bug and file a new one",
    answer: "B",
    explanation: "Provide a complete reproduction package: detailed steps, exact environment (OS, browser, version), evidence (screenshot/video), and confirmation you can still reproduce it. This removes ambiguity and enables the developer to replicate the conditions exactly.",
  },
];
