import type { QuizRow } from "../../quiz-types";

export const defectLifeCycleQuizzes: QuizRow[] = [
  {
    lesson_title: "Defect Life Cycle",
    question: "What is the first state of a newly reported bug?",
    option_a: "Open",
    option_b: "New",
    option_c: "Assigned",
    option_d: "In Progress",
    answer: "B",
    explanation: "When a bug is first reported, it enters the 'New' state — awaiting review and confirmation by the team.",
  },
  {
    lesson_title: "Defect Life Cycle",
    question: "When does a bug move to 'Reopen' state?",
    option_a: "When the bug is first reported",
    option_b: "When a developer starts working on it",
    option_c: "When QA retests and finds the fix didn't work",
    option_d: "When the bug is assigned to a developer",
    answer: "C",
    explanation: "A bug is reopened when it was marked Fixed, QA retested it, but the fix was insufficient — the bug still exists.",
  },
  {
    lesson_title: "Defect Life Cycle",
    question: "What does 'Deferred' status mean for a bug?",
    option_a: "The bug was fixed automatically",
    option_b: "The bug is not valid",
    option_c: "The valid bug will be fixed in a future release",
    option_d: "The bug requires more investigation",
    answer: "C",
    explanation: "Deferred means the bug is confirmed valid but the fix is scheduled for a future release — usually due to lower priority or resource constraints.",
  },
  {
    lesson_title: "Defect Life Cycle",
    question: "What should QA do in the 'Retest' phase?",
    option_a: "Write new test cases for the bug",
    option_b: "Report a new bug",
    option_c: "Verify the fix works AND check for regression",
    option_d: "Close the bug immediately",
    answer: "C",
    explanation: "During Retest, QA verifies the specific fix works AND runs surrounding tests to ensure the fix didn't introduce new issues (regression).",
  },
  {
    lesson_title: "Defect Life Cycle",
    question: "What does 'Rejected' status indicate?",
    option_a: "The developer cannot fix the bug",
    option_b: "The reported issue is not actually a bug — it's working as designed",
    option_c: "The bug is too old to fix",
    option_d: "The bug was found by an external user",
    answer: "B",
    explanation: "Rejected means the team determined the reported behavior is correct and intentional — it's not a defect. QA must document the reasoning.",
  },
  {
    lesson_title: "Defect Life Cycle",
    question: "Before closing a bug, QA must:",
    option_a: "Delete the bug report",
    option_b: "Retest the fix in the same environment where the bug was found",
    option_c: "Only verify the fix works on their local machine",
    option_d: "Get approval from the product manager",
    answer: "B",
    explanation: "QA must verify the fix in the same environment where the bug was found (not just locally or in a different environment).",
  },
  {
    lesson_title: "Defect Life Cycle",
    question: "In which state does QA verify that the bug is fixed?",
    option_a: "New",
    option_b: "Fixed",
    option_c: "Retest",
    option_d: "Closed",
    answer: "C",
    explanation: "The Retest state is when QA verifies the fix. If verified successfully, the bug moves to Verified → Closed. If not, it goes back to Reopen.",
  },
  {
    lesson_title: "Defect Life Cycle",
    question: "What is bug triage?",
    option_a: "Writing test cases for bugs",
    option_b: "A team meeting to review, prioritize, and assign open defects",
    option_c: "Automated bug detection",
    option_d: "The process of closing all bugs before release",
    answer: "B",
    explanation: "Bug triage is a regular team meeting where open defects are reviewed, their severity/priority assessed, and they're assigned to team members for resolution.",
  },
];
