import type { QuizRow } from "../../quiz-types";

export const testEnvironmentsAndConfigurationsQuizzes: QuizRow[] = [
  {
    lesson_title: "Test Environments & Configurations",
    question: "Which environment most closely mirrors production?",
    option_a: "Development",
    option_b: "QA/Testing",
    option_c: "Staging/Pre-production",
    option_d: "Local",
    answer: "C",
    explanation: "Staging (pre-production) is specifically designed to mirror production as closely as possible for final validation before release.",
  },
  {
    lesson_title: "Test Environments & Configurations",
    question: "What is 'environment parity'?",
    option_a: "All testers share the same computer",
    option_b: "Test environments match production in software versions and configurations",
    option_c: "All environments run the same test cases",
    option_d: "Developers and QA use the same environments",
    answer: "B",
    explanation: "Environment parity means your test environment has the same OS, database version, dependencies, and configuration as production — preventing 'works on my machine' issues.",
  },
  {
    lesson_title: "Test Environments & Configurations",
    question: "What is the main risk of using a shared test environment?",
    option_a: "It's more expensive",
    option_b: "Multiple testers can interfere with each other's test data",
    option_c: "It takes longer to deploy",
    option_d: "It doesn't support automation",
    answer: "B",
    explanation: "In shared environments, multiple testers can create, modify, or delete data that others rely on — causing false failures and confusion.",
  },
  {
    lesson_title: "Test Environments & Configurations",
    question: "What should always be documented about a test environment?",
    option_a: "Only the URL",
    option_b: "URL, OS, app version, database version, and last deployment date",
    option_c: "Only the database version",
    option_d: "Only the test cases that ran in it",
    answer: "B",
    explanation: "Complete environment documentation (URL, OS, versions, deployment date) ensures bugs can be reproduced reliably and environment issues can be diagnosed.",
  },
  {
    lesson_title: "Test Environments & Configurations",
    question: "What is 'environment drift'?",
    option_a: "When environments run too slow",
    option_b: "When the test environment gradually diverges from production configuration",
    option_c: "When test data is deleted accidentally",
    option_d: "When different browsers behave differently",
    answer: "B",
    explanation: "Environment drift occurs when manual changes, hotfixes, or configuration updates are applied to production but not reflected in test environments — causing false test results.",
  },
];
