import type { QuizRow } from "../../quiz-types";

export const testEnvironmentsAndConfigurationsQuizzes: QuizRow[] = [
  {
    lesson_title: "Test Environments & Configurations",
    question: "Which environment most closely mirrors production?",
    option_a: "Development",
    option_b: "QA/Testing",
    option_c: "Staging/Pre-production",
    option_d: "Local",
    answer: "C",
    explanation: "Staging (pre-production) is specifically designed to mirror production as closely as possible for final validation before release.",
  },
  {
    lesson_title: "Test Environments & Configurations",
    question: "What is 'environment parity'?",
    option_a: "All testers share the same computer",
    option_b: "Test environments match production in software versions and configurations",
    option_c: "All environments run the same test cases",
    option_d: "Developers and QA use the same environments",
    answer: "B",
    explanation: "Environment parity means your test environment has the same OS, database version, dependencies, and configuration as production — preventing 'works on my machine' issues.",
  },
  {
    lesson_title: "Test Environments & Configurations",
    question: "What is the main risk of using a shared test environment?",
    option_a: "It's more expensive",
    option_b: "Multiple testers can interfere with each other's test data",
    option_c: "It takes longer to deploy",
    option_d: "It doesn't support automation",
    answer: "B",
    explanation: "In shared environments, multiple testers can create, modify, or delete data that others rely on — causing false failures and confusion.",
  },
  {
    lesson_title: "Test Environments & Configurations",
    question: "What should always be documented about a test environment?",
    option_a: "Only the URL",
    option_b: "URL, OS, app version, database version, and last deployment date",
    option_c: "Only the database version",
    option_d: "Only the test cases that ran in it",
    answer: "B",
    explanation: "Complete environment documentation (URL, OS, versions, deployment date) ensures bugs can be reproduced reliably and environment issues can be diagnosed.",
  },
  {
    lesson_title: "Test Environments & Configurations",
    question: "What is 'environment drift'?",
    option_a: "When environments run too slow",
    option_b: "When the test environment gradually diverges from production configuration",
    option_c: "When test data is deleted accidentally",
    option_d: "When different browsers behave differently",
    answer: "B",
    explanation: "Environment drift occurs when manual changes, hotfixes, or configuration updates are applied to production but not reflected in test environments — causing false test results.",
  },
  {
    lesson_title: "Test Environments & Configurations",
    question: "You deploy the same code build to staging and tests fail there, but they passed in QA. The code is identical. What do you investigate first?",
    option_a: "Assume the staging tests are wrong and ignore the failures",
    option_b: "Differences in environment: database version, configuration, dependencies, or data between QA and staging",
    option_c: "File all failures as bugs immediately",
    option_d: "Redeploy the same build and see if it passes the second time",
    answer: "B",
    explanation: "When identical code behaves differently in two environments, the environment is the variable. Check for differences in database versions, environment variables, API integrations, or data state between environments.",
  },
  {
    lesson_title: "Test Environments & Configurations",
    question: "What is the purpose of an environment readiness checklist before test execution begins?",
    option_a: "To slow down testing with bureaucratic approvals",
    option_b: "To verify all prerequisites are in place so test failures are due to bugs, not environment issues",
    option_c: "To document who built the environment",
    option_d: "To list all test cases that will run",
    answer: "B",
    explanation: "An environment readiness checklist (correct build deployed, services running, test data seeded, integrations configured) ensures that failures during testing are caused by defects, not broken infrastructure.",
  },
  {
    lesson_title: "Test Environments & Configurations",
    question: "Your team discovers staging is running a database version 2 minor versions behind production. The release is in 2 days. What do you do?",
    option_a: "Ignore it — minor version differences don't matter",
    option_b: "Immediately upgrade staging to match production, then rerun any database-dependent tests",
    option_c: "Continue testing and note the discrepancy in the test report",
    option_d: "Cancel the release until staging matches production exactly",
    answer: "B",
    explanation: "Environment parity is critical. Even minor version differences can affect query behavior, performance, or functionality. Upgrade staging and rerun affected tests before the release — 2 days is enough time.",
  },
  {
    lesson_title: "Test Environments & Configurations",
    question: "What is containerization (e.g., Docker) and how does it improve test environment consistency?",
    option_a: "A way to store test data in files",
    option_b: "A technology that packages the application and all its dependencies into a single portable image, ensuring the same environment runs everywhere",
    option_c: "A cloud hosting service",
    option_d: "A type of automated testing framework",
    answer: "B",
    explanation: "Docker containers package the application with exact dependencies and configurations, eliminating environment differences between developer machines, QA environments, and production.",
  },
  {
    lesson_title: "Test Environments & Configurations",
    question: "Why is testing directly in a production environment considered risky?",
    option_a: "Production environments are too fast for testing",
    option_b: "Test data can affect real users and test actions can corrupt real customer data",
    option_c: "Production doesn't have the right browser versions",
    option_d: "Testing in production is always prohibited by regulations",
    answer: "B",
    explanation: "Testing in production risks creating fake orders, corrupting real customer data, sending real emails to customers, and disrupting live user sessions. Dedicated test environments exist specifically to avoid this.",
  },
  {
    lesson_title: "Test Environments & Configurations",
    question: "A developer says 'it works on my machine.' What systemic problem does this typically indicate?",
    option_a: "The developer is lying about testing their code",
    option_b: "There is an environment discrepancy — the developer's machine differs from the test/production environment",
    option_c: "QA is not skilled enough to reproduce the issue",
    option_d: "The test case is incorrect",
    answer: "B",
    explanation: "'Works on my machine' indicates environment inconsistency — different OS, software versions, configurations, or data between the developer's local setup and the test/production environment. The fix is environment parity through containers or Infrastructure-as-Code.",
  },
  {
    lesson_title: "Test Environments & Configurations",
    question: "What is cross-browser testing and why is it important?",
    option_a: "Testing the same feature on different web browsers to verify consistent behavior",
    option_b: "Testing a browser's security features against known vulnerabilities",
    option_c: "Comparing the speed of different browsers",
    option_d: "Testing that browsers correctly render competitor websites",
    answer: "A",
    explanation: "Web applications can behave differently across Chrome, Firefox, Safari, and Edge due to different rendering engines. Cross-browser testing ensures all target users have a consistent experience.",
  },
  {
    lesson_title: "Test Environments & Configurations",
    question: "You're asked to test a new third-party payment gateway integration. What environment setup questions do you raise before starting?",
    option_a: "None — just start testing and see what happens",
    option_b: "Does the test environment have a sandbox API key? Are real transactions charged? Are test card numbers available? Is the integration configured for test mode?",
    option_c: "Only ask what browser to use",
    option_d: "Ask the payment gateway to set up a separate server for QA",
    answer: "B",
    explanation: "Payment gateway integrations require sandbox/test mode configuration. Without it, you could be testing against real payment processing. Always confirm: sandbox API keys are configured, test card numbers are available, and no real charges occur.",
  },
  {
    lesson_title: "Test Environments & Configurations",
    question: "What is a 'test environment teardown' and why is it performed?",
    option_a: "Physically removing the test server hardware after a project ends",
    option_b: "Cleaning up test data, resetting configurations, and returning the environment to a known baseline state after testing completes",
    option_c: "Deleting all test cases from the test management tool",
    option_d: "Uninstalling the application from all devices",
    answer: "B",
    explanation: "Teardown ensures the environment is clean for the next test cycle. Leftover test data, changed configurations, or modified state can cause incorrect results in subsequent test runs.",
  },
  {
    lesson_title: "Test Environments & Configurations",
    question: "What does 'configuration testing' verify?",
    option_a: "That all test cases have correct configuration IDs",
    option_b: "That the application behaves correctly across different hardware, OS, browser, and network configurations",
    option_c: "That the test environment's firewall is properly configured",
    option_d: "That developers follow coding standards",
    answer: "B",
    explanation: "Configuration testing verifies the application works across different supported environments — browsers, OS versions, screen resolutions, network speeds. It catches issues that only appear in specific configurations.",
  },
];
