import type { QuizRow } from "../../quiz-types";

export const exploratoryTestingQuizzes: QuizRow[] = [
  {
    lesson_title: "Exploratory Testing",
    question: "What is the primary characteristic of exploratory testing?",
    option_a: "All test cases are written before execution",
    option_b: "Testing and test design happen simultaneously",
    option_c: "Only automated tools are used",
    option_d: "Only functional areas are tested",
    answer: "B",
    explanation: "Exploratory testing is simultaneous learning, test design, and execution. The tester uses their knowledge and creativity in real-time rather than following pre-written scripts.",
  },
  {
    lesson_title: "Exploratory Testing",
    question: "What is a 'charter' in session-based exploratory testing?",
    option_a: "A legal document for testing",
    option_b: "A mission statement that guides a testing session",
    option_c: "A list of all test cases",
    option_d: "A bug report template",
    answer: "B",
    explanation: "A charter defines the mission of an exploratory session: what area to explore, how to approach it, and what you're trying to learn or find.",
  },
  {
    lesson_title: "Exploratory Testing",
    question: "What is the recommended duration for a session-based exploratory testing session?",
    option_a: "5-10 minutes",
    option_b: "4-8 hours",
    option_c: "45-90 minutes",
    option_d: "1 full day",
    answer: "C",
    explanation: "Sessions of 45-90 minutes are optimal — long enough to explore deeply, short enough to maintain focus and document findings accurately.",
  },
  {
    lesson_title: "Exploratory Testing",
    question: "Which of these is a good heuristic to use during exploratory testing?",
    option_a: "Only test the happy path",
    option_b: "CRUD — verify Create, Read, Update, Delete for every entity",
    option_c: "Focus only on the most recent feature",
    option_d: "Never take notes during exploration",
    answer: "B",
    explanation: "CRUD is a powerful heuristic — verifying all four operations exist and work correctly for every entity catches common omissions and bugs.",
  },
  {
    lesson_title: "Exploratory Testing",
    question: "When is exploratory testing most valuable?",
    option_a: "When all requirements are perfectly documented",
    option_b: "For regression testing of stable features",
    option_c: "For new features with incomplete specs and to find unexpected bugs",
    option_d: "When running automated test suites",
    answer: "C",
    explanation: "Exploratory testing shines for new or incomplete features where scripted tests can't anticipate everything, and when trying to find bugs that formal test cases miss.",
  },
];
