import type { QuizRow } from "../../quiz-types";

export const exploratoryTestingQuizzes: QuizRow[] = [
  {
    lesson_title: "Exploratory Testing",
    question: "What is the primary characteristic of exploratory testing?",
    option_a: "All test cases are written before execution",
    option_b: "Testing and test design happen simultaneously",
    option_c: "Only automated tools are used",
    option_d: "Only functional areas are tested",
    answer: "B",
    explanation: "Exploratory testing is simultaneous learning, test design, and execution. The tester uses their knowledge and creativity in real-time rather than following pre-written scripts.",
  },
  {
    lesson_title: "Exploratory Testing",
    question: "What is a 'charter' in session-based exploratory testing?",
    option_a: "A legal document for testing",
    option_b: "A mission statement that guides a testing session",
    option_c: "A list of all test cases",
    option_d: "A bug report template",
    answer: "B",
    explanation: "A charter defines the mission of an exploratory session: what area to explore, how to approach it, and what you're trying to learn or find.",
  },
  {
    lesson_title: "Exploratory Testing",
    question: "What is the recommended duration for a session-based exploratory testing session?",
    option_a: "5–10 minutes",
    option_b: "4–8 hours",
    option_c: "45–90 minutes",
    option_d: "1 full day",
    answer: "C",
    explanation: "Sessions of 45–90 minutes are optimal — long enough to explore deeply, short enough to maintain focus and document findings accurately.",
  },
  {
    lesson_title: "Exploratory Testing",
    question: "Which of these is a good heuristic to use during exploratory testing?",
    option_a: "Only test the happy path",
    option_b: "CRUD — verify Create, Read, Update, Delete for every entity",
    option_c: "Focus only on the most recent feature",
    option_d: "Never take notes during exploration",
    answer: "B",
    explanation: "CRUD is a powerful heuristic — verifying all four operations exist and work correctly for every entity catches common omissions and bugs.",
  },
  {
    lesson_title: "Exploratory Testing",
    question: "When is exploratory testing most valuable?",
    option_a: "When all requirements are perfectly documented",
    option_b: "For regression testing of stable features",
    option_c: "For new features with incomplete specs and to find unexpected bugs that formal test cases miss",
    option_d: "When running automated test suites",
    answer: "C",
    explanation: "Exploratory testing shines for new or incomplete features where scripted tests can't anticipate everything, and when trying to find bugs that formal test cases miss.",
  },
  {
    lesson_title: "Exploratory Testing",
    question: "What is the difference between scripted testing and exploratory testing?",
    option_a: "Scripted tests use code; exploratory tests are always manual",
    option_b: "Scripted tests follow pre-defined steps; exploratory tests use real-time judgment to decide what to test next",
    option_c: "Exploratory testing is less rigorous and produces no documentation",
    option_d: "Scripted tests find more bugs per hour than exploratory tests",
    answer: "B",
    explanation: "Scripted tests follow a pre-defined path — great for regression. Exploratory testing uses the tester's knowledge, intuition, and real-time learning to investigate freely — great for finding unexpected defects.",
  },
  {
    lesson_title: "Exploratory Testing",
    question: "You have 2 hours to explore a new mobile checkout flow with no test cases written yet. Describe the best approach.",
    option_a: "Skip testing since there are no test cases to execute",
    option_b: "Write a charter, time-box the session, explore using heuristics like CRUD and boundary inputs, and document findings in real-time",
    option_c: "Wait for the product owner to write acceptance criteria first",
    option_d: "Automate the happy path and report the automation coverage",
    answer: "B",
    explanation: "For unscripted exploration: define a charter (mission), use heuristics (CRUD, boundary values, error scenarios), take notes as you go, and debrief findings at the end. 2 hours is ideal for a focused session.",
  },
  {
    lesson_title: "Exploratory Testing",
    question: "During exploratory testing, you discover a critical bug that wasn't in any test charter. What do you do?",
    option_a: "Ignore it since it's outside the charter scope",
    option_b: "Stop your current session and immediately investigate only that bug",
    option_c: "Note the bug with reproduction steps, file it, then decide whether to continue the current charter or pivot",
    option_d: "Continue the charter and report all bugs at the session end",
    answer: "C",
    explanation: "Document and file the critical bug immediately so it's not lost. Then make a judgment call: if it's severe enough to require immediate investigation, pivot — otherwise note it and continue. Don't ignore it.",
  },
  {
    lesson_title: "Exploratory Testing",
    question: "What is the SFDIPOT heuristic (San Francisco Depot) used for in exploratory testing?",
    option_a: "A framework for writing formal test cases",
    option_b: "A mnemonic to guide exploration: Structure, Function, Data, Interfaces, Platform, Operations, Time",
    option_c: "A bug severity classification system",
    option_d: "A CI/CD pipeline deployment checklist",
    answer: "B",
    explanation: "SFDIPOT provides lenses for exploring: Structure (how the system is built), Function (what it does), Data (inputs/outputs), Interfaces (connections), Platform (environment), Operations (usage patterns), Time (timing constraints).",
  },
  {
    lesson_title: "Exploratory Testing",
    question: "Why is exploratory testing NOT a suitable replacement for automated regression tests?",
    option_a: "Exploratory testing is too expensive",
    option_b: "Exploratory testing cannot be documented",
    option_c: "Exploratory testing relies on human judgment each time, making it inconsistent for verifying the same scenarios repeatedly",
    option_d: "Exploratory testing only works on mobile applications",
    answer: "C",
    explanation: "Regression testing requires consistent, repeatable execution of the same scenarios. Automation does this reliably at scale. Exploratory testing's strength is discovery, not verification — the two are complementary.",
  },
  {
    lesson_title: "Exploratory Testing",
    question: "What is a 'debrief' in session-based exploratory testing?",
    option_a: "The report filed at the end of the project",
    option_b: "A short review after a session where the tester reports what was tested, bugs found, and areas not covered",
    option_c: "A meeting to assign new test cases",
    option_d: "The process of converting exploratory notes into formal test cases",
    answer: "B",
    explanation: "A debrief is a short post-session review (5–10 minutes) where the tester reports: what was covered, bugs found, areas not tested, and notes for follow-up sessions — providing accountability and visibility.",
  },
  {
    lesson_title: "Exploratory Testing",
    question: "A stakeholder asks 'how do you know you've tested enough during exploratory testing?' How do you answer?",
    option_a: "You can never be sure — exploratory testing has no end criteria",
    option_b: "When the test session timer runs out",
    option_c: "When coverage criteria are met: areas in the charter are explored, known risks are investigated, and session notes show reasonable depth",
    option_d: "When no more bugs are found",
    answer: "C",
    explanation: "Sufficiency in exploratory testing is judged by coverage of the charter's mission, exploration of known risk areas, and consistency of findings (bug rate dropping). Session notes and charters provide accountability.",
  },
  {
    lesson_title: "Exploratory Testing",
    question: "A feature has vague, incomplete requirements. Why is exploratory testing especially valuable in this situation?",
    option_a: "It allows you to skip testing entirely since requirements aren't clear",
    option_b: "Exploratory testing surfaces undefined edge cases and behavior gaps that scripted tests (which rely on clear requirements) would miss entirely",
    option_c: "It's only valuable when requirements are complete",
    option_d: "It lets testers make up their own requirements",
    answer: "B",
    explanation: "Vague requirements mean scripted tests can only cover what's known. Exploratory testing uses heuristics and real user simulation to find unexpected behavior, integration issues, and interpretation gaps that no one anticipated.",
  },
  {
    lesson_title: "Exploratory Testing",
    question: "What is 'pair testing' in exploratory testing?",
    option_a: "Two testers independently testing the same feature and comparing results",
    option_b: "Two testers working together on the same machine — one exploring, one observing and taking notes — combining their perspectives",
    option_c: "A developer and a tester writing automated tests together",
    option_d: "Testing across two different environments simultaneously",
    answer: "B",
    explanation: "Pair testing has two people working together — one drives (navigates, interacts) while the other observes, takes notes, and thinks critically. The collaboration finds more bugs than either would alone.",
  },
  {
    lesson_title: "Exploratory Testing",
    question: "What tester mindset is most essential for effective exploratory testing?",
    option_a: "Following instructions precisely without deviation",
    option_b: "Skeptical curiosity — questioning assumptions, trying unexpected inputs, and actively looking for ways the system might fail",
    option_c: "Optimism — testing the happy path thoroughly",
    option_d: "Speed — covering as many features as possible in minimum time",
    answer: "B",
    explanation: "Effective exploratory testers are naturally skeptical and curious. They ask 'what if I do this?', 'what could go wrong here?', and 'what does the system do with unexpected input?' — thinking like both a user and an adversary.",
  },
];
