import type { QuizRow } from "../../quiz-types";

export const introductionToApiTestingQuizzes: QuizRow[] = [
  {
    lesson_title: "Introduction to API Testing",
    question: "What HTTP method is used to retrieve data from a server?",
    option_a: "POST",
    option_b: "PUT",
    option_c: "GET",
    option_d: "DELETE",
    answer: "C",
    explanation: "GET is used to read/retrieve resources. It should not change server state — it's a read-only operation.",
  },
  {
    lesson_title: "Introduction to API Testing",
    question: "What HTTP status code indicates a resource was not found?",
    option_a: "200",
    option_b: "400",
    option_c: "401",
    option_d: "404",
    answer: "D",
    explanation: "404 Not Found means the requested resource doesn't exist. This is one of the most important status codes for API testers to know.",
  },
  {
    lesson_title: "Introduction to API Testing",
    question: "What does HTTP status 401 mean?",
    option_a: "Resource not found",
    option_b: "Request not authenticated — no or invalid credentials provided",
    option_c: "Authenticated but not authorized",
    option_d: "Server error",
    answer: "B",
    explanation: "401 Unauthorized means authentication is required or has failed. The request lacks valid authentication credentials.",
  },
  {
    lesson_title: "Introduction to API Testing",
    question: "What does HTTP status 403 mean?",
    option_a: "Not authenticated",
    option_b: "Resource not found",
    option_c: "Authenticated but forbidden — user lacks permission",
    option_d: "Bad request",
    answer: "C",
    explanation: "403 Forbidden means the user IS authenticated but does NOT have permission for the requested resource (different from 401).",
  },
  {
    lesson_title: "Introduction to API Testing",
    question: "What HTTP method is used to create a new resource?",
    option_a: "GET",
    option_b: "POST",
    option_c: "DELETE",
    option_d: "PATCH",
    answer: "B",
    explanation: "POST is used to create new resources. The server creates the resource and typically returns 201 Created with the new resource's data.",
  },
  {
    lesson_title: "Introduction to API Testing",
    question: "What is an advantage of API testing over UI testing?",
    option_a: "API tests are always cheaper to write",
    option_b: "API tests validate user experience better",
    option_c: "API tests are faster, more stable, and catch business logic issues early",
    option_d: "API tests don't need test data",
    answer: "C",
    explanation: "API tests are significantly faster than UI tests, more stable (APIs change less than UIs), and can test business logic without a working UI.",
  },
  {
    lesson_title: "Introduction to API Testing",
    question: "In REST APIs, what does the response body typically contain?",
    option_a: "HTML markup",
    option_b: "JSON or XML data",
    option_c: "SQL queries",
    option_d: "Binary files only",
    answer: "B",
    explanation: "REST APIs typically return JSON (most common) or XML formatted data that represents the requested resource or operation result.",
  },
  {
    lesson_title: "Introduction to API Testing",
    question: "What is Postman primarily used for?",
    option_a: "Writing and running automated UI tests",
    option_b: "Sending and testing HTTP requests to APIs",
    option_c: "Managing databases",
    option_d: "Creating test plans",
    answer: "B",
    explanation: "Postman is an API testing tool that allows you to send HTTP requests, inspect responses, write assertions, and manage collections of API tests.",
  },
];
