import type { QuizRow } from "../../quiz-types";

export const introductionToApiTestingQuizzes: QuizRow[] = [
  {
    lesson_title: "Introduction to API Testing",
    question: "What HTTP method is used to retrieve data from a server?",
    option_a: "POST",
    option_b: "PUT",
    option_c: "GET",
    option_d: "DELETE",
    answer: "C",
    explanation: "GET is used to read/retrieve resources. It should not change server state — it's a read-only operation.",
  },
  {
    lesson_title: "Introduction to API Testing",
    question: "What HTTP status code indicates a resource was not found?",
    option_a: "200",
    option_b: "400",
    option_c: "401",
    option_d: "404",
    answer: "D",
    explanation: "404 Not Found means the requested resource doesn't exist. This is one of the most important status codes for API testers to know.",
  },
  {
    lesson_title: "Introduction to API Testing",
    question: "What does HTTP status 401 mean?",
    option_a: "Resource not found",
    option_b: "Request not authenticated — no or invalid credentials provided",
    option_c: "Authenticated but not authorized",
    option_d: "Server error",
    answer: "B",
    explanation: "401 Unauthorized means authentication is required or has failed. The request lacks valid authentication credentials.",
  },
  {
    lesson_title: "Introduction to API Testing",
    question: "What does HTTP status 403 mean?",
    option_a: "Not authenticated",
    option_b: "Resource not found",
    option_c: "Authenticated but forbidden — user lacks permission",
    option_d: "Bad request",
    answer: "C",
    explanation: "403 Forbidden means the user IS authenticated but does NOT have permission for the requested resource (different from 401).",
  },
  {
    lesson_title: "Introduction to API Testing",
    question: "What HTTP method is used to create a new resource?",
    option_a: "GET",
    option_b: "POST",
    option_c: "DELETE",
    option_d: "PATCH",
    answer: "B",
    explanation: "POST is used to create new resources. The server creates the resource and typically returns 201 Created with the new resource's data.",
  },
  {
    lesson_title: "Introduction to API Testing",
    question: "What is an advantage of API testing over UI testing?",
    option_a: "API tests are always cheaper to write",
    option_b: "API tests validate user experience better",
    option_c: "API tests are faster, more stable, and catch business logic issues earlier",
    option_d: "API tests don't need test data",
    answer: "C",
    explanation: "API tests are significantly faster than UI tests, more stable (APIs change less than UIs), and can test business logic without a working UI.",
  },
  {
    lesson_title: "Introduction to API Testing",
    question: "In REST APIs, what does the response body typically contain?",
    option_a: "HTML markup",
    option_b: "JSON or XML data",
    option_c: "SQL queries",
    option_d: "Binary files only",
    answer: "B",
    explanation: "REST APIs typically return JSON (most common) or XML formatted data that represents the requested resource or operation result.",
  },
  {
    lesson_title: "Introduction to API Testing",
    question: "What is Postman primarily used for?",
    option_a: "Writing and running automated UI tests",
    option_b: "Sending and testing HTTP requests to APIs",
    option_c: "Managing databases",
    option_d: "Creating test plans",
    answer: "B",
    explanation: "Postman is an API testing tool that allows you to send HTTP requests, inspect responses, write assertions, and manage collections of API tests.",
  },
  {
    lesson_title: "Introduction to API Testing",
    question: "You're testing a user registration API endpoint (POST /users). List the most important test cases to cover.",
    option_a: "Only test the happy path — valid data creating a new user",
    option_b: "Valid registration, duplicate email, missing required fields, invalid email format, and password too short",
    option_c: "Only test error cases — the happy path is assumed to work",
    option_d: "Test only the status code, not the response body",
    answer: "B",
    explanation: "A thorough API test covers: the happy path (201 Created, correct body), negative cases (duplicate email → 409 or 422, missing fields → 400, invalid email → 400), and boundary conditions. Both success and failure paths matter.",
  },
  {
    lesson_title: "Introduction to API Testing",
    question: "Which HTTP status code indicates a bad request due to malformed data or missing required fields?",
    option_a: "200",
    option_b: "401",
    option_c: "400",
    option_d: "500",
    answer: "C",
    explanation: "400 Bad Request means the server cannot process the request due to client error — malformed JSON, missing required fields, or invalid data format. The client must fix the request.",
  },
  {
    lesson_title: "Introduction to API Testing",
    question: "A developer says 'the UI works perfectly, so the API must be fine.' Why is this reasoning flawed?",
    option_a: "It's not flawed — if the UI works, the API definitely works",
    option_b: "The UI only exercises a subset of API scenarios; direct API testing can reveal edge cases, missing validations, and security issues the UI never triggers",
    option_c: "APIs don't need testing if developers write unit tests",
    option_d: "UI tests are less reliable than the developer's reasoning",
    answer: "B",
    explanation: "The UI only calls the API in the ways it was designed to. Direct API testing reveals what happens with edge case inputs, missing fields, unusual data, or unauthorized requests — none of which the UI typically sends.",
  },
  {
    lesson_title: "Introduction to API Testing",
    question: "What is the difference between HTTP PUT and PATCH?",
    option_a: "PUT creates; PATCH deletes",
    option_b: "PUT replaces the entire resource; PATCH applies a partial update to specific fields",
    option_c: "They are identical — use either one",
    option_d: "PATCH is more secure than PUT",
    answer: "B",
    explanation: "PUT replaces the entire resource with the request body. PATCH modifies only the specified fields. Testing both means verifying PUT requires all fields and PATCH can update one field without affecting others.",
  },
  {
    lesson_title: "Introduction to API Testing",
    question: "You send DELETE /users/123 and get a 200 OK response. How do you verify the user was actually deleted?",
    option_a: "Trust the 200 OK response — the server confirmed deletion",
    option_b: "Send GET /users/123 and expect a 404 Not Found response",
    option_c: "Send DELETE /users/123 again and see if it returns an error",
    option_d: "Check the response body for a 'deleted' field",
    answer: "B",
    explanation: "Never trust only the response of the operation — verify the state change. Send GET /users/123 after deletion and confirm you receive 404 Not Found. This proves the resource is actually gone.",
  },
  {
    lesson_title: "Introduction to API Testing",
    question: "What is an API request header used for?",
    option_a: "Storing the main data payload of the request",
    option_b: "Passing metadata such as authentication tokens, content type, and accepted response formats",
    option_c: "Specifying the HTTP method",
    option_d: "Defining the server's URL",
    answer: "B",
    explanation: "HTTP headers carry metadata: Authorization (auth tokens), Content-Type (format of request body), Accept (format expected in response). Testing headers means verifying behavior with valid/invalid/missing authorization tokens.",
  },
  {
    lesson_title: "Introduction to API Testing",
    question: "What does HTTP status 500 indicate and what should a QA engineer do when they see it?",
    option_a: "500 means the request was successful — no action needed",
    option_b: "500 Internal Server Error means the server crashed — file a bug with the exact request that triggered it and check server logs",
    option_c: "500 means the client sent wrong data — fix the request",
    option_d: "500 is expected for performance testing scenarios",
    answer: "B",
    explanation: "500 is a server-side failure — a bug in the application code. File a bug report with: exact request (method, URL, headers, body), steps to reproduce, and any error details from the response. This is typically a high-severity defect.",
  },
];
