import { toQuizRows } from "../supplement-utils";

export const beginnerSupplementBanks = {
  "What is Software Testing?": [
    [
      "Which of the following BEST describes the relationship between Verification and Validation in testing?",
      "Verification and Validation are the same thing",
      "Verification checks if we're building the product right; Validation checks if we're building the right product",
      "Verification is done by QA; Validation is done by developers",
      "Verification only applies to code reviews",
      "B",
      "Verification is a checking activity (does it match the spec). Validation is a user-centric activity (does it meet user needs).",
    ],
    [
      "According to the 7 Testing Principles (ISTQB), what does the pesticide paradox mean?",
      "Testing poisons code quality",
      "Testers need protective equipment",
      "Repeating the same tests finds fewer new bugs over time; test suites must evolve",
      "Pesticides should never be used near software",
      "C",
      "The pesticide paradox (principle 5) states that using the same test cases repeatedly results in diminishing returns — new tests are needed.",
    ],
    [
      "What is the ISO 25010 quality characteristic that refers to 'ease of use'?",
      "Reliability",
      "Usability",
      "Compatibility",
      "Performance Efficiency",
      "B",
      "Usability is the ISO 25010 characteristic that measures how effectively and easily users can accomplish their goals.",
    ],
    [
      "In the context of testing, what does 'fitness for use' imply?",
      "The software must pass all unit tests",
      "The software meets both functional requirements and user expectations",
      "The software has zero defects",
      "The software is deployed to production",
      "B",
      "Fitness for use means the software is suitable for its intended purpose — functionally complete and meets user needs.",
    ],
    [
      "Which scenario is an example of the 7th testing principle ('Absence-of-errors fallacy')?",
      "A feature works perfectly but doesn't solve the user's actual problem",
      "A tester found all the bugs",
      "The application never crashes",
      "The code has 100% coverage",
      "A",
      "The absence-of-errors fallacy means a bug-free product that doesn't meet user needs is still a failure — quality isn't just absence of bugs.",
    ],
  ] as const,

  "Software Development Life Cycle (SDLC)": [
    [
      "In which SDLC model is testing typically introduced in parallel with development rather than after?",
      "Waterfall",
      "Agile",
      "V-Model",
      "Linear",
      "B",
      "In Agile, testing is integrated into every sprint. QA works in parallel with development, not as a separate sequential phase.",
    ],
    [
      "What is the primary benefit of the V-Model for safety-critical systems?",
      "It requires fewer test cases",
      "Testing is planned early with clear entry/exit criteria at each level",
      "It eliminates the need for integration testing",
      "It's faster than other SDLC models",
      "B",
      "The V-Model's structure ensures rigorous verification and validation — each dev phase has a corresponding test phase, ideal for high-stakes systems.",
    ],
    [
      "What does Shift-Right testing refer to?",
      "Moving tests from left to right in documentation",
      "Testing activities performed after deployment using monitoring and feature flags",
      "Shifting team members to different departments",
      "Running tests from right-to-left on the keyboard",
      "B",
      "Shift-Right means testing in production environments using canary deployments, monitoring, and synthetic checks to learn from real usage.",
    ],
    [
      "In the Spiral Model, which phase is most relevant for QA's involvement in risk identification?",
      "Engineering phase only",
      "Risk Analysis and Evaluation phases",
      "Planning phase only",
      "None — QA is not involved in Spiral Model",
      "B",
      "The Spiral Model's strength is its risk-driven approach; QA participates in risk analysis and evaluation across each spiral iteration.",
    ],
    [
      "How does CI/CD (Continuous Integration/Continuous Deployment) fundamentally change QA's role compared to Waterfall?",
      "QA is no longer needed in CI/CD",
      "QA becomes a gatekeeper focused on preventing bad releases through automated testing in the pipeline",
      "QA only works during the final deployment phase",
      "Testing is done less frequently in CI/CD",
      "B",
      "In CI/CD, QA must shift-left: automated tests are embedded in the pipeline, and QA becomes responsible for test automation and early feedback.",
    ],
  ] as const,

  "Software Testing Life Cycle (STLC)": [
    [
      "What document links every requirement to its corresponding test case?",
      "Test Case Document",
      "Requirements Traceability Matrix (RTM)",
      "Test Plan",
      "Test Closure Report",
      "B",
      "The RTM (Requirements Traceability Matrix) ensures every requirement has at least one test case and no test case is orphaned.",
    ],
    [
      "Which STLC phase produces the Requirements Understanding Document (RUD)?",
      "Test Planning",
      "Requirement Analysis",
      "Test Case Development",
      "Test Environment Setup",
      "B",
      "Requirement Analysis is the first STLC phase where QA classifies requirements and produces the RUD or similar documentation.",
    ],
    [
      "What is the relationship between entry criteria and exit criteria in STLC?",
      "They are identical",
      "Entry criteria define when a phase can begin; exit criteria define when it is complete",
      "Exit criteria apply only to the final phase",
      "They are determined by the developer",
      "B",
      "Entry criteria (prerequisites to start) and exit criteria (conditions for completion) create gate structures that ensure phase quality.",
    ],
    [
      "During Test Environment Setup, what does a smoke test validate?",
      "The environment can handle peak load",
      "That the test environment is functional and basic features work",
      "All test cases pass on the first try",
      "The database has sufficient capacity",
      "B",
      "A smoke test is a quick, shallow validation that the environment is ready for formal testing — checking if critical paths work.",
    ],
    [
      "Why is peer review a critical part of the Test Case Development phase?",
      "It increases project costs",
      "It ensures test cases are clear, complete, effective, and free of ambiguity",
      "It is required by all companies",
      "It replaces the need for test execution",
      "B",
      "Peer review catches gaps, ambiguities, and design flaws in test cases before execution — improving quality and preventing wasted test cycles.",
    ],
  ] as const,

  "Types of Testing": [
    [
      "Which testing type specifically verifies that different components of a system work correctly together at their interfaces?",
      "Unit Testing",
      "System Testing",
      "Integration Testing",
      "Smoke Testing",
      "C",
      "Integration testing focuses on interfaces and interactions between components, catching defects at boundaries.",
    ],
    [
      "What is the primary difference between stress testing and load testing?",
      "Stress testing uses automated tools; load testing is manual",
      "Load testing verifies normal expected load; stress testing pushes beyond capacity to find breaking points",
      "They are the same thing",
      "Stress testing is for APIs; load testing is for UIs",
      "B",
      "Load testing validates performance under expected conditions; stress testing intentionally exceeds capacity to find limits and failure modes.",
    ],
    [
      "Which testing type evaluates if the software works across different browsers, OSes, and devices?",
      "Usability Testing",
      "Performance Testing",
      "Compatibility Testing",
      "Accessibility Testing",
      "C",
      "Compatibility testing checks that software functions correctly in different environments — browsers, operating systems, devices.",
    ],
    [
      "What is contract testing and why is it important in microservices?",
      "A legal agreement between testers and developers",
      "Verifies that service consumer and provider agree on API contracts to prevent integration breaks",
      "Testing that only applies to contracted vendors",
      "A type of acceptance testing",
      "B",
      "Contract testing (using tools like Pact) ensures microservices maintain agreed-upon API contracts, preventing incompatibilities between services.",
    ],
    [
      "When should acceptance testing (UAT) occur in the lifecycle?",
      "During development while features are being coded",
      "Before deployment, when the system is feature-complete and ready for business validation",
      "Only in production after go-live",
      "Alongside unit testing",
      "B",
      "UAT happens before deployment when the system is ready. End users validate it meets their business needs before the organization commits to go-live.",
    ],
  ] as const,

  "Writing Your First Test Case": [
    [
      "What is an 'edge case' in the context of test case design?",
      "A test case that is located at the edge of the test management tool",
      "Unusual but valid inputs that sit at the boundaries of acceptable values",
      "A test case that fails",
      "A test case written at the end of the project",
      "B",
      "Edge cases are boundary conditions — unusual but valid inputs that often expose bugs due to off-by-one errors or boundary logic flaws.",
    ],
    [
      "Why is it important to link test cases to requirements?",
      "It increases the number of test cases",
      "It enables requirement traceability and ensures no requirement is tested and no test is orphaned",
      "It makes testing slower",
      "It reduces the need for test planning",
      "B",
      "Traceability links every requirement to at least one test case and vice versa, ensuring complete coverage and visibility.",
    ],
    [
      "What does the 'Status' field in a test case indicate?",
      "The priority of the bug it found",
      "The severity of the issue being tested",
      "The result of test execution: Pass, Fail, Blocked, Skipped, or Not Run",
      "The estimated duration of the test",
      "C",
      "The Status field records the outcome when the test is executed, indicating whether it passed, failed, was blocked, skipped, or hasn't been run.",
    ],
    [
      "How do you write test data that ensures repeatability?",
      "Use random or generated values each time",
      "Use exact, specific values that produce consistent results across runs",
      "Use production data directly",
      "Avoid using test data altogether",
      "B",
      "Specific, fixed test data ensures the same steps produce the same result every time — a prerequisite for repeatability and reliability.",
    ],
    [
      "What is the risk of having dependencies between test cases?",
      "It makes tests run faster",
      "One test failure causes cascading failures; tests can't be run independently or in any order",
      "It improves code coverage",
      "It reduces the need for test data",
      "B",
      "Test dependencies create fragile test suites where one failure breaks multiple downstream tests, making debugging harder and reducing flexibility.",
    ],
  ] as const,

  "Bug Reporting Fundamentals": [
    [
      "What is the purpose of including test data in a bug report?",
      "To show the developer how much testing was done",
      "To allow developers to reproduce the bug using exact values, not ambiguous descriptions",
      "To reduce the severity rating",
      "To increase the priority of the bug",
      "B",
      "Exact test data (real email addresses, specific values) enables developers to reproduce the bug reliably without guessing.",
    ],
    [
      "Which statement best describes an 'orphan bug' in issue tracking?",
      "A bug that has not been assigned to anyone",
      "A bug reported by an external user",
      "A bug that is not linked to any test case, requirement, or feature — making it harder to understand context",
      "A bug that was closed without being fixed",
      "C",
      "An orphan bug lacks context and traceability, making it difficult for developers to understand where it came from and how to fix it.",
    ],
    [
      "When reporting an intermittent bug, what should be documented?",
      "Only the steps to reproduce",
      "Frequency, timestamps, environmental variations, and any patterns in when it occurs",
      "Nothing extra — just report it like any other bug",
      "The developer's name",
      "B",
      "Intermittent bugs are hard to diagnose; documenting frequency, conditions, timestamps, and patterns helps developers identify root causes.",
    ],
    [
      "What makes a bug report actionable for a developer?",
      "It uses technical jargon to sound professional",
      "It has a clear title, exact reproduction steps, expected vs actual results, and necessary attachments",
      "It lists all the features of the system",
      "It is submitted immediately without review",
      "B",
      "An actionable bug report has all the information developers need to reproduce, diagnose, and fix the issue without asking questions.",
    ],
    [
      "How should you handle finding a duplicate bug (already reported and assigned)?",
      "Report it separately",
      "Link the new report to the original and close it as 'Duplicate'",
      "Ignore it and continue testing",
      "Report it to the project manager privately",
      "B",
      "Linking duplicates prevents duplicate work, consolidates discussion, and provides developers with a clear picture of the bug's scope.",
    ],
  ] as const,

  "Defect Life Cycle": [
    [
      "What is the 'Deferred' state and when is it used?",
      "A temporary state while the bug is being investigated",
      "When a valid bug's fix is scheduled for a future release rather than the current one",
      "When a bug is no longer reproducible",
      "An error status in the tracking system",
      "B",
      "Deferred means the bug is confirmed valid but the team has decided to fix it later due to priority or resource constraints.",
    ],
    [
      "During the Retest phase, what should QA verify?",
      "Only that the specific bug fix works",
      "That the fix works AND that no new issues were introduced (regression testing)",
      "That the developer is competent",
      "That the fix works in all environments simultaneously",
      "B",
      "Retest involves verifying the specific fix AND checking surrounding functionality to ensure the fix didn't cause regressions.",
    ],
    [
      "What is the purpose of bug triage meetings?",
      "To celebrate bugs found",
      "To review new bugs, confirm validity, assign severity/priority, and decide on assignment and target release",
      "To fire team members responsible for bugs",
      "To write bug reports",
      "B",
      "Triage meetings ensure new bugs are quickly assessed, prioritized, and assigned — preventing bugs from languishing in 'New' status.",
    ],
    [
      "What does an SLA (Service Level Agreement) define in the context of defects?",
      "The total number of bugs allowed in a release",
      "Expected response and resolution times based on bug severity",
      "The tools used for bug tracking",
      "The names of developers assigned to bugs",
      "B",
      "SLAs set expectations — e.g., 'Critical bugs must have a response within 2 hours' — ensuring timely bug attention based on business impact.",
    ],
    [
      "What is 'defect aging' and why should it be monitored?",
      "The age of the tester who found the bug",
      "The time a defect has been open without resolution; aging bugs indicate priority, dependency, or process issues",
      "How old a bug report can be before deletion",
      "The date the bug was first discovered",
      "B",
      "Defect aging reveals bottlenecks and process problems — old High-severity bugs signal blocking dependencies; old Lows may be 'Won't Fix'.",
    ],
    [
      "When does a bug move from 'Fixed' to 'Reopen'?",
      "When the developer completes the fix",
      "When QA retests the fix and determines it doesn't actually resolve the problem",
      "When the bug is reported again by another tester",
      "After 30 days of being in Fixed status",
      "B",
      "A bug is reopened when QA's retest reveals that the fix was incomplete or ineffective — the defect still exists.",
    ],
    [
      "What does the 'Rejected' defect status communicate?",
      "The developer refused to fix the bug",
      "The team determined the reported behavior is correct and intentional — not actually a defect",
      "The bug is too old to address",
      "The bug was resolved without any changes",
      "B",
      "Rejected means the behavior is working as designed; it is not a defect. QA must document the reasoning to prevent re-reporting.",
    ],
  ] as const,

  "Test Environments & Configurations": [
    [
      "What is the most common cause of 'false test failures' related to test environments?",
      "The tests are poorly written",
      "Environment drift — the test environment diverges from production configuration",
      "Testers are not following procedures",
      "Automation tools are unreliable",
      "B",
      "Environment drift causes bugs to appear/disappear inconsistently because the test environment no longer matches production.",
    ],
    [
      "How should feature flags be managed in test environments?",
      "Never use feature flags in testing",
      "Flags should be ON in QA to test new features and OFF to test baseline behavior — independently from production state",
      "Copy the production flag configuration into test environments",
      "Flags are only for development, not QA",
      "B",
      "QA must control flags independently to test both new features (flags ON) and baseline behavior (flags OFF) regardless of production state.",
    ],
    [
      "What is Docker Compose and why is it valuable for test environments?",
      "A JavaScript library for UI testing",
      "A tool to create isolated, reproducible, consistent environments in containers for reliable testing across machines",
      "A replacement for manual test case writing",
      "A database management system",
      "B",
      "Docker Compose enables consistent, isolated environments that run the same way on every developer's machine and CI/CD pipeline.",
    ],
    [
      "Which environment should be used for formal, planned test execution?",
      "Local developer machines",
      "Development server (constantly changing)",
      "QA/Testing environment (stable, controlled, owned by QA)",
      "Production",
      "C",
      "The QA/Testing environment is specifically designed for formal test execution — it's stable, controlled, and isolated from active development.",
    ],
    [
      "What environmental factors are critical for reproducing bugs consistently?",
      "Only the application version",
      "OS, database version, browser version, feature flags, third-party integrations, and exact deployed version",
      "Only the URL",
      "The tester's mood",
      "B",
      "Complete environmental documentation ensures bugs can be reliably reproduced by capturing all variables that might affect behavior.",
    ],
    [
      "What is a 'sandbox' in the context of test environments?",
      "A physical testing location",
      "An isolated, test-only instance of third-party services (e.g., Stripe Sandbox) that mimics production without affecting real data",
      "A type of automation framework",
      "A bug tracking tool",
      "B",
      "Sandboxes allow testing integrations with payment systems, email services, etc., using test credentials without touching production data.",
    ],
    [
      "Why should test environments be documented in detail?",
      "To create busy work for QA",
      "So bugs can be reliably reproduced, environment issues diagnosed, and test results properly interpreted",
      "Documentation is not needed",
      "Only for audits",
      "B",
      "Detailed documentation (URL, OS, versions, deployment date, feature flags) is essential for repeatability and troubleshooting.",
    ],
    [
      "What is the relationship between environment parity and false test results?",
      "They are unrelated",
      "Poor environment parity causes false failures — tests pass in QA but fail in production, or vice versa",
      "Perfect parity eliminates the need for staging",
      "Parity only matters for manual testing",
      "B",
      "When test environments diverge from production, tests become unreliable; results don't predict production behavior accurately.",
    ],
    [
      "What should be checked when conducting a smoke test on a new environment setup?",
      "Just the login page",
      "Critical paths: login, core workflows, database connectivity, and that basic features function",
      "Every feature in the system",
      "Only the UI appearance",
      "B",
      "A smoke test validates that the environment is fundamentally working — checking critical paths and basic functionality before detailed testing.",
    ],
    [
      "When is data seeding required for test environments?",
      "Never — use random data",
      "When test cases require specific pre-existing data (users, products, permissions) to set up proper test conditions",
      "Only in production",
      "Only for manual tests",
      "B",
      "Seeding populates the test environment with required reference data so tests can start in a known, consistent state.",
    ],
  ] as const,

  "Exploratory Testing": [
    [
      "What is the key difference between exploratory testing and scripted testing?",
      "Exploratory testing uses fewer tools",
      "Exploratory testing involves simultaneous learning, design, and execution; scripted testing follows pre-written steps",
      "Exploratory testing is always faster",
      "Scripted testing is used for new features only",
      "B",
      "Exploratory testing's strength is real-time adaptation; the tester learns and adjusts strategy during testing rather than following a rigid script.",
    ],
    [
      "What is the recommended format for writing an exploratory testing session charter?",
      "'Explore [area] with [approach] to discover [information/bugs]' — clear mission, method, and goal",
      "A detailed step-by-step test case",
      "Any question the tester wants to investigate",
      "A list of 50+ test cases",
      "A",
      "A well-formed charter gives direction and focus to the session without over-constraining; it answers what, how, and why.",
    ],
    [
      "What does the CRUD heuristic help testers discover?",
      "Only database problems",
      "Missing or broken Create, Read, Update, or Delete operations for entities",
      "Performance issues",
      "UI layout problems",
      "B",
      "CRUD tests ensure all four operations exist and work correctly for every entity — a powerful shortcut to finding feature gaps.",
    ],
    [
      "What is 'session-based exploratory testing' (SBET)?",
      "Testing during a single session without any structure",
      "Structured time-boxed sessions (45-90 min) guided by a charter, with notes and bug documentation",
      "Automated testing sessions",
      "Testing only in the morning",
      "B",
      "SBET structures exploratory testing with time limits, missions (charters), and documentation — balancing flexibility with rigor.",
    ],
    [
      "When is exploratory testing most valuable and why?",
      "Only for regression testing",
      "For new/incomplete features where formal test cases can't anticipate all behaviors; for finding unexpected bugs",
      "Only when test cases have not been written",
      "Instead of scripted testing",
      "B",
      "Exploratory testing excels when requirements are unclear or incomplete, and when searching for unscripted bugs that formal tests miss.",
    ],
    [
      "What should an exploratory testing session report contain at minimum?",
      "Just the bugs found",
      "Charter, tester name, duration, key findings, bugs filed, and observations",
      "Detailed test case steps",
      "Test coverage percentage",
      "B",
      "Session reports document what was explored, findings, and bugs; this creates continuity and accountability for exploratory efforts.",
    ],
    [
      "Which heuristic is useful for testing permission-based bugs?",
      "CRUD",
      "Asking: Can role X access what only role Y should see? What about cross-user data?",
      "Only testing the happy path",
      "Performance heuristics",
      "B",
      "Permission testing targets authorization flaws (IDOR — Insecure Direct Object Reference) — a common security vulnerability.",
    ],
    [
      "What does the FEW HICCUPS heuristic cover?",
      "Only functional testing",
      "Functions, Error handling, Workflow, Hardware, Interfaces, Compatibility, Concurrency, Usability, Performance, Security",
      "UI layout issues",
      "Database schema",
      "B",
      "FEW HICCUPS is a comprehensive heuristic covering both functional and non-functional areas, ensuring broad test coverage.",
    ],
    [
      "How can a mind map enhance exploratory testing preparation?",
      "It replaces the need for testing",
      "It generates test ideas by branching concepts, helping testers think systematically about areas to explore",
      "It predicts all bugs",
      "It writes test cases automatically",
      "B",
      "Mind maps visually organize concepts and generate test ideas before a session, ensuring the tester thinks broadly about the feature.",
    ],
    [
      "What makes documentation important in exploratory testing?",
      "It slows down testing",
      "Notes and session reports create traceability, enable knowledge sharing, and help replay findings if needed",
      "Documentation is not needed in exploratory testing",
      "Only for compliance purposes",
      "B",
      "Even though exploratory testing is flexible, documentation ensures findings aren't lost and enables others to build on discoveries.",
    ],
  ] as const,

  "Introduction to API Testing": [
    [
      "What does REST stand for in the context of APIs?",
      "Rapid Endpoint Service Testing",
      "Representational State Transfer",
      "Request-Response Execution System",
      "Resource Entity Service Transaction",
      "B",
      "REST (Representational State Transfer) is an architectural style for APIs using HTTP methods to perform actions on resources identified by URLs.",
    ],
    [
      "What HTTP status code indicates a successful resource creation?",
      "200 OK",
      "201 Created",
      "202 Accepted",
      "204 No Content",
      "B",
      "201 Created indicates a POST request successfully created a new resource; it typically includes the created resource in the response.",
    ],
    [
      "What HTTP method is used to partially update a resource?",
      "POST",
      "PUT",
      "PATCH",
      "DELETE",
      "C",
      "PATCH updates specific fields of a resource. PUT replaces the entire resource, requiring all fields. PATCH is more flexible for partial updates.",
    ],
    [
      "Why is API testing considered more efficient than UI testing?",
      "API tests don't require test data",
      "API tests are faster, more stable (less UI churn), and can validate business logic without a working UI",
      "UI testing is never reliable",
      "APIs don't have bugs",
      "B",
      "API tests run in milliseconds vs seconds, provide more stable feedback (APIs change less than UIs), and enable early testing of logic.",
    ],
    [
      "What should be verified for every API endpoint?",
      "Only the status code",
      "Status code, response body correctness, response time, error messages, authentication/authorization, data persistence, schema compliance",
      "Only the response body",
      "Only that it doesn't crash",
      "B",
      "Comprehensive API testing covers status codes, response format/values, performance, security (auth/authz), and persistence.",
    ],
    [
      "What does HTTP status 422 indicate?",
      "Server error",
      "The request syntax is invalid",
      "Semantically invalid input — the request is well-formed but the values don't make business sense",
      "Rate limit exceeded",
      "C",
      "422 Unprocessable Entity means the server understood the request but can't process it due to semantic errors (e.g., invalid email format, duplicate username).",
    ],
    [
      "In API testing, what is the purpose of checking authorization besides authentication?",
      "They serve the same purpose",
      "Authentication verifies identity; authorization verifies permissions — ensuring users cannot access data they shouldn't see",
      "Authorization is only for APIs",
      "It improves performance",
      "B",
      "Authorization testing catches IDOR (Insecure Direct Object Reference) and permission flaws — users shouldn't access other users' data.",
    ],
  ] as const,
} as const;

export const beginnerSupplementQuizzes = toQuizRows(beginnerSupplementBanks);
